// 北大消消乐 · 考研题库 v1.0
const QUESTION_BANK = {
'101': [
{id:'101-01',type:'single',stem:'马克思主义哲学认为，世界的本原是：',options:['A. 物质','B. 意识','C. 实践','D. 矛盾'],answer:'A',analysis:'马克思主义哲学是彻底的唯物主义，认为世界的本原是物质。物质第一性，意识第二性。',chapter:'马原',difficulty:1},
{id:'101-02',type:'single',stem:'唯物辩证法的实质和核心是：',options:['A. 质量互变规律','B. 否定之否定规律','C. 对立统一规律','D. 联系和发展'],answer:'C',analysis:'对立统一规律（即矛盾规律）是唯物辩证法的实质和核心，揭示了事物发展的源泉和动力。',chapter:'马原',difficulty:2},
{id:'101-03',type:'single',stem:'实践是检验真理的唯一标准，这是由真理的本性和实践的特点所决定的。实践作为检验真理的标准，既是确定的又是不确定的，其不确定性是因为：',options:['A. 任何实践都是具体的、历史的','B. 实践可以随意改变','C. 实践是主观的','D. 真理是绝对的'],answer:'A',analysis:'实践标准的不确定性是指任何实践都是一定历史条件下的具体实践，都有其历史局限性。',chapter:'马原',difficulty:3},
{id:'101-04',type:'single',stem:'社会意识相对独立性最突出的表现是：',options:['A. 社会意识与社会存在的不完全同步性','B. 社会意识内部各形式之间的影响','C. 社会意识的历史继承性','D. 社会意识对社会存在的能动反作用'],answer:'D',analysis:'社会意识的能动反作用是其相对独立性最突出、最重要的表现。先进的社会意识推动社会发展。',chapter:'马原',difficulty:2},
{id:'101-05',type:'single',stem:'毛泽东思想活的灵魂的三个基本方面是：',options:['A. 实事求是、群众路线、独立自主','B. 统一战线、武装斗争、党的建设','C. 理论联系实际、密切联系群众、批评与自我批评','D. 解放思想、实事求是、与时俱进'],answer:'A',analysis:'实事求是、群众路线、独立自主是毛泽东思想活的灵魂的三个基本方面，贯穿于毛泽东思想各个组成部分。',chapter:'毛中特',difficulty:2},
{id:'101-06',type:'single',stem:'新民主主义革命的三大法宝是：',options:['A. 土地革命、武装斗争、根据地建设','B. 统一战线、武装斗争、党的建设','C. 实事求是、群众路线、独立自主','D. 政治、经济、文化'],answer:'B',analysis:'统一战线、武装斗争、党的建设是中国革命的三大法宝，是毛泽东在《〈共产党人〉发刊词》中总结的。',chapter:'毛中特',difficulty:1},
{id:'101-07',type:'single',stem:'中国近代史上第一个不平等条约是：',options:['A. 《北京条约》','B. 《马关条约》','C. 《南京条约》','D. 《辛丑条约》'],answer:'C',analysis:'1842年签订的《南京条约》是中国近代史上第一个不平等条约，标志着中国开始沦为半殖民地半封建社会。',chapter:'史纲',difficulty:1},
{id:'101-08',type:'single',stem:'标志着中国新民主主义革命开端的历史事件是：',options:['A. 辛亥革命','B. 新文化运动','C. 五四运动','D. 中共一大'],answer:'C',analysis:'1919年五四运动标志着中国新民主主义革命的开端，工人阶级开始以独立的政治力量登上历史舞台。',chapter:'史纲',difficulty:1},
{id:'101-09',type:'single',stem:'社会主义核心价值观中，属于国家层面的价值目标是：',options:['A. 自由、平等、公正、法治','B. 富强、民主、文明、和谐','C. 爱国、敬业、诚信、友善','D. 创新、协调、绿色、开放、共享'],answer:'B',analysis:'社会主义核心价值观三个层面：国家层面（富强、民主、文明、和谐）、社会层面（自由、平等、公正、法治）、个人层面（爱国、敬业、诚信、友善）。',chapter:'思修',difficulty:1},
{id:'101-10',type:'single',stem:'我国宪法规定，中华人民共和国的根本制度是：',options:['A. 人民代表大会制度','B. 社会主义制度','C. 民主集中制','D. 多党合作制度'],answer:'B',analysis:'《宪法》第一条规定：社会主义制度是中华人民共和国的根本制度。',chapter:'思修',difficulty:1},
{id:'101-11',type:'multi',stem:'下列属于唯物辩证法基本规律的有：',options:['A. 对立统一规律','B. 质量互变规律','C. 否定之否定规律','D. 因果律'],answer:'ABC',analysis:'唯物辩证法的三大基本规律是：对立统一规律、质量互变规律、否定之否定规律。因果律不属于基本规律。',chapter:'马原',difficulty:2},
{id:'101-12',type:'multi',stem:'新发展理念包括：',options:['A. 创新、协调','B. 绿色、开放','C. 共享','D. 稳定'],answer:'ABC',analysis:'新发展理念是创新、协调、绿色、开放、共享，D项"稳定"不属于新发展理念的内容。',chapter:'毛中特',difficulty:1},
{id:'101-13',type:'judge',stem:'生产力决定生产关系，生产关系对生产力没有任何反作用。',options:['A. 正确','B. 错误'],answer:'B',analysis:'生产力决定生产关系，但生产关系对生产力具有能动的反作用。适合的生产关系促进生产力发展，不适合的则阻碍。',chapter:'马原',difficulty:1},
{id:'101-14',type:'judge',stem:'中国共产党第一次全国代表大会于1921年在上海召开。',options:['A. 正确','B. 错误'],answer:'A',analysis:'中共一大于1921年7月23日在上海法租界望志路106号开幕，后转至浙江嘉兴南湖一艘游船上闭幕。',chapter:'史纲',difficulty:1},
{id:'101-15',type:'single',stem:'习近平新时代中国特色社会主义思想明确中国特色社会主义最本质的特征是：',options:['A. 人民当家作主','B. 中国共产党领导','C. 依法治国','D. 社会主义市场经济'],answer:'B',analysis:'党的十九大明确：中国特色社会主义最本质的特征是中国共产党领导。',chapter:'毛中特',difficulty:2},
],
'201': [
{id:'201-01',type:'single',stem:'Choose the best word: The government has _____ new policies to address climate change.',options:['A. implemented','B. implied','C. imported','D. imposed'],answer:'A',analysis:'implement意为"实施、执行"。句意：政府实施了新政策来应对气候变化。imply暗示，import进口，impose强加。',chapter:'词汇',difficulty:2},
{id:'201-02',type:'single',stem:'The word "ubiquitous" most nearly means:',options:['A. rare','B. everywhere','C. dangerous','D. expensive'],answer:'B',analysis:'ubiquitous = existing everywhere, omnipresent（无处不在的）。考研英语高频词汇。',chapter:'词汇',difficulty:2},
{id:'201-03',type:'single',stem:'Choose the correct grammar: Neither the teacher nor the students _____ aware of the change.',options:['A. is','B. are','C. was','D. has been'],answer:'B',analysis:'neither...nor连接并列主语时，谓语动词遵循就近原则，与students一致用复数are。',chapter:'语法',difficulty:2},
{id:'201-04',type:'single',stem:'The phrase "a far cry from" means:',options:['A. very similar to','B. very different from','C. close to','D. derived from'],answer:'B',analysis:'a far cry from = very different from（与...相差甚远）。常见考研阅读理解短语。',chapter:'词汇',difficulty:2},
{id:'201-05',type:'single',stem:'Fill in: Had I known the truth, I _____ differently.',options:['A. would act','B. would have acted','C. will act','D. acted'],answer:'B',analysis:'虚拟语气：与过去事实相反。Had I known = If I had known, 主句用would have + 过去分词。',chapter:'语法',difficulty:3},
{id:'201-06',type:'single',stem:'The author\'s attitude toward AI regulation can best be described as:',options:['A. wholly supportive','B. cautiously optimistic','C. strongly opposed','D. completely indifferent'],answer:'B',analysis:'考研阅读理解中作者态度题常见选项。cautiously optimistic = 谨慎乐观，是最常见的正确态度选项之一。',chapter:'阅读',difficulty:3},
{id:'201-07',type:'single',stem:'"Notwithstanding" is closest in meaning to:',options:['A. because of','B. in spite of','C. according to','D. instead of'],answer:'B',analysis:'notwithstanding = in spite of / despite（尽管）。考研翻译常考词。',chapter:'词汇',difficulty:3},
{id:'201-08',type:'single',stem:'Choose the best title for a passage about rising sea levels threatening coastal cities:',options:['A. Ocean Wonders','B. The Tide of Change','C. City Life Today','D. Water Sports Guide'],answer:'B',analysis:'The Tide of Change（变化的潮流）最切题，既暗指海平面上升（tide），又暗示变化趋势。考研新题型标题匹配技巧。',chapter:'阅读',difficulty:2},
{id:'201-09',type:'single',stem:'The correct order is: ① However, recent studies suggest otherwise. ② It was long believed that... ③ This finding has significant implications.',options:['A. ②①③','B. ①②③','C. ③②①','D. ②③①'],answer:'A',analysis:'逻辑排序：先陈述传统观点②，然后转折①，最后说影响③。这是考研新题型排序的典型模式。',chapter:'阅读',difficulty:2},
{id:'201-10',type:'single',stem:'"Paradigm shift" in academic context means:',options:['A. minor adjustment','B. fundamental change in approach','C. temporary trend','D. statistical error'],answer:'B',analysis:'paradigm shift = 范式转变，指某一领域基本理论框架的根本性变化。学术文章高频词。',chapter:'词汇',difficulty:3},
{id:'201-11',type:'single',stem:'Translate: "The significance of this study lies in its interdisciplinary approach."',options:['A. 该研究的局限在于跨学科方法','B. 该研究的意义在于其跨学科方法','C. 该研究的困难在于其多学科方法','D. 该研究的目的在于其交叉学科方法'],answer:'B',analysis:'significance = 意义；lie in = 在于；interdisciplinary approach = 跨学科方法。',chapter:'翻译',difficulty:2},
{id:'201-12',type:'judge',stem:'"Economic" and "economical" have the same meaning.',options:['A. True','B. False'],answer:'B',analysis:'economic = 经济的（与经济有关的）；economical = 节约的、省钱的。两者含义不同。',chapter:'词汇',difficulty:1},
{id:'201-13',type:'single',stem:'The tone of the passage is best described as:',options:['A. sarcastic','B. objective','C. emotional','D. humorous'],answer:'B',analysis:'学术文章通常采用客观(objective)的语气。sarcastic讽刺的，emotional情绪化的，humorous幽默的。',chapter:'阅读',difficulty:2},
{id:'201-14',type:'single',stem:'Which conjunction best fills the blank: "_____ the rain, the match continued."',options:['A. Despite','B. Although','C. Because','D. Unless'],answer:'A',analysis:'Despite + 名词（the rain）表让步。Although后跟从句。句意：尽管下雨，比赛继续进行。',chapter:'语法',difficulty:1},
{id:'201-15',type:'single',stem:'"To shed light on" means:',options:['A. to darken','B. to clarify or explain','C. to ignore','D. to complicate'],answer:'B',analysis:'shed light on = 阐明、解释。学术写作和考研阅读中的高频表达。',chapter:'词汇',difficulty:2},
],
'301': [
{id:'301-01',type:'single',stem:'lim(x→0) sin(x)/x 的值为：',options:['A. 0','B. 1','C. ∞','D. 不存在'],answer:'B',analysis:'这是第一个重要极限：lim(x→0) sin(x)/x = 1。考研数学必背公式。',chapter:'高数-极限',difficulty:1},
{id:'301-02',type:'single',stem:'函数f(x)=|x|在x=0处：',options:['A. 可导且连续','B. 连续但不可导','C. 可导但不连续','D. 既不连续也不可导'],answer:'B',analysis:'f(x)=|x|在x=0处连续（左右极限等于函数值），但不可导（左导数=-1，右导数=1，不相等）。',chapter:'高数-微分',difficulty:2},
{id:'301-03',type:'single',stem:'∫₀¹ x² dx 的值为：',options:['A. 1/2','B. 1/3','C. 1/4','D. 1'],answer:'B',analysis:'∫₀¹ x² dx = [x³/3]₀¹ = 1/3 - 0 = 1/3。基本定积分计算。',chapter:'高数-积分',difficulty:1},
{id:'301-04',type:'single',stem:'设A是3阶矩阵，|A|=2，则|2A|=',options:['A. 4','B. 8','C. 16','D. 6'],answer:'C',analysis:'|kA| = k^n |A|，其中n为矩阵阶数。|2A| = 2³×|A| = 8×2 = 16。',chapter:'线代-行列式',difficulty:2},
{id:'301-05',type:'single',stem:'n阶单位矩阵E的特征值为：',options:['A. 全为0','B. 全为1','C. 全为n','D. 全为-1'],answer:'B',analysis:'单位矩阵E的特征方程|E-λE|=0，即(1-λ)^n=0，所以λ=1（n重）。',chapter:'线代-特征值',difficulty:1},
{id:'301-06',type:'single',stem:'设随机变量X~N(0,1)，则P(X>0)=',options:['A. 0','B. 0.25','C. 0.5','D. 1'],answer:'C',analysis:'标准正态分布关于x=0对称，所以P(X>0) = P(X<0) = 0.5。',chapter:'概率-正态分布',difficulty:1},
{id:'301-07',type:'single',stem:'微分方程 y\' + 2y = 0 的通解为：',options:['A. y = Ce^(2x)','B. y = Ce^(-2x)','C. y = C/x²','D. y = Cx²'],answer:'B',analysis:'一阶齐次线性ODE，y\'/y = -2，积分得 ln|y| = -2x + C₁，即 y = Ce^(-2x)。',chapter:'高数-微分方程',difficulty:2},
{id:'301-08',type:'single',stem:'级数 Σ(n=1,∞) 1/n 的敛散性为：',options:['A. 收敛','B. 发散','C. 条件收敛','D. 绝对收敛'],answer:'B',analysis:'调和级数 Σ1/n 发散。这是p级数p=1的情况，p≤1时发散。考研必考知识点。',chapter:'高数-级数',difficulty:2},
{id:'301-09',type:'single',stem:'设A为可逆矩阵，则(A⁻¹)⁻¹=',options:['A. A','B. A²','C. E','D. A⁻²'],answer:'A',analysis:'逆矩阵的逆等于原矩阵：(A⁻¹)⁻¹ = A。因为 A⁻¹·A = E。',chapter:'线代-矩阵',difficulty:1},
{id:'301-10',type:'single',stem:'二重积分 ∬D 1 dσ 的几何意义是：',options:['A. D的周长','B. D的面积','C. D的体积','D. D的质量'],answer:'B',analysis:'∬D 1 dσ 表示区域D的面积。这是二重积分最基本的几何应用。',chapter:'高数-重积分',difficulty:1},
{id:'301-11',type:'single',stem:'事件A和B互斥，P(A)=0.3, P(B)=0.5，则P(A∪B)=',options:['A. 0.15','B. 0.8','C. 0.65','D. 1'],answer:'B',analysis:'互斥事件：P(A∪B) = P(A) + P(B) = 0.3 + 0.5 = 0.8。互斥时AB不能同时发生。',chapter:'概率-基础',difficulty:1},
{id:'301-12',type:'judge',stem:'矩阵A的转置的转置等于A本身，即(Aᵀ)ᵀ = A。',options:['A. 正确','B. 错误'],answer:'A',analysis:'转置的转置等于原矩阵，(Aᵀ)ᵀ = A，这是矩阵转置的基本性质。',chapter:'线代-矩阵',difficulty:1},
{id:'301-13',type:'single',stem:'函数f(x,y)=x²+y²在点(0,0)处取得：',options:['A. 极大值','B. 极小值','C. 鞍点','D. 不确定'],answer:'B',analysis:'f(0,0)=0，对任意(x,y)≠(0,0)，f(x,y)=x²+y²>0=f(0,0)，所以(0,0)是极小值点。',chapter:'高数-多元函数',difficulty:2},
{id:'301-14',type:'single',stem:'向量组α₁=(1,0,0), α₂=(0,1,0), α₃=(0,0,1)的秩为：',options:['A. 1','B. 2','C. 3','D. 0'],answer:'C',analysis:'三个向量线性无关（构成单位矩阵E₃），秩=3。',chapter:'线代-向量',difficulty:1},
{id:'301-15',type:'single',stem:'泊松分布X~P(λ)的期望E(X)=',options:['A. λ²','B. λ','C. 1/λ','D. √λ'],answer:'B',analysis:'泊松分布的期望和方差都等于参数λ：E(X) = D(X) = λ。',chapter:'概率-分布',difficulty:1},
],
'408': [
{id:'408-01',type:'single',stem:'在一个长度为n的顺序表中，删除第i个元素需要移动的元素个数为：',options:['A. n-i','B. n-i+1','C. n-i-1','D. i'],answer:'A',analysis:'删除第i个元素后，第i+1到第n个元素都要前移，共n-i个。',chapter:'数据结构-线性表',difficulty:1},
{id:'408-02',type:'single',stem:'栈的特点是：',options:['A. 先进先出','B. 先进后出','C. 随机存取','D. 顺序存取'],answer:'B',analysis:'栈(Stack)是后进先出(LIFO)的线性表，也叫先进后出(FILO)。队列才是先进先出。',chapter:'数据结构-栈和队列',difficulty:1},
{id:'408-03',type:'single',stem:'具有n个结点的完全二叉树的深度为：',options:['A. ⌊log₂n⌋','B. ⌊log₂n⌋+1','C. ⌈log₂n⌉','D. n/2'],answer:'B',analysis:'完全二叉树深度 = ⌊log₂n⌋ + 1。如n=7，深度=⌊2.8⌋+1=3。',chapter:'数据结构-树',difficulty:2},
{id:'408-04',type:'single',stem:'快速排序的平均时间复杂度为：',options:['A. O(n)','B. O(n log n)','C. O(n²)','D. O(log n)'],answer:'B',analysis:'快速排序平均O(n log n)，最坏O(n²)（已排序时）。是实际应用中最快的排序算法之一。',chapter:'数据结构-排序',difficulty:1},
{id:'408-05',type:'single',stem:'在计算机中，一个字节(Byte)由多少个二进制位(bit)组成？',options:['A. 4','B. 8','C. 16','D. 32'],answer:'B',analysis:'1 Byte = 8 bits。这是计算机最基本的存储单位换算。',chapter:'组成原理-数据表示',difficulty:1},
{id:'408-06',type:'single',stem:'CPU中，用于存放下一条将要执行的指令地址的寄存器是：',options:['A. IR(指令寄存器)','B. PC(程序计数器)','C. AR(地址寄存器)','D. DR(数据寄存器)'],answer:'B',analysis:'PC（Program Counter）程序计数器始终指向下一条要执行的指令的地址。IR存放当前正在执行的指令。',chapter:'组成原理-CPU',difficulty:2},
{id:'408-07',type:'single',stem:'以下哪种存储器的访问速度最快？',options:['A. 主存(DRAM)','B. 寄存器','C. Cache','D. 磁盘'],answer:'B',analysis:'速度排序：寄存器 > Cache > 主存(DRAM) > 磁盘。寄存器在CPU内部，速度最快。',chapter:'组成原理-存储器',difficulty:1},
{id:'408-08',type:'single',stem:'进程和线程的主要区别是：',options:['A. 进程是资源分配的基本单位，线程是CPU调度的基本单位','B. 线程是资源分配的基本单位','C. 进程比线程占用更少的资源','D. 二者没有区别'],answer:'A',analysis:'进程是资源分配最小单位，线程是CPU调度最小单位。同一进程的线程共享进程资源。',chapter:'操作系统-进程管理',difficulty:2},
{id:'408-09',type:'single',stem:'产生死锁的四个必要条件中，不包括：',options:['A. 互斥条件','B. 请求与保持','C. 抢占条件','D. 循环等待'],answer:'C',analysis:'死锁四个必要条件：互斥、请求与保持、不可抢占（非抢占）、循环等待。"抢占条件"恰恰相反，应为"不可抢占"。',chapter:'操作系统-死锁',difficulty:2},
{id:'408-10',type:'single',stem:'虚拟内存使用的页面置换算法中，LRU代表：',options:['A. 最近最久未使用','B. 最近最少使用','C. 先进先出','D. 最优置换'],answer:'A',analysis:'LRU = Least Recently Used，最近最久未使用。淘汰最长时间没被访问的页面。',chapter:'操作系统-内存管理',difficulty:2},
{id:'408-11',type:'single',stem:'OSI参考模型共分为几层？',options:['A. 4层','B. 5层','C. 7层','D. 3层'],answer:'C',analysis:'OSI七层模型：物理层、数据链路层、网络层、传输层、会话层、表示层、应用层。TCP/IP是4层。',chapter:'计算机网络-体系结构',difficulty:1},
{id:'408-12',type:'single',stem:'TCP协议提供的是哪种服务？',options:['A. 无连接不可靠','B. 无连接可靠','C. 面向连接可靠','D. 面向连接不可靠'],answer:'C',analysis:'TCP是面向连接的可靠传输协议。UDP是无连接不可靠的。',chapter:'计算机网络-传输层',difficulty:1},
{id:'408-13',type:'single',stem:'IP地址192.168.1.1属于哪类地址？',options:['A. A类','B. B类','C. C类','D. D类'],answer:'C',analysis:'192.168.x.x属于C类私有地址范围（192.168.0.0~192.168.255.255）。C类地址首字节192-223。',chapter:'计算机网络-网络层',difficulty:1},
{id:'408-14',type:'single',stem:'哈夫曼树(最优二叉树)中，权值越大的叶子结点离根结点：',options:['A. 越近','B. 越远','C. 距离相同','D. 不确定'],answer:'A',analysis:'哈夫曼树的构造原则：权值大的结点离根近，权值小的离根远，使得WPL(带权路径长度)最小。',chapter:'数据结构-树',difficulty:2},
{id:'408-15',type:'single',stem:'图的深度优先搜索(DFS)使用的数据结构是：',options:['A. 队列','B. 栈','C. 堆','D. 散列表'],answer:'B',analysis:'DFS用栈（或递归，本质也是栈）。BFS用队列。这是图遍历的核心区别。',chapter:'数据结构-图',difficulty:1},
]
};
