var QB={'408':[
{q:'O(nlogn)排序',o:['冒泡','归并','选择','插入'],a:1},{q:'TCP层',o:['网络','传输','应用','链路'],a:1},{q:'LRU',o:['最近最少使用','FIFO','最不常用','随机'],a:0},{q:'IPv4长度',o:['16','32','64','128'],a:1},{q:'进程vs线程',o:['进程独立空间','不能并发','进程更轻','不共享'],a:0},{q:'哈夫曼',o:['等长','前缀','后缀','ASCII'],a:1},{q:'死锁不含',o:['互斥','请求保持','循环等待','可抢占'],a:3},{q:'B+树数据',o:['叶节点','根','所有','分支'],a:0},{q:'握手第二次',o:['SYN','ACK','SYN+ACK','FIN'],a:2},{q:'虚拟内存',o:['局部性','缓存','流水线','中断'],a:0},{q:'栈',o:['FIFO','LIFO','随机','双端'],a:1},{q:'DNS',o:['仅TCP','仅UDP','TCP+UDP','ICMP'],a:2},{q:'HTTP端口',o:['21','25','80','443'],a:2},{q:'快排最坏',o:['O(n)','O(nlogn)','O(n²)','O(logn)'],a:2},{q:'BFS用',o:['栈','队列','堆','树'],a:1},{q:'堆排空间',o:['O(1)','O(n)','O(logn)','O(nlogn)'],a:0},{q:'ARP',o:['IP→MAC','MAC→IP','域名→IP','IP→域名'],a:0},{q:'SCAN别名',o:['FCFS','电梯','最短','CSCAN'],a:1},{q:'cache高因',o:['局部性','容量','速度','总线'],a:0},{q:'子网掩码',o:['划分','加密','路由','纠错'],a:0},{q:'TCP可靠',o:['校验序号确认重传','仅校验','仅重传','无'],a:0},{q:'页表',o:['逻辑→物理','物理→逻辑','分配','回收'],a:0},{q:'FCFS',o:['最短优先','先来先服务','时间片','优先级'],a:1},{q:'完全二叉树高',o:['log₂n','⌊log₂n⌋+1','n/2','n'],a:1},{q:'第i层最多',o:['2^i','2^(i-1)','i','2i'],a:1}
],'301':[
{q:'x³-3x在x=1导数',o:['0','3','-3','6'],a:0},{q:'∫2xdx',o:['x²+C','2x²+C','x²/2','2x+C'],a:0},{q:'Σ1/n²',o:['发散','收敛','振荡','不定'],a:1},{q:'eˣ泰勒',o:['1+x+x²','1+x+x²/2','x+x²+x³','1+2x'],a:1},{q:'(1,2,3)(2,4,6)',o:['正交','无关','相关','互逆'],a:2},{q:'特征值2,3行列式',o:['5','6','1','-1'],a:1},{q:'拉格朗日',o:['可微','连续','有界','单调'],a:1},{q:'A可逆',o:['|A|=0','|A|≠0','对称','正定'],a:1},{q:'lim sinx/x',o:['0','1','∞','不存在'],a:1},{q:'维数=',o:['基个数','向量数','元素数','秩'],a:0},{q:"y'+y=0",o:['Ceˣ','Ce⁻ˣ','Cx','C/x'],a:1},{q:'正定特征值',o:['全正','全负','全零','不定'],a:0},{q:'行列式项数',o:['n','n!','2ⁿ','n²'],a:1},{q:'梯度',o:['增最快','减最快','不变','随机'],a:0},{q:'收敛必要',o:['通项→0','通项→1','有界','单调'],a:0},{q:'隐函数',o:['Fy≠0','Fx≠0','F=0','F>0'],a:0},{q:'Fourier',o:['函数','均值','0','1'],a:1},{q:'标准形',o:['只含平方','只含交叉','全0','全1'],a:0},{q:'散度',o:['源强度','旋转','方向','速度'],a:0},{q:'∬1dA圆',o:['1','π','2π','4π'],a:1},{q:"y'=ky",o:['Ceᵏˣ','Ckx','C+kx','k/x'],a:0},{q:'Stokes',o:['曲面曲线','二三重','面体积','长面'],a:0},{q:'格林',o:['单连通','多连通','无限','任意'],a:0},{q:'Jacobi',o:['偏导阵','逆阵','转置','伴随'],a:0},{q:'Cauchy推广',o:['拉格朗日','罗尔','泰勒','Stokes'],a:0}
],'201':[
{q:'Ubiquitous',o:['rare','omnipresent','obsolete','unique'],a:1},{q:'If I___rich',o:['was','were','am','will be'],a:1},{q:'Serendipity',o:['bad luck','planned','fortunate accident','research'],a:2},{q:'Pragmatic',o:['idealistic','practical','theoretical','emotional'],a:1},{q:'Ephemeral',o:['eternal','short-lived','important','trivial'],a:1},{q:'New leaf',o:['读书','重新开始','放弃','入睡'],a:1},{q:'Whom',o:['主格','宾格','所有格','任意'],a:1},{q:'Ambiguous',o:['clear','uncertain','angry','happy'],a:1},{q:'Resilient',o:['fragile','recover','rigid','weak'],a:1},{q:'Paradox',o:['agreement','contradiction','parallel','example'],a:1},{q:'Albeit',o:['because','although','therefore','however'],a:1},{q:'Ameliorate',o:['worsen','improve','maintain','destroy'],a:1},{q:'Dichotomy',o:['unity','division','trilogy','multiple'],a:1},{q:'Connotation',o:['字面义','隐含义','同义','反义'],a:1},{q:'Substantiate',o:['deny','prove','ignore','delay'],a:1},{q:'完形',o:['词义逻辑','语法','翻译','写作'],a:0},{q:'推断标志',o:['infer','define','list','compare'],a:0},{q:'长难句',o:['主谓','定状','补语','插入语'],a:0},{q:'增译',o:['补充','删除','直译','音译'],a:0},{q:'小作文',o:['称呼正文落款','标题正文','摘要','目录'],a:0},{q:'大作文',o:['描述分析总结','仅描述','仅议论','叙事'],a:0},{q:'虚拟语气',o:['过去','现在假设','将来','经常'],a:1},{q:'which/that',o:['非限定which','限定which','无区别','都不能'],a:0},{q:'Phenomena',o:['phenomenons','phenomenas','phenomena','phenomeni'],a:2},{q:'Neither nor',o:['跟最近','跟最远','单数','复数'],a:0}
],'101':[
{q:'辩证法核心',o:['质量互变','对立统一','否定之否定','因果'],a:1},{q:'新发展理念首',o:['创新','协调','绿色','共享'],a:0},{q:'民主集中制',o:['少服从多','集体','根本组织原则','党管'],a:2},{q:'物质性',o:['地理','人口','生产方式','资源'],a:2},{q:'实践认识',o:['来源','动力','目的','以上都是'],a:3},{q:'中特开创',o:['毛','邓小平','江','胡'],a:1},{q:'改革开放',o:['1976','1978','1980','1982'],a:1},{q:'全面不含',o:['建设','深化','依法','创新'],a:3},{q:'五位不含',o:['经济','政治','文化','军事'],a:3},{q:'一带一路',o:['丝路+海丝','铁路','国内外','东西'],a:0},{q:'命运共同体',o:['邓','习近平','江','胡'],a:1},{q:'价值观层面',o:['2','3','4','5'],a:1},{q:'矛盾转化',o:['2012','2015','2017','2019'],a:2},{q:'百年第一',o:['2021小康','2035','2049','2025'],a:0},{q:'供给侧',o:['三去一降一补','四个全面','五位一体','六稳'],a:0},{q:'生态',o:['绿水青山','发展优先','效率','速度'],a:0},{q:'全过程民主',o:['选举协商决策管理监督','仅选举','仅协商','仅监督'],a:0},{q:'乡村不含',o:['产业兴旺','生态宜居','乡风文明','城镇化'],a:3},{q:'二十大',o:['中国式现代化','改革开放','科学','和谐'],a:0},{q:'新质',o:['创新','资本','劳动','土地'],a:0},{q:'共同富裕',o:['同步','同等','普遍+差别','平均'],a:2},{q:'安全观',o:['政治安全','经济','军事','文化'],a:0},{q:'现代化特征',o:['3','4','5','6'],a:2},{q:'活灵魂',o:['矛盾','具体问题具体分析','阶级','经济'],a:1},{q:'专政本质',o:['阶级','人民当家作主','民主集中','多党'],a:1}
]};

var MP=[{n:'海岛',s:'408',bg:'#050f20',g:'rgba(0,100,200,.05)',t:'#0a3060',tl:'#0d4080',gn:'#081828',p:'#0af',z:'rgba(0,100,255,'},{n:'雨林',s:'301',bg:'#061a06',g:'rgba(0,180,60,.06)',t:'#0a4a0a',tl:'#1a6a1a',gn:'#0a200a',p:'#0f0',z:'rgba(0,200,80,'},{n:'沙漠',s:'201',bg:'#1a1005',g:'rgba(200,150,50,.05)',t:'#4a3a10',tl:'#6a5020',gn:'#201808',p:'#fa0',z:'rgba(200,150,0,'},{n:'雪地',s:'101',bg:'#101420',g:'rgba(150,180,255,.06)',t:'#2a3a5a',tl:'#4a5a7a',gn:'#181c2a',p:'#aaf',z:'rgba(100,150,255,'}];
var NM=['张三丰','王重阳','丘处机','萧峰','段誉','虚竹','令狐冲','张无忌','杨过','郭靖','黄蓉','韦小宝','东方不败','任盈盈','灭绝师太','周芷若','赵敏','小龙女','黄药师'];
var LV=['炼气','筑基','金丹','元婴','化神','合体','大乘','渡劫'];
var LT=[{e:'🩹',n:'绷带',hp:10},{e:'🥤',n:'可乐',hp:15},{e:'💊',n:'急救包',hp:25},{e:'🛡',n:'护盾',def:3},{e:'⚡',n:'增伤',atk:3},{e:'📖',n:'窥探',hint:1},{e:'🎯',n:'倍镜',range:1}];
var W,H,cx,mc,mi=0,SZ=2400,TL=48,P,bots,lts,ads,zn,gt,go,kl,cb,mxC,xp,aL,wr,ky={},qA=false,cB,qTm,qTmI,adO=false,cm={x:0,y:0},pt=[];
var jDx=0,jDy=0,gS;
function selMap(i){mi=i;document.querySelectorAll('.map-card').forEach(function(c,j){c.classList.toggle('sel',j===i)})}
function R(a,b){return a+Math.random()*(b-a)}
function startGame(){
document.getElementById('lobbyS').classList.remove('on');var c=document.getElementById('C');W=c.width=innerWidth;H=c.height=innerHeight;
cx=c.getContext('2d');mc=document.getElementById('M').getContext('2d');window.onresize=function(){W=c.width=innerWidth;H=c.height=innerHeight};
P={x:SZ/2+R(-200,200),y:SZ/2+R(-200,200),hp:100,sp:3,an:0,sh:0,at:0,hi:0,rn:0,bd:2,co:1,md:0};
bots=[];kl=0;cb=0;mxC=0;xp=0;gt=0;go=false;aL=[];wr=[];
for(var i=0;i<19;i++){var a=R(0,6.28),d=400+R(0,700);bots.push({x:SZ/2+Math.cos(a)*d,y:SZ/2+Math.sin(a)*d,hp:50+R(0,50),sp:1+R(0,1.5),alive:true,nm:NM[i],mt:0,md:R(0,6.28),sk:.3+R(0,.5),cl:'hsl('+~~R(0,360)+',65%,55%)',lt:[LT[~~R(0,LT.length)]]})}
lts=[];for(var i=0;i<25;i++)lts.push({x:200+R(0,SZ-400),y:200+R(0,SZ-400),tp:LT[~~R(0,LT.length)],tk:false,nq:true});
ads=[];for(var i=0;i<4;i++)ads.push({x:500+R(0,SZ-1000),y:500+R(0,SZ-1000),op:false,fy:-200-i*300,ld:false});
zn={cx:SZ/2,cy:SZ/2,r:SZ/2,tr:SZ/2,dm:1};gS=Date.now();requestAnimationFrame(lp)}
function lp(){if(go)return;gt++;uP();uB();uZ();cZ();bF();uAD();pt=pt.filter(function(p){p.x+=p.vx;p.y+=p.vy;p.life--;return p.life>0});dR();dMM();uH();
var rem=Math.max(0,900-(Date.now()-gS)/1000),mm=~~(rem/60),ss=~~(rem%60);document.getElementById('gTimer').textContent='⏱ '+mm+':'+(ss<10?'0':'')+ss;
if(rem<=0&&!go)eG(bots.filter(function(b){return b.alive}).length===0);requestAnimationFrame(lp)}
function uP(){if(qA||adO)return;var dx=jDx,dy=jDy;if(ky['w']||ky['arrowup'])dy=-1;if(ky['s']||ky['arrowdown'])dy=1;if(ky['a']||ky['arrowleft'])dx=-1;if(ky['d']||ky['arrowright'])dx=1;
if(dx||dy){var l=Math.sqrt(dx*dx+dy*dy);P.x+=dx/l*P.sp;P.y+=dy/l*P.sp;P.an=Math.atan2(dy,dx);if(gt%8===0)pt.push({x:P.x,y:P.y,vx:R(-.5,.5),vy:R(-.5,.5),life:20,c:MP[mi].p,sz:2})}
P.x=Math.max(10,Math.min(SZ-10,P.x));P.y=Math.max(10,Math.min(SZ-10,P.y))}
function uB(){bots.forEach(function(b){if(!b.alive)return;b.mt--;if(b.mt<=0){b.md=R(0,6.28);b.mt=80+R(0,120)}var dx=zn.cx-b.x,dy=zn.cy-b.y,d=Math.sqrt(dx*dx+dy*dy);
if(d>zn.r*.65){b.x+=dx/d*b.sp*.9;b.y+=dy/d*b.sp*.9}else{b.x+=Math.cos(b.md)*b.sp*.4;b.y+=Math.sin(b.md)*b.sp*.4}b.x=Math.max(10,Math.min(SZ-10,b.x));b.y=Math.max(10,Math.min(SZ-10,b.y))})}
function uZ(){[[7200,10800,SZ*.4,1],[14400,17100,SZ*.25,2],[21600,23400,SZ*.12,4],[30600,31800,SZ*.04,8]].forEach(function(p){if(gt>=p[0]&&gt<=p[1]){var t=(gt-p[0])/(p[1]-p[0]);zn.r=zn.tr+(p[2]-zn.tr)*t;zn.dm=p[3]}if(gt===p[1])zn.tr=p[2]})}
function cZ(){var dx=P.x-zn.cx,dy=P.y-zn.cy;if(Math.sqrt(dx*dx+dy*dy)>zn.r){P.hp-=zn.dm*.015;document.getElementById('zw').classList.add('on')}else{document.getElementById('zw').classList.remove('on')}
bots.forEach(function(b){if(!b.alive)return;var dx=b.x-zn.cx,dy=b.y-zn.cy;if(Math.sqrt(dx*dx+dy*dy)>zn.r)b.hp-=zn.dm*.025;if(b.hp<=0){b.alive=false;aKF(b.nm+' 毒圈淘汰');dL(b)}});
if(P.hp<=0&&!go)eG(false);if(bots.filter(function(b){return b.alive}).length===0&&!go)eG(true)}
function uAD(){ads.forEach(function(a){if(a.op||a.ld)return;a.fy+=1.5;if(a.fy>=a.y){a.fy=a.y;a.ld=true;aKF('📦 空投落地！')}})}
function dL(b){b.lt.forEach(function(l){lts.push({x:b.x+R(-20,20),y:b.y+R(-20,20),tp:l,tk:false,nq:false})})}
document.addEventListener('keydown',function(e){var k=e.key.toLowerCase();ky[k]=true;ky[e.code]=true;if(e.code==='Space'&&!qA&&!go&&!adO)tF();if(k==='f'&&!qA&&!adO)tL();if(k==='e'&&!qA)tAD();if(k==='q')uHeal()});
document.addEventListener('keyup',function(e){ky[e.key.toLowerCase()]=false;ky[e.code]=false});
var jE=document.getElementById('joy'),jSt=document.getElementById('joyS');
jE.addEventListener('touchstart',function(e){e.preventDefault()},{passive:false});
jE.addEventListener('touchmove',function(e){e.preventDefault();var t=e.touches[0],r=jE.getBoundingClientRect(),ccx=r.left+60,ccy=r.top+60,dx=t.clientX-ccx,dy=t.clientY-ccy,d=Math.sqrt(dx*dx+dy*dy);if(d>40){dx=dx/d*40;dy=dy/d*40}jSt.style.left=(35+dx)+'px';jSt.style.top=(35+dy)+'px';jDx=dx/40;jDy=dy/40},{passive:false});
jE.addEventListener('touchend',function(){jDx=0;jDy=0;jSt.style.left='35px';jSt.style.top='35px'});
function tF(){var cl=null,mn=80+(P.rn?40:0);bots.forEach(function(b){if(!b.alive)return;var d=Math.sqrt((b.x-P.x)**2+(b.y-P.y)**2);if(d<mn){mn=d;cl=b}});if(cl){cB=cl;sQ('fight')}}
function tL(){var f=null,mn=35;lts.forEach(function(l){if(l.tk)return;var d=Math.sqrt((l.x-P.x)**2+(l.y-P.y)**2);if(d<mn){mn=d;f=l}});if(f){if(f.nq){cB={lr:f};sQ('loot')}else{pL(f)}}}
function pL(l){l.tk=true;var t=l.tp;if(t.hp)P.hp=Math.min(100,P.hp+t.hp);if(t.def)P.sh+=t.def;if(t.atk)P.at+=t.atk;if(t.hint)P.hi+=t.hint;if(t.range)P.rn=1;if(t.e==='🩹')P.bd++;if(t.e==='🥤')P.co++;if(t.e==='💊')P.md++;aKF('拾取 '+t.e+' '+t.n);uBag()}
function tAD(){var f=null,mn=40;ads.forEach(function(a){if(a.op||!a.ld)return;var d=Math.sqrt((a.x-P.x)**2+(a.y-P.y)**2);if(d<mn){mn=d;f=a}});
if(f){f.op=true;adO=true;var pr={'408':'【算法设计】设计O(nlogn)算法将数组偶数前移奇数后移\n提示：稳定排序','301':'【证明题】连续函数在[a,b]取最值\n步骤：有界性→上确界→BW定理','201':'【翻译】AI advancement brings opportunities and challenges...\n请翻译成中文','101':'【分析题】中国式现代化五特征\n1体现什么？2打破西方化？3共同富裕？'};
document.getElementById('adBody').textContent=pr[MP[mi].s];document.getElementById('adP').classList.add('on')}}
function closeAD(){adO=false;document.getElementById('adP').classList.remove('on');P.hp=Math.min(100,P.hp+30);P.sh+=2;P.at+=2;xp+=50;aKF('📦 +30HP+2🛡+2⚡+50EXP');uBag()}
function useHeal(){if(P.co>0&&P.hp<100){P.co--;P.hp=Math.min(100,P.hp+15);aKF('🥤+15HP');uBag()}else if(P.bd>0&&P.hp<100){P.bd--;P.hp=Math.min(100,P.hp+10);aKF('🩹+10HP');uBag()}else if(P.md>0&&P.hp<100){P.md--;P.hp=Math.min(100,P.hp+25);aKF('💊+25HP');uBag()}}
var qM='fight';
function sQ(mode){qM=mode;qA=true;var m=MP[mi],qs=QB[m.s],q=qs[~~(Math.random()*qs.length)];
document.getElementById('qM').innerHTML=mode==='fight'?'遭遇 <b>'+cB.nm+'</b>':'📦拾取答题(不扣血)';
var ht='';if(P.hi>0){var wi;do{wi=~~(Math.random()*4)}while(wi===q.a);ht='<span class="tag">📖排除'+String.fromCharCode(65+wi)+'</span>';P.hi--;uBag()}
document.getElementById('qT').innerHTML='<span class="tag">'+m.s+'</span>'+ht+' '+q.q;
var h='';q.o.forEach(function(o,i){h+='<div class="oo" onclick="dA('+i+','+q.a+')">'+String.fromCharCode(65+i)+'. '+o+'</div>'});
document.getElementById('qO').innerHTML=h;document.getElementById('qov').classList.add('on');qTm=15;document.getElementById('qTm').textContent='⏱'+qTm;clearInterval(qTmI);
qTmI=setInterval(function(){qTm--;document.getElementById('qTm').textContent='⏱'+qTm;if(qTm<=0){clearInterval(qTmI);dA(-1,-1)}},1000);aL.push({q:q.q,opts:q.o,correct:q.a,picked:-1,mode:mode})}
function dA(pk,co){clearInterval(qTmI);var last=aL[aL.length-1];last.picked=pk;
document.querySelectorAll('.qbox .oo').forEach(function(x,i){x.style.pointerEvents='none';if(i===co)x.classList.add('ok');if(i===pk&&i!==co)x.classList.add('no')});
if(qM==='fight'){if(pk===co){cB.alive=false;kl++;cb++;if(cb>mxC)mxC=cb;xp+=20+cb*5;aKF('🎯击杀'+cB.nm);if(cb>=3)sC(cb);dL(cB)}
else{var dm=15-(P.sh>0?5:0);P.hp-=dm;cb=0;if(P.sh>0)P.sh--;wr.push(last);if(cB.lt&&cB.lt.length>0){var dr2=cB.lt.splice(0,1)[0];lts.push({x:cB.x+R(-15,15),y:cB.y+R(-15,15),tp:dr2,tk:false,nq:false});aKF('❌答错'+cB.nm+'掉落'+dr2.e)}}}
else if(qM==='loot'){if(pk===co){pL(cB.lr);xp+=5}else{wr.push(last);aKF('答错不扣血')}}
setTimeout(function(){document.getElementById('qov').classList.remove('on');qA=false;cB=null;if(P.hp<=0)eG(false)},800)}
function skipQ(){clearInterval(qTmI);if(qM==='fight')P.hp-=5;document.getElementById('qov').classList.remove('on');qA=false;cB=null}
function bF(){if(gt%240!==0)return;var a2=bots.filter(function(b){return b.alive});if(a2.length<2)return;for(var i=0;i<a2.length;i++)for(var j=i+1;j<a2.length;j++){var d=Math.sqrt((a2[i].x-a2[j].x)**2+(a2[i].y-a2[j].y)**2);if(d<50){if(Math.random()>a2[j].sk){a2[j].alive=false;aKF(a2[i].nm+'击杀'+a2[j].nm);dL(a2[j])}else if(Math.random()>a2[i].sk){a2[i].alive=false;aKF(a2[j].nm+'击杀'+a2[i].nm);dL(a2[i])}return}}}
function dR(){var m=MP[mi];cx.fillStyle=m.bg;cx.fillRect(0,0,W,H);cm.x=P.x-W/2;cm.y=P.y-H/2;cx.strokeStyle=m.g;cx.lineWidth=1;var sx=(-cm.x%TL+TL)%TL,sy=(-cm.y%TL+TL)%TL;for(var x=sx;x<W;x+=TL){cx.beginPath();cx.moveTo(x,0);cx.lineTo(x,H);cx.stroke()}for(var y=sy;y<H;y+=TL){cx.beginPath();cx.moveTo(0,y);cx.lineTo(W,y);cx.stroke()}
for(var tx=0;tx<SZ;tx+=100)for(var ty=0;ty<SZ;ty+=100){if((tx*7+ty*13)%17<6){var s2=tx-cm.x,s3=ty-cm.y;if(s2>-30&&s2<W+30&&s3>-30&&s3<H+30){cx.fillStyle=m.t;cx.beginPath();cx.arc(s2,s3,14,0,6.28);cx.fill();cx.fillStyle=m.tl;cx.beginPath();cx.arc(s2-3,s3-4,9,0,6.28);cx.fill();cx.fillStyle='rgba(0,0,0,.2)';cx.beginPath();cx.ellipse(s2+2,s3+14,10,4,0,0,6.28);cx.fill()}}}
dZone(m);lts.forEach(function(l){if(l.tk)return;var s2=l.x-cm.x,s3=l.y-cm.y;if(s2<-20||s2>W+20||s3<-20||s3>H+20)return;cx.font='14px serif';cx.fillText(l.tp.e,s2-7,s3+4)});
ads.forEach(function(a){if(a.op)return;var fy=a.ld?a.y:a.fy,s2=a.x-cm.x,s3=fy-cm.y;if(s2<-40||s2>W+40||s3<-40||s3>H+40)return;cx.font='20px serif';cx.fillText('📦',s2-10,s3+6);if(!a.ld){cx.strokeStyle='rgba(255,215,0,.4)';cx.lineWidth=1;cx.beginPath();cx.moveTo(s2,s3-16);cx.lineTo(s2-14,s3-36);cx.moveTo(s2,s3-16);cx.lineTo(s2+14,s3-36);cx.stroke();cx.beginPath();cx.arc(s2,s3-42,16,Math.PI,0);cx.strokeStyle='rgba(255,215,0,.5)';cx.lineWidth=2;cx.stroke()}else{cx.beginPath();cx.arc(s2,s3,20,0,6.28);cx.strokeStyle='rgba(255,215,0,.3)';cx.lineWidth=2;cx.setLineDash([4,4]);cx.stroke();cx.setLineDash([])}});
bots.forEach(function(b){if(!b.alive)return;var s2=b.x-cm.x,s3=b.y-cm.y;if(s2<-40||s2>W+40||s3<-40||s3>H+40)return;cx.fillStyle='rgba(0,0,0,.25)';cx.beginPath();cx.ellipse(s2,s3+12,9,4,0,0,6.28);cx.fill();var gr=cx.createRadialGradient(s2-3,s3-8,2,s2,s3,14);gr.addColorStop(0,b.cl);gr.addColorStop(1,'rgba(0,0,0,.4)');cx.fillStyle=gr;cx.beginPath();cx.arc(s2,s3-6,10,0,6.28);cx.fill();cx.fillRect(s2-6,s3-1,12,13);cx.beginPath();cx.arc(s2,s3+12,6,0,Math.PI);cx.fill();cx.font='9px sans-serif';cx.fillStyle='#999';cx.textAlign='center';cx.fillText(b.nm,s2,s3-20);cx.fillStyle='rgba(255,0,0,.25)';cx.fillRect(s2-12,s3-26,24,3);cx.fillStyle='#f85149';cx.fillRect(s2-12,s3-26,24*(b.hp/100),3);cx.textAlign='left'});
var px=P.x-cm.x,py=P.y-cm.y;cx.fillStyle='rgba(0,0,0,.3)';cx.beginPath();cx.ellipse(px,py+14,11,5,0,0,6.28);cx.fill();cx.shadowColor='rgba(46,160,67,.4)';cx.shadowBlur=16;var pg=cx.createRadialGradient(px-3,py-10,2,px,py,16);pg.addColorStop(0,'#a8ff78');pg.addColorStop(1,'#1a6a1a');cx.fillStyle=pg;cx.beginPath();cx.arc(px,py-8,12,0,6.28);cx.fill();cx.fillRect(px-7,py-1,14,15);cx.beginPath();cx.arc(px,py+14,7,0,Math.PI);cx.fill();cx.shadowBlur=0;cx.strokeStyle='rgba(46,160,67,.5)';cx.lineWidth=2;cx.beginPath();cx.moveTo(px,py);cx.lineTo(px+Math.cos(P.an)*22,py+Math.sin(P.an)*22);cx.stroke();var rng=80+(P.rn?40:0);cx.beginPath();cx.arc(px,py,rng,0,6.28);cx.strokeStyle='rgba(46,160,67,.07)';cx.lineWidth=1;cx.stroke();
pt.forEach(function(p){cx.fillStyle=p.c;cx.globalAlpha=p.life/40;cx.beginPath();cx.arc(p.x-cm.x,p.y-cm.y,p.sz,0,6.28);cx.fill();cx.globalAlpha=1});
if(mi===3&&gt%2===0)for(var i=0;i<3;i++)pt.push({x:P.x+R(-W/2,W/2),y:P.y-H/2,vx:R(-.5,.5),vy:R(1,2),life:60,c:'rgba(200,220,255,.4)',sz:R(1,3)});
if(mi===2&&gt%5===0)for(var i=0;i<2;i++)pt.push({x:P.x+R(-W/2,W/2),y:P.y+R(-H/2,H/2),vx:R(1,3),vy:R(-.5,.5),life:40,c:'rgba(200,180,100,.15)',sz:R(2,6)})}
function dZone(m){var sx=zn.cx-cm.x,sy=zn.cy-cm.y;cx.save();cx.beginPath();cx.rect(0,0,W,H);cx.arc(sx,sy,zn.r,0,6.28,true);cx.closePath();cx.fillStyle=m.z+(.18+Math.sin(gt*.02)*.05)+')';cx.fill();cx.restore();cx.beginPath();cx.arc(sx,sy,zn.r,0,6.28);cx.strokeStyle=m.z+'.5)';cx.lineWidth=3;cx.setLineDash([8,4]);cx.stroke();cx.setLineDash([])}
function dMM(){var s=150/SZ;mc.clearRect(0,0,150,150);mc.fillStyle=MP[mi].gn;mc.fillRect(0,0,150,150);mc.beginPath();mc.arc(zn.cx*s,zn.cy*s,zn.r*s,0,6.28);mc.fillStyle='rgba(46,160,67,.08)';mc.fill();mc.strokeStyle=MP[mi].z+'.4)';mc.lineWidth=1;mc.stroke();bots.forEach(function(b){if(!b.alive)return;mc.fillStyle='#f85149';mc.fillRect(b.x*s-1,b.y*s-1,3,3)});ads.forEach(function(a){if(a.op)return;mc.fillStyle='#ffd700';mc.fillRect(a.x*s-2,a.y*s-2,4,4)});mc.fillStyle='#58d666';mc.beginPath();mc.arc(P.x*s,P.y*s,3,0,6.28);mc.fill()}
function uH(){var a2=bots.filter(function(b){return b.alive}).length+1;document.getElementById('alive').textContent=a2;document.getElementById('hpL').textContent='HP '+Math.max(0,~~P.hp);var hp=Math.max(0,P.hp);document.getElementById('hpF').style.width=hp+'%';document.getElementById('hpF').style.background=hp>60?'linear-gradient(90deg,#2ea043,#58d666)':hp>30?'linear-gradient(90deg,#f0ad4e,#ffc107)':'linear-gradient(90deg,#dc3545,#f85149)';var lv=Math.min(~~(xp/100),LV.length-1);document.getElementById('lvL').textContent=LV[lv]+' Lv.'+(lv+1);document.getElementById('xpF').style.width=(xp%100)+'%';document.getElementById('xpT').textContent='EXP '+xp+'/'+(~~(xp/100)+1)*100}
function uBag(){var h='<div class="bag-s">🔫</div>';if(P.bd)h+='<div class="bag-s">🩹'+P.bd+'</div>';if(P.co)h+='<div class="bag-s">🥤'+P.co+'</div>';if(P.md)h+='<div class="bag-s">💊'+P.md+'</div>';if(P.sh)h+='<div class="bag-s">🛡'+P.sh+'</div>';if(P.at)h+='<div class="bag-s">⚡'+P.at+'</div>';if(P.hi)h+='<div class="bag-s">📖'+P.hi+'</div>';if(P.rn)h+='<div class="bag-s">🎯</div>';document.getElementById('bag').innerHTML=h}
function aKF(m){var d=document.createElement('div');d.textContent='☠ '+m;document.getElementById('kf').appendChild(d);setTimeout(function(){d.remove()},3500)}
function sC(n){var d=document.createElement('div');d.className='combo';d.style.color=n>=5?'#ffd700':'#58d666';d.textContent=n+'连杀！';document.body.appendChild(d);setTimeout(function(){d.remove()},900)}
function eG(won){go=true;var a2=bots.filter(function(b){return b.alive}).length,rank=won?1:a2+2;document.getElementById('rIco').textContent=won?'🍗':'💀';document.getElementById('rRk').textContent='#'+rank;document.getElementById('rTt').textContent=won?'大吉大利，今晚吃鸡！':'你被淘汰了';document.getElementById('rTt').style.color=won?'#58d666':'#f85149';var acc=aL.length?((aL.length-wr.length)/aL.length*100).toFixed(0):0;
document.getElementById('rSts').innerHTML='<div class="st"><b>'+kl+'</b><small>击杀</small></div><div class="st"><b>#'+rank+'</b><small>排名</small></div><div class="st"><b>'+xp+'</b><small>EXP</small></div><div class="st"><b>'+mxC+'</b><small>最高连杀</small></div><div class="st"><b>'+aL.length+'</b><small>答题</small></div><div class="st"><b>'+acc+'%</b><small>正确率</small></div>';
var eh='';wr.forEach(function(w,i){eh+='<div class="ei"><b>#'+(i+1)+' '+w.q+'</b><br>你选: '+(w.picked>=0?String.fromCharCode(65+w.picked)+'. '+w.opts[w.picked]:'未答')+'<div class="ans">✅'+String.fromCharCode(65+w.correct)+'. '+w.opts[w.correct]+'</div></div>'});document.getElementById('rErrs').innerHTML=eh||'<div style="color:#2ea043;text-align:center">🎉全部答对！</div>';document.getElementById('resultS').classList.add('on')}
