/**
 * 201英语一 · 500道选择题题库
 * ========================================
 * 每局按真实卷面抽45题: 20完形填空 + 20阅读理解 + 5新题型
 * 
 * 分类标签 cat:
 *   cloze   = 完形填空(词汇/语法/逻辑)
 *   reading = 阅读理解(主旨/细节/推断/态度/词义)
 *   new     = 新题型(七选五/排序/小标题)
 */
const ENGLISH_QUESTIONS = [
  // ═══ 完形填空 (cloze) — 约220题 ═══
  // 词汇辨析
  {cat:'cloze', stem:'The word "ubiquitous" most nearly means:', opts:['A. rare','B. present everywhere','C. dangerous','D. beautiful'], ans:1, hint:'ubi=everywhere'},
  {cat:'cloze', stem:'"The findings are preliminary" implies the results are:', opts:['A. final','B. not yet confirmed','C. wrong','D. secret'], ans:1, hint:'preliminary=初步的'},
  {cat:'cloze', stem:'The antonym of "benevolent" is:', opts:['A. kind','B. generous','C. malevolent','D. wise'], ans:2, hint:'bene=good, male=bad'},
  {cat:'cloze', stem:'"She acquiesced to the decision" means she:', opts:['A. rejected it','B. accepted it reluctantly','C. celebrated it','D. ignored it'], ans:1, hint:'acquiesce=默许'},
  {cat:'cloze', stem:'The word "exacerbate" means to:', opts:['A. improve','B. make worse','C. examine','D. explain'], ans:1, hint:'ex+acerb=使更尖锐'},
  {cat:'cloze', stem:'Which word means "to make something less severe"?', opts:['A. aggravate','B. mitigate','C. perpetuate','D. exacerbate'], ans:1, hint:'mitigate=缓解'},
  {cat:'cloze', stem:'"Inevitable" means something that is:', opts:['A. avoidable','B. uncertain','C. unavoidable','D. unlikely'], ans:2, hint:'in+evitable=不可避免'},
  {cat:'cloze', stem:'"Pertinent" information is information that is:', opts:['A. irrelevant','B. outdated','C. relevant','D. secret'], ans:2, hint:'pertinent=相关的'},
  {cat:'cloze', stem:'The prefix "anti-" in "antithesis" means:', opts:['A. for','B. against/opposite','C. before','D. after'], ans:1, hint:'anti-=反，对立'},
  {cat:'cloze', stem:'"She was ambivalent about the proposal" means:', opts:['A. she strongly supported it','B. she had mixed feelings','C. she rejected it','D. she ignored it'], ans:1, hint:'ambi+valent=两面的'},
  {cat:'cloze', stem:'A "pragmatic" approach is one that is:', opts:['A. idealistic','B. impractical','C. practical','D. theoretical'], ans:2, hint:'pragmatic=务实的'},
  {cat:'cloze', stem:'"The study corroborates previous findings" means it:', opts:['A. contradicts them','B. supports them','C. ignores them','D. replaces them'], ans:1, hint:'corroborate=证实'},
  {cat:'cloze', stem:'What does "albeit" mean in context?', opts:['A. because','B. although','C. therefore','D. unless'], ans:1, hint:'albeit=虽然'},
  {cat:'cloze', stem:'"Empirical evidence" refers to evidence based on:', opts:['A. theory','B. observation and experiment','C. opinion','D. tradition'], ans:1, hint:'empirical=经验的/实证的'},
  {cat:'cloze', stem:'The word "plausible" means:', opts:['A. impossible','B. seemingly reasonable','C. certain','D. absurd'], ans:1, hint:'plausible=貌似合理的'},
  {cat:'cloze', stem:'"Robust" economic growth means growth that is:', opts:['A. weak','B. strong and healthy','C. slow','D. unpredictable'], ans:1, hint:'robust=强健的'},
  {cat:'cloze', stem:'The word "facilitate" means to:', opts:['A. hinder','B. make easier','C. complicate','D. prevent'], ans:1, hint:'facilitate=促进/使便利'},
  {cat:'cloze', stem:'"Tangible" benefits are benefits that are:', opts:['A. abstract','B. concrete and real','C. imaginary','D. temporary'], ans:1, hint:'tangible=有形的/切实的'},
  {cat:'cloze', stem:'The word "scrutinize" means to:', opts:['A. ignore','B. examine closely','C. accept blindly','D. destroy'], ans:1, hint:'scrutinize=仔细审查'},
  {cat:'cloze', stem:'"Profound" impact means an impact that is:', opts:['A. shallow','B. deep and significant','C. temporary','D. minor'], ans:1, hint:'profound=深刻的'},

  // 固定搭配
  {cat:'cloze', stem:'The government needs to _____ measures to address climate change.', opts:['A. make','B. take','C. do','D. give'], ans:1, hint:'take measures固定搭配'},
  {cat:'cloze', stem:'The research was carried _____ by a team of scientists.', opts:['A. on','B. out','C. up','D. away'], ans:1, hint:'carry out=执行'},
  {cat:'cloze', stem:'The new policy came _____ effect last month.', opts:['A. in','B. into','C. to','D. with'], ans:1, hint:'come into effect=生效'},
  {cat:'cloze', stem:'The results are _____ line with our expectations.', opts:['A. on','B. in','C. at','D. to'], ans:1, hint:'in line with=符合'},
  {cat:'cloze', stem:'She takes _____ her mother in appearance.', opts:['A. on','B. after','C. up','D. over'], ans:1, hint:'take after=像'},
  {cat:'cloze', stem:'The project was put _____ due to lack of funding.', opts:['A. forward','B. off','C. up','D. down'], ans:1, hint:'put off=推迟'},
  {cat:'cloze', stem:'We need to _____ up with a better plan.', opts:['A. put','B. come','C. take','D. give'], ans:1, hint:'come up with=想出'},
  {cat:'cloze', stem:'The company _____ for bankruptcy last year.', opts:['A. applied','B. filed','C. asked','D. demanded'], ans:1, hint:'file for bankruptcy固定搭配'},
  {cat:'cloze', stem:'Scientists are _____ the verge of a breakthrough.', opts:['A. at','B. on','C. in','D. by'], ans:1, hint:'on the verge of=在...边缘'},
  {cat:'cloze', stem:'The decision was made _____ behalf of the entire committee.', opts:['A. in','B. on','C. by','D. at'], ans:1, hint:'on behalf of=代表'},
  {cat:'cloze', stem:'The economy has been _____ decline for two years.', opts:['A. at','B. in','C. on','D. to'], ans:1, hint:'in decline=在衰退'},
  {cat:'cloze', stem:'He devotes himself _____ scientific research.', opts:['A. for','B. to','C. in','D. on'], ans:1, hint:'devote...to=献身于'},
  {cat:'cloze', stem:'The proposal met _____ strong opposition.', opts:['A. to','B. with','C. by','D. for'], ans:1, hint:'meet with=遭遇'},
  {cat:'cloze', stem:'This discovery shed light _____ the mechanism of the disease.', opts:['A. in','B. on','C. to','D. at'], ans:1, hint:'shed light on=阐明'},
  {cat:'cloze', stem:'The policy is _____ odds with public opinion.', opts:['A. in','B. at','C. on','D. to'], ans:1, hint:'at odds with=与...不一致'},

  // 语法填空
  {cat:'cloze', stem:'_____ it rained heavily, the match was cancelled.', opts:['A. Although','B. Because','C. Unless','D. While'], ans:1, hint:'因果关系，because表原因'},
  {cat:'cloze', stem:'Not until he arrived _____ the truth.', opts:['A. he knew','B. did he know','C. he did know','D. knew he'], ans:1, hint:'not until倒装'},
  {cat:'cloze', stem:'_____ the importance of education, more funds should be allocated.', opts:['A. Give','B. Given','C. Giving','D. To give'], ans:1, hint:'given=鉴于(介词)'},
  {cat:'cloze', stem:'The harder you work, _____ you will achieve.', opts:['A. much','B. the more','C. most','D. many'], ans:1, hint:'the+比较级...the+比较级'},
  {cat:'cloze', stem:'Had I known the answer, I _____ the question.', opts:['A. would answer','B. would have answered','C. will answer','D. had answered'], ans:1, hint:'虚拟语气：had+过去完成→would have done'},
  {cat:'cloze', stem:'The report, _____ was published last week, caused controversy.', opts:['A. that','B. which','C. what','D. it'], ans:1, hint:'非限制性定语从句用which'},
  {cat:'cloze', stem:'It is essential that every student _____ the exam.', opts:['A. takes','B. take','C. took','D. has taken'], ans:1, hint:'虚拟语气：essential+that+should+动词原形'},
  {cat:'cloze', stem:'_____ is well known, China has a long history.', opts:['A. It','B. As','C. What','D. Which'], ans:1, hint:'as引导非限制性定语从句(前置)'},
  {cat:'cloze', stem:'The man _____ I spoke is a professor.', opts:['A. who','B. to whom','C. which','D. whom'], ans:1, hint:'speak to sb → to whom'},
  {cat:'cloze', stem:'No sooner had he arrived _____ it began to rain.', opts:['A. when','B. than','C. before','D. that'], ans:1, hint:'no sooner...than固定搭配'},

  // 逻辑连接词
  {cat:'cloze', stem:'The price increased; _____, demand decreased.', opts:['A. moreover','B. consequently','C. however','D. meanwhile'], ans:1, hint:'因果关系，consequently=因此'},
  {cat:'cloze', stem:'The theory is interesting; _____, it lacks empirical support.', opts:['A. therefore','B. however','C. moreover','D. thus'], ans:1, hint:'转折关系'},
  {cat:'cloze', stem:'The project was delayed. _____, the budget was exceeded.', opts:['A. Nevertheless','B. Furthermore','C. Otherwise','D. Instead'], ans:1, hint:'递进关系，furthermore=此外'},
  {cat:'cloze', stem:'He studied hard for the exam; _____, he passed with flying colors.', opts:['A. nevertheless','B. as a result','C. otherwise','D. in contrast'], ans:1, hint:'结果关系'},
  {cat:'cloze', stem:'The economy is recovering; _____, unemployment remains high.', opts:['A. therefore','B. nonetheless','C. consequently','D. accordingly'], ans:1, hint:'让步/转折，nonetheless=尽管如此'},

  // 更多词汇
  {cat:'cloze', stem:'The word "infer" means to:', opts:['A. state explicitly','B. conclude from evidence','C. deny','D. repeat'], ans:1, hint:'infer=推断'},
  {cat:'cloze', stem:'"Cohesive" means:', opts:['A. separated','B. united and forming a whole','C. broken','D. random'], ans:1, hint:'cohesive=有凝聚力的'},
  {cat:'cloze', stem:'The word "elicit" means to:', opts:['A. hide','B. draw out a response','C. prevent','D. destroy'], ans:1, hint:'elicit=引出'},
  {cat:'cloze', stem:'"Prolific" writer means a writer who:', opts:['A. writes rarely','B. produces many works','C. writes poorly','D. is unknown'], ans:1, hint:'prolific=多产的'},
  {cat:'cloze', stem:'The word "viable" means:', opts:['A. impossible','B. capable of working successfully','C. dangerous','D. illegal'], ans:1, hint:'viable=可行的'},
  {cat:'cloze', stem:'"Salient" features are features that are:', opts:['A. hidden','B. most noticeable','C. unimportant','D. rare'], ans:1, hint:'salient=显著的'},
  {cat:'cloze', stem:'The word "inherent" means:', opts:['A. external','B. existing as a natural part','C. temporary','D. optional'], ans:1, hint:'inherent=固有的'},
  {cat:'cloze', stem:'"Commensurate" with means:', opts:['A. less than','B. proportionate to','C. greater than','D. unrelated to'], ans:1, hint:'commensurate=相称的'},
  {cat:'cloze', stem:'The word "pervasive" means:', opts:['A. limited','B. spreading widely throughout','C. rare','D. declining'], ans:1, hint:'pervasive=普遍的/弥漫的'},
  {cat:'cloze', stem:'"Unprecedented" means:', opts:['A. expected','B. never done or known before','C. repeated','D. common'], ans:1, hint:'un+precedent+ed=空前的'},
  {cat:'cloze', stem:'The word "resilient" means:', opts:['A. fragile','B. able to recover quickly','C. rigid','D. slow'], ans:1, hint:'resilient=有弹性的/能恢复的'},
  {cat:'cloze', stem:'"Detrimental" effects are effects that are:', opts:['A. beneficial','B. harmful','C. neutral','D. minor'], ans:1, hint:'detrimental=有害的'},
  {cat:'cloze', stem:'The word "paramount" means:', opts:['A. unimportant','B. of supreme importance','C. secondary','D. optional'], ans:1, hint:'paramount=至高无上的'},
  {cat:'cloze', stem:'"Advocate" can mean:', opts:['A. to oppose','B. to publicly support','C. to ignore','D. to punish'], ans:1, hint:'advocate=提倡/支持'},
  {cat:'cloze', stem:'The word "scrutiny" means:', opts:['A. praise','B. careful examination','C. neglect','D. approval'], ans:1, hint:'scrutiny=审查'},
  {cat:'cloze', stem:'"Pivotal" role means a role that is:', opts:['A. minor','B. of central importance','C. optional','D. temporary'], ans:1, hint:'pivotal=关键的'},
  {cat:'cloze', stem:'The word "mundane" means:', opts:['A. exciting','B. lacking interest; dull','C. mysterious','D. elegant'], ans:1, hint:'mundane=平凡的/乏味的'},
  {cat:'cloze', stem:'"Sparse" means:', opts:['A. dense','B. thinly scattered','C. heavy','D. concentrated'], ans:1, hint:'sparse=稀疏的'},
  {cat:'cloze', stem:'The word "impede" means to:', opts:['A. assist','B. delay or obstruct','C. accelerate','D. enable'], ans:1, hint:'impede=阻碍'},
  {cat:'cloze', stem:'"Alleviate" suffering means to:', opts:['A. increase it','B. make it less severe','C. ignore it','D. study it'], ans:1, hint:'alleviate=减轻'},
  {cat:'cloze', stem:'The word "eminent" means:', opts:['A. unknown','B. famous and respected','C. ordinary','D. young'], ans:1, hint:'eminent=杰出的'},
  {cat:'cloze', stem:'"Indigenous" people are people who are:', opts:['A. foreign','B. native to a place','C. immigrant','D. temporary'], ans:1, hint:'indigenous=本土的/原住的'},
  {cat:'cloze', stem:'The word "notorious" means:', opts:['A. famous for good','B. famous for something bad','C. unknown','D. admired'], ans:1, hint:'notorious=臭名昭著的'},
  {cat:'cloze', stem:'"Ambiguous" means:', opts:['A. clear','B. open to multiple interpretations','C. definite','D. simple'], ans:1, hint:'ambiguous=模棱两可的'},
  {cat:'cloze', stem:'The word "consensus" means:', opts:['A. disagreement','B. general agreement','C. conflict','D. debate'], ans:1, hint:'consensus=共识'},

  // ═══ 阅读理解 (reading) — 约220题 ═══
  // 主旨题
  {cat:'reading', stem:'Which of the following best describes the main idea of the passage?', opts:['A. The importance of fundamental research','B. The history of the Nobel Prize','C. Biographical details of scientists','D. Funding strategies for universities'], ans:0, hint:'主旨题找中心论点'},
  {cat:'reading', stem:'The passage is mainly about:', opts:['A. How artificial intelligence is transforming healthcare','B. The history of computer science','C. Programming languages comparison','D. Social media marketing'], ans:0, hint:'主旨=AI在医疗领域的转变'},
  {cat:'reading', stem:'What is the primary purpose of the passage?', opts:['A. To argue for stronger environmental regulations','B. To describe tourist destinations','C. To review a novel','D. To explain cooking techniques'], ans:0, hint:'目的题=作者写作意图'},
  {cat:'reading', stem:'The central theme of the passage is:', opts:['A. The growing gap between rich and poor','B. Fashion trends in 2025','C. Sports achievements','D. Celebrity gossip'], ans:0, hint:'中心主题'},
  {cat:'reading', stem:'The passage primarily discusses:', opts:['A. The ethical implications of gene editing','B. Gardening tips','C. Travel itineraries','D. Pet care'], ans:0, hint:'primarily=主要讨论'},

  // 细节题
  {cat:'reading', stem:'According to the passage, the main reason for the decline in bee populations is:', opts:['A. pesticide use','B. climate change alone','C. natural predators','D. urbanization'], ans:0, hint:'细节题找原文对应'},
  {cat:'reading', stem:'The author states that the study sample consisted of:', opts:['A. 500 randomly selected participants','B. only male subjects','C. college students exclusively','D. patients from one hospital'], ans:0, hint:'注意原文具体数字'},
  {cat:'reading', stem:'According to the passage, renewable energy sources currently account for what percentage of global electricity?', opts:['A. approximately 30%','B. over 50%','C. less than 10%','D. exactly 100%'], ans:0, hint:'细节数据题'},
  {cat:'reading', stem:'The passage mentions all of the following as benefits of remote work EXCEPT:', opts:['A. increased productivity','B. reduced commuting time','C. better work-life balance','D. stronger team bonding'], ans:3, hint:'EXCEPT题找不在文中的选项'},
  {cat:'reading', stem:'Which factor does the author identify as most critical to the success of the project?', opts:['A. Community engagement','B. Government funding','C. International support','D. Media coverage'], ans:0, hint:'找作者强调的关键因素'},

  // 推断题
  {cat:'reading', stem:'It can be inferred from the passage that:', opts:['A. Traditional education models need significant reform','B. All students prefer online learning','C. Technology will replace teachers','D. Schools should be abolished'], ans:0, hint:'推断题找合理推论'},
  {cat:'reading', stem:'The author implies that current regulations are:', opts:['A. insufficient to address new challenges','B. too strict','C. perfectly adequate','D. not enforced at all'], ans:0, hint:'imply=暗示'},
  {cat:'reading', stem:'Based on the passage, one can conclude that:', opts:['A. Interdisciplinary research will become more important','B. Specialization is the only path forward','C. Research funding will decrease','D. Universities will close'], ans:0, hint:'conclude=得出结论'},
  {cat:'reading', stem:'The passage suggests that the author would most likely agree with:', opts:['A. A balanced approach to economic development and environmental protection','B. Unlimited economic growth at any cost','C. Completely halting industrial development','D. Ignoring environmental concerns'], ans:0, hint:'推断作者立场'},
  {cat:'reading', stem:'From the passage, it can be inferred that the new technology:', opts:['A. Has both promising benefits and potential risks','B. Is completely safe','C. Should be banned','D. Has no practical application'], ans:0, hint:'推断题找平衡观点'},

  // 态度题 
  {cat:'reading', stem:'"The author\'s tone is sardonic" suggests the tone is:', opts:['A. sad','B. happy','C. mocking','D. neutral'], ans:2, hint:'sardonic=讽刺的'},
  {cat:'reading', stem:'The author\'s attitude toward the policy can be described as:', opts:['A. cautiously optimistic','B. overwhelmingly positive','C. indifferent','D. completely negative'], ans:0, hint:'态度题常选中立偏向选项'},
  {cat:'reading', stem:'The tone of the passage is best described as:', opts:['A. objective and analytical','B. emotional and biased','C. humorous','D. aggressive'], ans:0, hint:'学术文章通常客观分析'},
  {cat:'reading', stem:'How does the author feel about the current situation?', opts:['A. Concerned but hopeful','B. Completely satisfied','C. Apathetic','D. Furious'], ans:0, hint:'作者态度通常不极端'},
  {cat:'reading', stem:'The passage conveys a sense of:', opts:['A. urgency about addressing the problem','B. complacency','C. indifference','D. celebration'], ans:0, hint:'学术文章常有紧迫感'},

  // 词义题
  {cat:'reading', stem:'The word "comprising" in the passage most likely means:', opts:['A. excluding','B. consisting of','C. limiting','D. opposing'], ans:1, hint:'comprising=包含/由...组成'},
  {cat:'reading', stem:'The phrase "a raft of" in paragraph 3 means:', opts:['A. a boat full of','B. a large number of','C. a lack of','D. a raft on'], ans:1, hint:'a raft of=大量的'},
  {cat:'reading', stem:'In the context of the passage, "yield" most likely means:', opts:['A. to stop','B. to produce or generate','C. to surrender','D. to plant'], ans:1, hint:'yield在科学语境=产出'},
  {cat:'reading', stem:'The underlined word "adverse" is closest in meaning to:', opts:['A. beneficial','B. unfavorable','C. neutral','D. accidental'], ans:1, hint:'adverse=不利的'},
  {cat:'reading', stem:'The expression "in the wake of" means:', opts:['A. before','B. following or after','C. instead of','D. regardless of'], ans:1, hint:'in the wake of=在...之后'},
  {cat:'reading', stem:'The phrase "runs counter to" means:', opts:['A. supports','B. contradicts','C. follows','D. accompanies'], ans:1, hint:'run counter to=与...相悖'},
  {cat:'reading', stem:'The word "nuanced" as used in the passage means:', opts:['A. simple','B. having subtle differences','C. obvious','D. irrelevant'], ans:1, hint:'nuanced=细致入微的'},
  {cat:'reading', stem:'"Burgeoning" industries are industries that are:', opts:['A. declining','B. growing rapidly','C. stable','D. disappearing'], ans:1, hint:'burgeoning=蓬勃发展的'},

  // 更多阅读理解题
  {cat:'reading', stem:'Which of the following would the author most likely support?', opts:['A. Increasing investment in public education','B. Eliminating all public schools','C. Reducing teacher salaries','D. Abolishing homework'], ans:0, hint:'推断作者支持的观点'},
  {cat:'reading', stem:'The passage indicates that the main challenge facing developing countries is:', opts:['A. balancing growth with sustainability','B. lack of natural resources','C. too much foreign investment','D. excessive population decline'], ans:0, hint:'发展中国家面临的挑战'},
  {cat:'reading', stem:'According to the passage, innovation is most likely to occur when:', opts:['A. diverse perspectives are combined','B. individuals work alone','C. tradition is strictly followed','D. competition is eliminated'], ans:0, hint:'创新=多元视角'},
  {cat:'reading', stem:'The author uses the example of Finland to illustrate:', opts:['A. how education reform can succeed','B. the failure of social policies','C. the benefits of large class sizes','D. why standardized testing is essential'], ans:0, hint:'举例论证的目的'},
  {cat:'reading', stem:'The phrase "tipping point" in the passage refers to:', opts:['A. the critical moment when change becomes irreversible','B. the highest point of a mountain','C. a point of financial collapse','D. a type of reward system'], ans:0, hint:'tipping point=临界点'},
  {cat:'reading', stem:'The passage implies that traditional media:', opts:['A. is struggling to adapt to the digital age','B. has completely disappeared','C. is more popular than ever','D. is not affected by technology'], ans:0, hint:'传统媒体适应数字化的困境'},
  {cat:'reading', stem:'Which sentence best summarizes the author\'s conclusion?', opts:['A. A multi-faceted approach is needed to solve complex problems','B. Simple solutions are always best','C. Technology alone can solve everything','D. The problem cannot be solved'], ans:0, hint:'结论通常是综合性的'},
  {cat:'reading', stem:'The author would most likely describe the government\'s response as:', opts:['A. inadequate but well-intentioned','B. perfectly effective','C. completely misguided','D. unnecessary'], ans:0, hint:'作者评价通常辨证'},
  {cat:'reading', stem:'What does the passage suggest about the relationship between wealth and happiness?', opts:['A. Beyond a certain point, more wealth does not increase happiness','B. More money always means more happiness','C. Poor people are happier','D. Wealth has no effect on happiness'], ans:0, hint:'经典心理学结论'},
  {cat:'reading', stem:'The phrase "elephant in the room" most likely refers to:', opts:['A. an obvious problem that no one wants to discuss','B. a large animal','C. an unexpected guest','D. a popular topic'], ans:0, hint:'elephant in the room=显而易见却被回避的问题'},

  // 更多词汇与搭配题
  {cat:'reading', stem:'The author uses "paradox" to describe:', opts:['A. a seemingly contradictory situation that reveals a truth','B. a simple truth','C. an obvious fact','D. a mathematical formula'], ans:0, hint:'paradox=悖论'},
  {cat:'reading', stem:'The word "reckon" in British English often means:', opts:['A. to think or believe','B. to count money','C. to drive fast','D. to sleep'], ans:0, hint:'reckon=认为(英式口语)'},
  {cat:'reading', stem:'What is the function of the phrase "by the same token" in the passage?', opts:['A. To introduce a related point','B. To contradict the previous statement','C. To end the discussion','D. To change the topic'], ans:0, hint:'by the same token=同样地'},
  {cat:'reading', stem:'The word "catalyst" in the passage is used metaphorically to mean:', opts:['A. something that accelerates change','B. a chemical substance','C. a type of machine','D. a political leader'], ans:0, hint:'catalyst比喻=催化剂/推动力'},
  {cat:'reading', stem:'"Status quo" in the passage refers to:', opts:['A. the existing state of affairs','B. a new innovation','C. a historical event','D. a future prediction'], ans:0, hint:'status quo=现状'},

  // ═══ 新题型 (new) — 约60题 ═══
  {cat:'new', stem:'Which sentence best fits the blank in the passage to maintain logical coherence?', opts:['A. However, this approach has its limitations.','B. Therefore, the problem was solved immediately.','C. In addition, the weather was nice.','D. Meanwhile, sports events continued.'], ans:0, hint:'七选五=逻辑衔接'},
  {cat:'new', stem:'The most appropriate heading for paragraph 2 would be:', opts:['A. The Causes of Income Inequality','B. Solutions Already Implemented','C. Historical Background','D. Future Predictions'], ans:0, hint:'小标题匹配段落主旨'},
  {cat:'new', stem:'Based on the logic of the passage, which sentence should come after the given paragraph?', opts:['A. Despite these challenges, progress has been made.','B. The experiment was abandoned.','C. No one cared about the results.','D. The weather changed dramatically.'], ans:0, hint:'排序题=逻辑承接'},
  {cat:'new', stem:'Which of the following would best complete the passage?', opts:['A. Further research is needed to validate these findings.','B. The topic is no longer relevant.','C. Everyone agreed with the conclusion.','D. The data was unreliable.'], ans:0, hint:'结尾补全=总结+展望'},
  {cat:'new', stem:'The sentence that should be removed because it does not fit the paragraph is:', opts:['A. The one about cooking recipes','B. The one about research methods','C. The one about statistical analysis','D. The one about theoretical framework'], ans:0, hint:'排除无关句子'},
  {cat:'new', stem:'Which heading best captures the essence of paragraph 4?', opts:['A. Implications for Policy Makers','B. A Brief Introduction','C. Unrelated Anecdotes','D. Personal Opinions'], ans:0, hint:'段落标题要概括核心内容'},
  {cat:'new', stem:'The transitional sentence between paragraphs 3 and 4 should express:', opts:['A. a shift from problem to solution','B. a continuation of the same topic','C. an unrelated anecdote','D. a contradiction'], ans:0, hint:'过渡句=承上启下'},
  {cat:'new', stem:'Which sentence provides the strongest support for the main argument?', opts:['A. Recent data from WHO confirms the trend.','B. Some people disagree.','C. The weather was sunny.','D. No studies have been conducted.'], ans:0, hint:'论据支持=数据/权威引用'},

  // 句型与语法选择题
  {cat:'cloze', stem:'_____ he realized his mistake, it was too late.', opts:['A. Until','B. By the time','C. Unless','D. While'], ans:1, hint:'by the time=到...的时候'},
  {cat:'cloze', stem:'The book, _____ I have read recently, is very inspiring.', opts:['A. that','B. which','C. what','D. where'], ans:1, hint:'非限制性定语从句用which'},
  {cat:'cloze', stem:'_____ for the scholarship, she would not have been able to attend university.', opts:['A. Were it not','B. Had it not been','C. If it was not','D. Should it not be'], ans:1, hint:'虚拟条件句倒装'},
  {cat:'cloze', stem:'The more you practice, _____ you become.', opts:['A. good','B. the better','C. best','D. well'], ans:1, hint:'the+比较级, the+比较级'},
  {cat:'cloze', stem:'It is high time we _____ action on climate change.', opts:['A. take','B. took','C. will take','D. are taking'], ans:1, hint:'it is high time+过去时'},
  {cat:'cloze', stem:'Were I in your position, I _____ the offer.', opts:['A. will accept','B. would accept','C. accept','D. accepted'], ans:1, hint:'虚拟语气were...would'},
  {cat:'cloze', stem:'_____ difficult the task may be, we must try.', opts:['A. However','B. Whatever','C. Whenever','D. Wherever'], ans:0, hint:'however+adj=无论多么'},
  {cat:'cloze', stem:'The project succeeded, not because of luck, _____ because of hard work.', opts:['A. and','B. but','C. or','D. so'], ans:1, hint:'not...but=不是...而是'},
  {cat:'cloze', stem:'_____ to the left, you will see the museum.', opts:['A. Turn','B. Turning','C. Turned','D. Having turned'], ans:1, hint:'现在分词表伴随'},
  {cat:'cloze', stem:'He speaks English as if he _____ a native speaker.', opts:['A. is','B. were','C. has been','D. will be'], ans:1, hint:'as if+虚拟语气用were'},

  // 更多搭配与词汇
  {cat:'cloze', stem:'The word "juxtapose" means to:', opts:['A. separate','B. place side by side for comparison','C. hide','D. destroy'], ans:1, hint:'juxtapose=并列对比'},
  {cat:'cloze', stem:'"Anecdotal" evidence is based on:', opts:['A. personal accounts rather than systematic research','B. statistical analysis','C. laboratory experiments','D. mathematical models'], ans:0, hint:'anecdotal=轶事的/非系统性的'},
  {cat:'cloze', stem:'The word "dichotomy" refers to:', opts:['A. a division into two contradictory groups','B. unity','C. similarity','D. gradual change'], ans:0, hint:'dichotomy=二分法'},
  {cat:'cloze', stem:'"Conundrum" means:', opts:['A. a simple question','B. a confusing and difficult problem','C. a celebration','D. an answer'], ans:1, hint:'conundrum=难题'},
  {cat:'cloze', stem:'The word "ephemeral" means:', opts:['A. permanent','B. lasting for a very short time','C. ancient','D. important'], ans:1, hint:'ephemeral=短暂的'},
  {cat:'cloze', stem:'"Discrepancy" between two sets of data means:', opts:['A. agreement','B. a difference or inconsistency','C. similarity','D. correlation'], ans:1, hint:'discrepancy=差异'},
  {cat:'cloze', stem:'The word "preclude" means to:', opts:['A. include','B. prevent from happening','C. allow','D. postpone'], ans:1, hint:'preclude=阻止/排除'},
  {cat:'cloze', stem:'"Stipulate" means to:', opts:['A. suggest vaguely','B. specify as a condition','C. deny','D. ignore'], ans:1, hint:'stipulate=规定/要求'},
  {cat:'cloze', stem:'The word "remuneration" means:', opts:['A. punishment','B. payment for work','C. education','D. retirement'], ans:1, hint:'remuneration=报酬'},
  {cat:'cloze', stem:'"Auspicious" means:', opts:['A. unfavorable','B. indicating a good outcome','C. dangerous','D. ordinary'], ans:1, hint:'auspicious=吉利的'},

  // 更多阅读
  {cat:'reading', stem:'The passage uses the term "double-edged sword" to describe technology because:', opts:['A. it has both advantages and disadvantages','B. it is sharp','C. it is used in warfare','D. it is expensive'], ans:0, hint:'double-edged sword=双刃剑'},
  {cat:'reading', stem:'The data presented in the passage primarily serves to:', opts:['A. support the author\'s argument','B. confuse the reader','C. entertain','D. provide historical context'], ans:0, hint:'数据=支撑论点'},
  {cat:'reading', stem:'Which rhetorical device does the author use in the opening paragraph?', opts:['A. A provocative question','B. A personal anecdote','C. Statistical data','D. A quotation from a famous person'], ans:0, hint:'修辞策略=引发思考的问题'},
  {cat:'reading', stem:'The author\'s reference to "the tragedy of the commons" is used to:', opts:['A. illustrate the conflict between individual and collective interests','B. describe a theatrical performance','C. discuss ancient Greek drama','D. analyze population growth'], ans:0, hint:'公地悲剧=个体与集体利益冲突'},
  {cat:'reading', stem:'The structure of the passage can best be described as:', opts:['A. problem-solution','B. chronological narrative','C. comparison-contrast','D. cause and effect'], ans:0, hint:'篇章结构=提出问题→解决方案'},

  // 新题型补充
  {cat:'new', stem:'The gap in paragraph 3 is best filled with a sentence that:', opts:['A. provides a specific example','B. introduces a new topic','C. contradicts the main idea','D. repeats previous information'], ans:0, hint:'填空通常需要例证'},
  {cat:'new', stem:'The correct order of the paragraphs should be:', opts:['A. Introduction → Problem → Evidence → Solution → Conclusion','B. Conclusion → Problem → Solution → Introduction','C. Random order','D. Evidence → Introduction → Conclusion'], ans:0, hint:'学术文章的标准逻辑顺序'},
  {cat:'new', stem:'Which of the following sentences would best serve as a topic sentence for the paragraph?', opts:['A. Several factors contribute to the phenomenon.','B. The weather was pleasant last week.','C. John went to the store.','D. Music is enjoyable.'], ans:0, hint:'主题句=概括段落内容'},
  {cat:'new', stem:'The sentence "Moreover, the data reveals a troubling trend" functions as:', opts:['A. a transition adding supporting evidence','B. a conclusion','C. an introduction','D. a counterargument'], ans:0, hint:'moreover=递进，data=证据'},

  // 补充更多到接近500
  {cat:'cloze', stem:'The word "cacophony" means:', opts:['A. harmony','B. a harsh mixture of sounds','C. silence','D. melody'], ans:1, hint:'cacophony(caco=bad+phon=sound)'},
  {cat:'cloze', stem:'"Surreptitious" behavior is behavior that is:', opts:['A. open','B. kept secret because disapproved of','C. loud','D. legal'], ans:1, hint:'surreptitious=偷偷摸摸的'},
  {cat:'cloze', stem:'The word "ostensible" means:', opts:['A. real','B. appearing to be true but not necessarily so','C. hidden','D. impossible'], ans:1, hint:'ostensible=表面上的'},
  {cat:'cloze', stem:'"Magnanimous" means:', opts:['A. petty','B. very generous or forgiving','C. angry','D. weak'], ans:1, hint:'magn=great+anim=spirit'},
  {cat:'cloze', stem:'The word "verbose" means:', opts:['A. concise','B. using more words than needed','C. silent','D. poetic'], ans:1, hint:'verbose=冗长的'},
  {cat:'cloze', stem:'"Equivocal" statements are statements that are:', opts:['A. clear','B. ambiguous or unclear','C. false','D. proven'], ans:1, hint:'equi=equal+voc=voice→两种声音→模棱两可'},
  {cat:'cloze', stem:'The word "efficacy" means:', opts:['A. failure','B. the ability to produce a desired result','C. danger','D. cost'], ans:1, hint:'efficacy=功效'},
  {cat:'cloze', stem:'"Truncate" means to:', opts:['A. expand','B. shorten by cutting off','C. lengthen','D. duplicate'], ans:1, hint:'truncate=截断'},
  {cat:'cloze', stem:'The word "panacea" means:', opts:['A. a disease','B. a solution for all problems','C. a type of food','D. a country'], ans:1, hint:'panacea=万灵药'},
  {cat:'cloze', stem:'"Gregarious" person is someone who:', opts:['A. is shy','B. enjoys being with others','C. is mean','D. is lazy'], ans:1, hint:'gregarious=合群的'},

  {cat:'reading', stem:'The author uses the phrase "tip of the iceberg" to suggest that:', opts:['A. the visible problem is much smaller than the actual one','B. the problem is frozen','C. the solution is cold','D. the issue involves water'], ans:0, hint:'tip of the iceberg=冰山一角'},
  {cat:'reading', stem:'The contrast between paragraphs 2 and 3 serves to:', opts:['A. highlight different perspectives on the same issue','B. repeat the same information','C. confuse the reader','D. introduce humor'], ans:0, hint:'对比目的=展示不同角度'},
  {cat:'reading', stem:'Why does the author quote Dr. Smith in paragraph 4?', opts:['A. To provide expert support for the argument','B. To show disagreement','C. To change the topic','D. To fill space'], ans:0, hint:'引用专家=增加权威性'},
  {cat:'reading', stem:'The passage would most likely appear in:', opts:['A. an academic journal','B. a children\'s storybook','C. a recipe book','D. a sports magazine'], ans:0, hint:'根据文体判断出处'},
  {cat:'reading', stem:'Which of the following best describes the organization of the passage?', opts:['A. General to specific','B. Specific to general','C. Random','D. Alphabetical'], ans:0, hint:'文章组织通常从一般到具体'},

  {cat:'new', stem:'Which sentence acts as a bridge between the two contrasting ideas?', opts:['A. Nonetheless, there are some benefits.','B. The facts are clear.','C. Nobody disagrees.','D. The topic is boring.'], ans:0, hint:'nonetheless=桥接转折'},
  {cat:'new', stem:'The missing sentence in the gap should logically:', opts:['A. explain the cause mentioned in the previous sentence','B. introduce a completely new topic','C. repeat the first paragraph','D. provide a personal opinion without evidence'], ans:0, hint:'逻辑衔接=承接上文因果'},
  {cat:'new', stem:'Which heading best summarizes paragraph 5?', opts:['A. Future Directions and Recommendations','B. A Recipe for Success','C. Random Thoughts','D. Unrelated Data'], ans:0, hint:'最后段通常=建议/展望'},
  {cat:'new', stem:'The concluding sentence of the passage should:', opts:['A. summarize the key findings and look ahead','B. introduce a new problem','C. ask an unrelated question','D. repeat the title'], ans:0, hint:'结尾=总结+前瞻'},

  // ═══ 第三批 · 完形填空词汇 ═══
  {cat:'cloze', stem:'The word "aberration" means:', opts:['A. a normal event','B. a departure from what is normal','C. an improvement','D. a celebration'], ans:1, hint:'aberration=偏差/反常'},
  {cat:'cloze', stem:'"Ameliorate" means to:', opts:['A. worsen','B. make something better','C. destroy','D. ignore'], ans:1, hint:'ameliorate=改善'},
  {cat:'cloze', stem:'The word "anomaly" means:', opts:['A. something normal','B. something that deviates from the standard','C. a rule','D. a law'], ans:1, hint:'anomaly=异常'},
  {cat:'cloze', stem:'"Assiduous" means:', opts:['A. lazy','B. showing great care and perseverance','C. careless','D. quick'], ans:1, hint:'assiduous=勤勉的'},
  {cat:'cloze', stem:'The word "austere" means:', opts:['A. luxurious','B. severe or strict in manner','C. happy','D. colorful'], ans:1, hint:'austere=严肃的/朴素的'},
  {cat:'cloze', stem:'"Belligerent" means:', opts:['A. peaceful','B. hostile and aggressive','C. friendly','D. calm'], ans:1, hint:'belligerent=好战的'},
  {cat:'cloze', stem:'The word "candid" means:', opts:['A. dishonest','B. truthful and straightforward','C. secretive','D. vague'], ans:1, hint:'candid=坦率的'},
  {cat:'cloze', stem:'"Circumvent" means to:', opts:['A. follow directly','B. find a way around an obstacle','C. create','D. strengthen'], ans:1, hint:'circum=around+vent=go'},
  {cat:'cloze', stem:'The word "copious" means:', opts:['A. scarce','B. abundant in supply','C. expensive','D. rare'], ans:1, hint:'copious=大量的'},
  {cat:'cloze', stem:'"Debilitate" means to:', opts:['A. strengthen','B. make someone weak','C. encourage','D. heal'], ans:1, hint:'debilitate=使虚弱'},
  {cat:'cloze', stem:'The word "disparate" means:', opts:['A. similar','B. essentially different in kind','C. equal','D. connected'], ans:1, hint:'disparate=截然不同的'},
  {cat:'cloze', stem:'"Dogmatic" means:', opts:['A. flexible','B. inclined to impose one\'s views','C. uncertain','D. open-minded'], ans:1, hint:'dogmatic=教条的'},
  {cat:'cloze', stem:'The word "eclectic" means:', opts:['A. narrow in scope','B. deriving ideas from various sources','C. traditional','D. simple'], ans:1, hint:'eclectic=兼收并蓄的'},
  {cat:'cloze', stem:'"Fortuitous" means:', opts:['A. planned','B. happening by chance','C. unfortunate','D. expected'], ans:1, hint:'fortuitous=偶然的'},
  {cat:'cloze', stem:'The word "gratuitous" means:', opts:['A. necessary','B. uncalled for; unnecessary','C. grateful','D. expensive'], ans:1, hint:'gratuitous=无端的'},
  {cat:'cloze', stem:'"Idiosyncratic" means:', opts:['A. ordinary','B. peculiar to the individual','C. common','D. universal'], ans:1, hint:'idiosyncratic=独特的'},
  {cat:'cloze', stem:'The word "impervious" means:', opts:['A. vulnerable','B. not allowing passage through','C. open','D. easy to penetrate'], ans:1, hint:'impervious=不可渗透的'},
  {cat:'cloze', stem:'"Innocuous" means:', opts:['A. harmful','B. not harmful or offensive','C. poisonous','D. dangerous'], ans:1, hint:'innocuous=无害的'},
  {cat:'cloze', stem:'The word "laconic" means:', opts:['A. verbose','B. using few words','C. emotional','D. detailed'], ans:1, hint:'laconic=简洁的'},
  {cat:'cloze', stem:'"Malleable" means:', opts:['A. rigid','B. easily influenced or shaped','C. hard','D. unchangeable'], ans:1, hint:'malleable=可塑的'},
  {cat:'cloze', stem:'The word "nefarious" means:', opts:['A. good','B. extremely wicked','C. ordinary','D. kind'], ans:1, hint:'nefarious=邪恶的'},
  {cat:'cloze', stem:'"Obfuscate" means to:', opts:['A. clarify','B. make unclear or confusing','C. simplify','D. reveal'], ans:1, hint:'obfuscate=混淆'},
  {cat:'cloze', stem:'The word "pernicious" means:', opts:['A. beneficial','B. having a harmful effect','C. mild','D. temporary'], ans:1, hint:'pernicious=有害的'},
  {cat:'cloze', stem:'"Quintessential" means:', opts:['A. unusual','B. representing the most perfect example','C. minor','D. approximate'], ans:1, hint:'quintessential=典型的'},
  {cat:'cloze', stem:'The word "repudiate" means to:', opts:['A. accept','B. reject or refuse to accept','C. embrace','D. confirm'], ans:1, hint:'repudiate=否认/拒绝'},
  {cat:'cloze', stem:'"Sanguine" means:', opts:['A. pessimistic','B. optimistic in difficult situations','C. angry','D. sad'], ans:1, hint:'sanguine=乐观的'},
  {cat:'cloze', stem:'The word "tenacious" means:', opts:['A. giving up easily','B. persistent and determined','C. weak','D. indifferent'], ans:1, hint:'tenacious=顽强的'},
  {cat:'cloze', stem:'"Vindicate" means to:', opts:['A. accuse','B. clear of blame','C. punish','D. condemn'], ans:1, hint:'vindicate=证明无辜'},
  {cat:'cloze', stem:'The phrase "by and large" means:', opts:['A. specifically','B. on the whole','C. never','D. exactly'], ans:1, hint:'by and large=总的来说'},
  {cat:'cloze', stem:'"In lieu of" means:', opts:['A. in addition to','B. instead of','C. because of','D. apart from'], ans:1, hint:'in lieu of=代替'},

  // ═══ 完形填空 · 搭配与语法 ═══
  {cat:'cloze', stem:'He is accustomed _____ working long hours.', opts:['A. for','B. to','C. in','D. at'], ans:1, hint:'accustomed to=习惯于'},
  {cat:'cloze', stem:'The report is consistent _____ previous findings.', opts:['A. to','B. with','C. in','D. for'], ans:1, hint:'consistent with=与...一致'},
  {cat:'cloze', stem:'The proposal is subject _____ approval by the board.', opts:['A. of','B. to','C. for','D. with'], ans:1, hint:'subject to=以...为条件'},
  {cat:'cloze', stem:'Her success is attributed _____ hard work.', opts:['A. for','B. to','C. with','D. by'], ans:1, hint:'attribute...to=归因于'},
  {cat:'cloze', stem:'The children are exposed _____ various cultures.', opts:['A. for','B. to','C. with','D. in'], ans:1, hint:'exposed to=暴露于'},
  {cat:'cloze', stem:'The company prides itself _____ customer service.', opts:['A. in','B. on','C. for','D. to'], ans:1, hint:'pride oneself on=以...自豪'},
  {cat:'cloze', stem:'She refrained _____ commenting on the matter.', opts:['A. to','B. from','C. for','D. in'], ans:1, hint:'refrain from=克制住不做'},
  {cat:'cloze', stem:'The teacher _____ emphasis on critical thinking.', opts:['A. put','B. laid','C. made','D. set'], ans:1, hint:'lay emphasis on=强调'},
  {cat:'cloze', stem:'_____ raining, the concert went ahead as planned.', opts:['A. Although','B. Despite','C. Because','D. Therefore'], ans:1, hint:'despite+名词/动名词'},
  {cat:'cloze', stem:'Scarcely had he entered _____ the phone rang.', opts:['A. than','B. when','C. before','D. that'], ans:1, hint:'scarcely...when=一...就'},
  {cat:'cloze', stem:'Only by working together _____ achieve our goals.', opts:['A. we can','B. can we','C. we could','D. could we have'], ans:1, hint:'only+介词/副词→倒装'},
  {cat:'cloze', stem:'Little _____ know about the real situation.', opts:['A. he did','B. did he','C. he does','D. does he not'], ans:1, hint:'little否定词→倒装'},
  {cat:'cloze', stem:'She insisted that he _____ present at the meeting.', opts:['A. is','B. be','C. was','D. will be'], ans:1, hint:'insist虚拟→(should)+原形'},
  {cat:'cloze', stem:'_____ the circumstances, we had no choice.', opts:['A. Under','B. In','C. On','D. At'], ans:0, hint:'under the circumstances=在这种情况下'},
  {cat:'cloze', stem:'The policy gives rise _____ many concerns.', opts:['A. for','B. to','C. with','D. at'], ans:1, hint:'give rise to=引起'},
  {cat:'cloze', stem:'The project was brought _____ a successful conclusion.', opts:['A. for','B. to','C. in','D. at'], ans:1, hint:'bring to a conclusion=达成结论'},
  {cat:'cloze', stem:'I would rather you _____ tomorrow instead of today.', opts:['A. come','B. came','C. will come','D. coming'], ans:1, hint:'would rather+过去时=虚拟'},
  {cat:'cloze', stem:'No sooner _____ home than it started to rain.', opts:['A. I had arrived','B. had I arrived','C. I arrived','D. did I arrive'], ans:1, hint:'no sooner...than倒装'},
  {cat:'cloze', stem:'She speaks three languages, _____ she is only fifteen.', opts:['A. so','B. yet','C. for','D. nor'], ans:1, hint:'yet=然而(转折)'},
  {cat:'cloze', stem:'The museum, along with the park, _____ been renovated.', opts:['A. have','B. has','C. are','D. were'], ans:1, hint:'along with不影响主语单复数'},

  // ═══ 第四批 · 阅读理解 ═══
  {cat:'reading', stem:'The author\'s use of statistics in paragraph 2 serves to:', opts:['A. provide concrete evidence for the claim','B. confuse the reader','C. change the topic','D. criticize previous research'], ans:0, hint:'统计数据=论据'},
  {cat:'reading', stem:'The passage draws a comparison between _____ and _____ in order to:', opts:['A. highlight unexpected similarities','B. create confusion','C. provide entertainment','D. fill space'], ans:0, hint:'对比=揭示相似性/差异性'},
  {cat:'reading', stem:'Which of the following is NOT mentioned as a factor in the study?', opts:['A. Socioeconomic background','B. Genetic markers','C. Educational level','D. Personal hobbies'], ans:3, hint:'NOT题找未提及选项'},
  {cat:'reading', stem:'The phrase "gives short shrift to" means:', opts:['A. gives full attention to','B. treats dismissively','C. supports strongly','D. ignores completely'], ans:1, hint:'give short shrift to=忽视'},
  {cat:'reading', stem:'The author\'s main criticism of the study is:', opts:['A. the sample size was too small','B. the results were too positive','C. it was too expensive','D. it used too much technology'], ans:0, hint:'常见学术批评=样本不足'},
  {cat:'reading', stem:'The word "pivotal" in line 15 could be replaced by:', opts:['A. minor','B. crucial','C. optional','D. decorative'], ans:1, hint:'pivotal=crucial=关键的'},
  {cat:'reading', stem:'The author would most likely agree that:', opts:['A. a combination of approaches yields the best results','B. only one method should be used','C. research is unnecessary','D. tradition should never change'], ans:0, hint:'综合方法最有效'},
  {cat:'reading', stem:'The passage primarily serves to:', opts:['A. inform readers about recent developments in the field','B. advertise a product','C. tell a personal story','D. provide cooking instructions'], ans:0, hint:'学术文=inform'},
  {cat:'reading', stem:'The author\'s tone shifts from _____ to _____ between paragraphs 1 and 4:', opts:['A. descriptive to prescriptive','B. angry to calm','C. formal to informal','D. positive to more positive'], ans:0, hint:'从描述到建议'},
  {cat:'reading', stem:'The "glass ceiling" mentioned in the passage refers to:', opts:['A. an invisible barrier to advancement','B. a type of architecture','C. a scientific instrument','D. a company name'], ans:0, hint:'glass ceiling=玻璃天花板/隐性障碍'},
  {cat:'reading', stem:'According to the passage, the biggest obstacle to reform is:', opts:['A. resistance from entrenched interests','B. lack of technology','C. insufficient population','D. too much funding'], ans:0, hint:'既得利益的阻碍'},
  {cat:'reading', stem:'The passage mentions the "butterfly effect" to illustrate:', opts:['A. small changes can have large consequences','B. butterflies are beautiful','C. the weather is unpredictable','D. chaos theory is wrong'], ans:0, hint:'蝴蝶效应=小变化大影响'},
  {cat:'reading', stem:'What can be inferred about the author\'s background?', opts:['A. likely an academic or researcher','B. a professional athlete','C. a chef','D. a musician'], ans:0, hint:'从写作风格推断作者背景'},
  {cat:'reading', stem:'The passage suggests that the current system:', opts:['A. needs reform but not complete replacement','B. should be completely abolished','C. is perfect as it is','D. has nothing to do with the topic'], ans:0, hint:'需要改革但不是颠覆'},
  {cat:'reading', stem:'The idiom "barking up the wrong tree" in the passage means:', opts:['A. making a correct assumption','B. pursuing a mistaken course of action','C. literally barking at a tree','D. climbing too high'], ans:1, hint:'bark up the wrong tree=找错对象'},
  {cat:'reading', stem:'The expression "the lion\'s share" means:', opts:['A. a small portion','B. the largest part','C. an equal portion','D. nothing'], ans:1, hint:'lion\'s share=最大份额'},
  {cat:'reading', stem:'The phrase "with a pinch of salt" suggests one should:', opts:['A. add salt to food','B. be skeptical about a claim','C. be enthusiastic','D. cook carefully'], ans:1, hint:'with a pinch of salt=持保留态度'},
  {cat:'reading', stem:'According to the passage, what role does education play?', opts:['A. It serves as a great equalizer in society','B. It is unimportant','C. It creates inequality','D. It should be abolished'], ans:0, hint:'教育=社会公平化工具'},
  {cat:'reading', stem:'The author uses "red herring" to describe:', opts:['A. a type of fish','B. something misleading that diverts attention','C. a good argument','D. a historical event'], ans:1, hint:'red herring=转移注意力的东西'},
  {cat:'reading', stem:'The word "albeit" in the passage serves to:', opts:['A. introduce a contrast or qualification','B. add emphasis','C. provide a definition','D. change the topic'], ans:0, hint:'albeit=although(让步/限定)'},

  // ═══ 更多新题型 ═══
  {cat:'new', stem:'Which sentence should be inserted at the beginning of paragraph 2 to create a smooth transition?', opts:['A. On the other hand, critics argue differently.','B. The weather was nice that day.','C. He liked pizza.','D. Mathematics is important.'], ans:0, hint:'段落开头过渡=联系上文'},
  {cat:'new', stem:'The paragraph lacks a concluding sentence. Which would be most appropriate?', opts:['A. Therefore, addressing these issues requires coordinated effort.','B. The meeting was boring.','C. Nobody cares about this topic.','D. Let us talk about something else.'], ans:0, hint:'结尾句=总结+升华'},
  {cat:'new', stem:'Which of the given sentences is out of place in the paragraph?', opts:['A. The one discussing weather patterns in a paragraph about economics','B. The one with statistical data supporting the thesis','C. The one referencing expert opinions','D. The one offering policy recommendations'], ans:0, hint:'找与段落主题不符的句子'},
  {cat:'new', stem:'The correct sequence of the sentences is:', opts:['A. Topic sentence → Supporting details → Example → Conclusion','B. Conclusion → Example → Topic sentence → Details','C. Random order','D. Example → Conclusion → Topic → Details'], ans:0, hint:'标准段落结构'},
  {cat:'new', stem:'Which heading best matches a paragraph about the methodology of a study?', opts:['A. Research Design and Methods','B. Introduction','C. Conclusion','D. Acknowledgments'], ans:0, hint:'方法论段落标题'},
  {cat:'new', stem:'A sentence beginning with "In contrast" should be placed:', opts:['A. after a sentence presenting an opposing viewpoint or different data','B. at the very beginning of the passage','C. at the end as a conclusion','D. anywhere at random'], ans:0, hint:'in contrast=对比连接'},
  {cat:'new', stem:'The passage needs a sentence showing cause and effect. Which fits best?', opts:['A. As a result, productivity increased by 20%.','B. The sky is blue.','C. He went home early.','D. She likes coffee.'], ans:0, hint:'因果句=as a result'},
  {cat:'new', stem:'Which sentence would best introduce the concept of sustainability?', opts:['A. Sustainability involves meeting present needs without compromising future generations.','B. Everyone should buy a car.','C. The store was closed.','D. History repeats itself.'], ans:0, hint:'定义式引入概念'},
  {cat:'new', stem:'The gap requires a sentence that:', opts:['A. provides evidence for the claim in the previous sentence','B. changes the subject entirely','C. asks an unrelated question','D. makes a joke'], ans:0, hint:'填空=补充论据'},
  {cat:'new', stem:'Which would serve as the best hook (opening sentence) for an essay on climate change?', opts:['A. As global temperatures rise at an alarming rate, the world faces unprecedented challenges.','B. I had breakfast this morning.','C. Sports are fun.','D. The document was printed.'], ans:0, hint:'开头hook=引起关注'},
  {cat:'new', stem:'The sentence "Nevertheless, some scholars disagree" serves to:', opts:['A. introduce a counterargument','B. end the discussion','C. support the main point','D. provide a definition'], ans:0, hint:'nevertheless=引入反面观点'},
  {cat:'new', stem:'In a seven-paragraph essay, a sentence about "policy implications" most likely belongs in:', opts:['A. the final or penultimate paragraph','B. the introduction','C. paragraph 2','D. the abstract'], ans:0, hint:'政策建议通常在结尾部分'},

  // ═══ 第五批 · 词汇与阅读混合 ═══
  {cat:'cloze', stem:'The word "antecedent" means:', opts:['A. something that followed','B. something that came before','C. a consequence','D. a synonym'], ans:1, hint:'ante=before+ced=go'},
  {cat:'cloze', stem:'"Cognizant" means:', opts:['A. unaware','B. having knowledge or awareness','C. confused','D. forgetful'], ans:1, hint:'cognizant=认识到的'},
  {cat:'cloze', stem:'The word "delineate" means to:', opts:['A. erase','B. describe or portray precisely','C. confuse','D. remove'], ans:1, hint:'delineate=描绘/界定'},
  {cat:'cloze', stem:'"Engender" means to:', opts:['A. prevent','B. cause or give rise to','C. destroy','D. reduce'], ans:1, hint:'engender=引起/产生'},
  {cat:'cloze', stem:'The word "fallacious" means:', opts:['A. true','B. based on a mistaken belief','C. proven','D. logical'], ans:1, hint:'fallacious=谬误的'},
  {cat:'cloze', stem:'"Hegemony" means:', opts:['A. equality','B. leadership or dominance','C. weakness','D. democracy'], ans:1, hint:'hegemony=霸权'},
  {cat:'cloze', stem:'The word "incumbent" (as an adjective) means:', opts:['A. optional','B. necessary as a duty or responsibility','C. unlikely','D. former'], ans:1, hint:'incumbent upon=有义务的'},
  {cat:'cloze', stem:'"Juxtaposition" is the act of:', opts:['A. separating','B. placing close together for comparison','C. hiding','D. destroying'], ans:1, hint:'juxtaposition=并列/对比'},
  {cat:'cloze', stem:'The word "kudos" means:', opts:['A. criticism','B. praise and honor','C. punishment','D. money'], ans:1, hint:'kudos=荣誉/赞扬'},
  {cat:'cloze', stem:'"Lucrative" means:', opts:['A. unprofitable','B. producing much profit','C. dangerous','D. illegal'], ans:1, hint:'lucrative=有利可图的'},
  {cat:'cloze', stem:'The expression "par for the course" means:', opts:['A. above average','B. normal or expected','C. below standard','D. impossible'], ans:1, hint:'par for the course=意料之中'},
  {cat:'cloze', stem:'"Vis-a-vis" means:', opts:['A. goodbye','B. in relation to','C. above','D. below'], ans:1, hint:'vis-a-vis=关于/相对于'},
  {cat:'cloze', stem:'The expression "a foregone conclusion" means:', opts:['A. an uncertain outcome','B. a result that can be predicted with certainty','C. a surprising twist','D. an open question'], ans:1, hint:'foregone conclusion=预料中的结论'},
  {cat:'cloze', stem:'"Albeit" is closest in meaning to:', opts:['A. because','B. although','C. therefore','D. instead'], ans:1, hint:'albeit=although'},
  {cat:'cloze', stem:'The word "nebulous" means:', opts:['A. clear','B. vague or ill-defined','C. bright','D. solid'], ans:1, hint:'nebulous=模糊的'},
  {cat:'cloze', stem:'"Propensity" means:', opts:['A. aversion','B. an inclination or tendency','C. a skill','D. a weakness'], ans:1, hint:'propensity=倾向'},
  {cat:'cloze', stem:'The word "recalcitrant" means:', opts:['A. obedient','B. stubbornly disobedient','C. eager','D. helpful'], ans:1, hint:'recalcitrant=不服从的'},
  {cat:'cloze', stem:'"Watershed" moment means:', opts:['A. an insignificant event','B. a turning point','C. a flood','D. a dry period'], ans:1, hint:'watershed=分水岭/转折点'},
  {cat:'cloze', stem:'The word "zenith" means:', opts:['A. the lowest point','B. the highest point or peak','C. the middle','D. the beginning'], ans:1, hint:'zenith=顶点(反义nadir)'},

  {cat:'reading', stem:'The passage suggests that globalization has:', opts:['A. created both winners and losers','B. benefited everyone equally','C. harmed everyone','D. had no effect'], ans:0, hint:'全球化的双重影响'},
  {cat:'reading', stem:'The term "moral hazard" in the passage refers to:', opts:['A. the risk that a party will take risks because they do not bear the full costs','B. being morally good','C. physical danger','D. a type of insurance'], ans:0, hint:'moral hazard=道德风险'},
  {cat:'reading', stem:'The passage implies that the "digital divide" is:', opts:['A. a gap between those with and without access to technology','B. a mathematical concept','C. a type of software','D. a political party'], ans:0, hint:'digital divide=数字鸿沟'},
  {cat:'reading', stem:'The word "caveat" in the passage means:', opts:['A. a warning or proviso','B. a celebration','C. an approval','D. a compliment'], ans:0, hint:'caveat=警告/附加条件'},
  {cat:'reading', stem:'The phrase "paradigm shift" in paragraph 3 refers to:', opts:['A. a fundamental change in approach or underlying assumptions','B. a minor adjustment','C. a temporary trend','D. a computer program'], ans:0, hint:'paradigm shift=范式转变'},
  {cat:'reading', stem:'The author\'s reference to the "Dunning-Kruger effect" suggests:', opts:['A. people with limited knowledge tend to overestimate their abilities','B. smart people are always modest','C. education is unnecessary','D. testing is unreliable'], ans:0, hint:'Dunning-Kruger=认知偏差'},
  {cat:'reading', stem:'What is the purpose of the rhetorical question in the last paragraph?', opts:['A. To provoke thought and engagement from the reader','B. To provide a definitive answer','C. To end the discussion abruptly','D. To introduce a new topic'], ans:0, hint:'修辞问=引发思考'},
  {cat:'reading', stem:'The passage indicates that "soft skills" include:', opts:['A. communication, teamwork, and adaptability','B. programming and data analysis','C. physical strength','D. mathematical calculations'], ans:0, hint:'soft skills=软技能'},
  {cat:'reading', stem:'The word "ramifications" in the passage means:', opts:['A. simple outcomes','B. complex consequences or implications','C. branches of a tree','D. mathematical divisions'], ans:1, hint:'ramifications=影响/后果'},
  {cat:'reading', stem:'According to the passage, "stakeholders" refers to:', opts:['A. all parties who have an interest in or are affected by something','B. people who own stakes','C. gamblers','D. investors only'], ans:0, hint:'stakeholders=利益相关方'},

  // ═══ 更多新题型 ═══
  {cat:'new', stem:'A paragraph that begins with "To begin with" should be followed by:', opts:['A. a paragraph starting with "Furthermore" or "In addition"','B. a conclusion','C. an unrelated paragraph','D. the same paragraph repeated'], ans:0, hint:'列举论证的逻辑顺序'},
  {cat:'new', stem:'The function of "To sum up" at the beginning of the final paragraph is to:', opts:['A. signal the conclusion and summary of main points','B. introduce new information','C. ask a question','D. provide more examples'], ans:0, hint:'to sum up=总结信号'},
  {cat:'new', stem:'Which transitional phrase indicates a concession?', opts:['A. Admittedly','B. Therefore','C. Similarly','D. In fact'], ans:0, hint:'admittedly=诚然(让步)'},
  {cat:'new', stem:'A paragraph discussing "limitations of the study" typically appears:', opts:['A. near the end of a research paper','B. in the introduction','C. in the abstract only','D. in the references'], ans:0, hint:'局限性讨论在结尾'},
  {cat:'new', stem:'Which phrase signals an example is about to be given?', opts:['A. For instance','B. In conclusion','C. However','D. Therefore'], ans:0, hint:'for instance=例如'},
  {cat:'new', stem:'The phrase "It is worth noting that" serves to:', opts:['A. draw attention to an important but perhaps overlooked point','B. end the discussion','C. introduce a joke','D. provide a definition'], ans:0, hint:'值得注意=强调'},
  {cat:'new', stem:'A passage organized in "compare and contrast" pattern would use words like:', opts:['A. similarly, on the other hand, whereas, likewise','B. first, second, third','C. once upon a time','D. the end'], ans:0, hint:'对比结构的信号词'},
  {cat:'new', stem:'Which sentence pattern indicates the author is about to present evidence?', opts:['A. Research indicates that... / Studies have shown that...','B. I personally believe...','C. Everyone knows that...','D. It is obvious that...'], ans:0, hint:'证据引入=research shows'},

  // ═══ 第五批 · 完形填空词义辨析 ═══
  {cat:'cloze', stem:'The government has taken measures to ___ the spread of the virus.', opts:['A. contain','B. maintain','C. retain','D. obtain'], ans:0, hint:'contain=遏制'},
  {cat:'cloze', stem:'The company decided to ___ its operations overseas.', opts:['A. expand','B. expend','C. extend','D. extent'], ans:0, hint:'expand=扩展(业务)'},
  {cat:'cloze', stem:'The evidence ___ that the defendant was innocent.', opts:['A. suggested','B. suspected','C. subjected','D. sustained'], ans:0, hint:'suggest=表明'},
  {cat:'cloze', stem:'Many species are in danger of ___ due to habitat loss.', opts:['A. extinction','B. distinction','C. extension','D. extraction'], ans:0, hint:'extinction=灭绝'},
  {cat:'cloze', stem:'The new policy was ___ by a majority of the committee.', opts:['A. endorsed','B. enforced','C. engaged','D. enhanced'], ans:0, hint:'endorse=批准，支持'},
  {cat:'cloze', stem:'Scientists are trying to ___ the mysteries of the universe.', opts:['A. unravel','B. uncover','C. unfold','D. undo'], ans:0, hint:'unravel=解开（谜团）'},
  {cat:'cloze', stem:'The ___ of the experiment confirmed the hypothesis.', opts:['A. outcome','B. outlook','C. output','D. outset'], ans:0, hint:'outcome=结果'},
  {cat:'cloze', stem:'Her speech was so ___ that everyone was moved to tears.', opts:['A. eloquent','B. elegant','C. elaborate','D. elusive'], ans:0, hint:'eloquent=有说服力的'},
  {cat:'cloze', stem:'The doctor advised him to ___ from smoking.', opts:['A. abstain','B. restrain','C. constrain','D. detain'], ans:0, hint:'abstain from=戒除'},
  {cat:'cloze', stem:'The bridge was built to ___ the gap between the two communities.', opts:['A. bridge','B. breach','C. break','D. broaden'], ans:0, hint:'bridge the gap=弥合差距'},
  {cat:'cloze', stem:'The scandal ___ public confidence in the government.', opts:['A. undermined','B. underlined','C. understood','D. undertook'], ans:0, hint:'undermine=削弱'},
  {cat:'cloze', stem:'The researchers ___ their findings in a prestigious journal.', opts:['A. published','B. publicized','C. punished','D. purchased'], ans:0, hint:'publish=发表'},
  {cat:'cloze', stem:'The treaty was designed to ___ peace in the region.', opts:['A. promote','B. provoke','C. prohibit','D. proclaim'], ans:0, hint:'promote=促进'},
  {cat:'cloze', stem:'The government has ___ new regulations to protect consumers.', opts:['A. implemented','B. implicated','C. implied','D. imported'], ans:0, hint:'implement=实施'},
  {cat:'cloze', stem:'The author\'s argument was ___ by several logical fallacies.', opts:['A. weakened','B. strengthened','C. abandoned','D. reinforced'], ans:0, hint:'weaken=削弱(论点)'},
  {cat:'cloze', stem:'The company ___ a significant loss in the third quarter.', opts:['A. incurred','B. inspired','C. inquired','D. insisted'], ans:0, hint:'incur=招致(损失)'},
  {cat:'cloze', stem:'The museum ___ a vast collection of ancient artifacts.', opts:['A. houses','B. holds','C. hoards','D. harbors'], ans:0, hint:'house=收藏(作为动词)'},
  {cat:'cloze', stem:'Technology has ___ the way we communicate.', opts:['A. transformed','B. transferred','C. translated','D. transmitted'], ans:0, hint:'transform=改变'},
  {cat:'cloze', stem:'The lecture was so boring that several students ___ off.', opts:['A. dozed','B. dosed','C. doted','D. doubted'], ans:0, hint:'doze off=打瞌睡'},
  {cat:'cloze', stem:'She showed remarkable ___ in dealing with the crisis.', opts:['A. composure','B. exposure','C. disclosure','D. closure'], ans:0, hint:'composure=镇定'},
  {cat:'cloze', stem:'The company is seeking to ___ its market share.', opts:['A. consolidate','B. constitute','C. consult','D. consume'], ans:0, hint:'consolidate=巩固'},
  {cat:'cloze', stem:'The proposal was met with ___ resistance from the opposition.', opts:['A. fierce','B. mild','C. gentle','D. moderate'], ans:0, hint:'fierce resistance=激烈反对'},
  {cat:'cloze', stem:'The new law will ___ into effect next month.', opts:['A. come','B. bring','C. put','D. take'], ans:0, hint:'come into effect=生效'},
  {cat:'cloze', stem:'The report ___ that climate change is accelerating.', opts:['A. concluded','B. included','C. excluded','D. secluded'], ans:0, hint:'conclude=得出结论'},
  {cat:'cloze', stem:'The athlete was ___ from the competition for doping.', opts:['A. disqualified','B. discharged','C. discarded','D. discouraged'], ans:0, hint:'disqualify=取消资格'},

  // ═══ 第六批 · 阅读理解推理判断 ═══
  {cat:'reading', stem:'When the author says "the writing is on the wall", he means:', opts:['A. The outcome is obvious and inevitable','B. Someone wrote on a wall','C. There is graffiti on the wall','D. A message was left'], ans:0, hint:'习语：结局已经注定'},
  {cat:'reading', stem:'The phrase "a double-edged sword" in the passage implies:', opts:['A. Something with both advantages and disadvantages','B. A weapon with two sharp edges','C. A dangerous tool','D. Two swords'], ans:0, hint:'双刃剑=利弊兼具'},
  {cat:'reading', stem:'The author\'s tone in the passage can best be described as:', opts:['A. Objective and analytical','B. Highly emotional','C. Completely indifferent','D. Sarcastic'], ans:0, hint:'学术文章常为客观分析'},
  {cat:'reading', stem:'The word "paramount" in the passage is closest in meaning to:', opts:['A. Of supreme importance','B. Average','C. Minimal','D. Secondary'], ans:0, hint:'paramount=最重要的'},
  {cat:'reading', stem:'According to the passage, "to level the playing field" means:', opts:['A. To create equal conditions for all','B. To flatten a sports field','C. To lower standards','D. To build a new playground'], ans:0, hint:'创造公平竞争环境'},
  {cat:'reading', stem:'The word "ubiquitous" is closest in meaning to:', opts:['A. Found everywhere','B. Rare','C. Unique','D. Mysterious'], ans:0, hint:'ubiquitous=无处不在的'},
  {cat:'reading', stem:'The phrase "at the expense of" means:', opts:['A. At the cost of; sacrificing','B. With the money of','C. For the benefit of','D. Instead of'], ans:0, hint:'以...为代价'},
  {cat:'reading', stem:'When the text states something is "counterintuitive", it means:', opts:['A. Contrary to what common sense would suggest','B. Easy to understand','C. Following intuition','D. Very logical'], ans:0, hint:'counter+intuitive=反直觉'},
  {cat:'reading', stem:'"The author draws an analogy between X and Y" means the author:', opts:['A. Compares X and Y to highlight similarities','B. Contrasts X and Y','C. Defines X using Y','D. Replaces X with Y'], ans:0, hint:'analogy=类比'},
  {cat:'reading', stem:'The word "pragmatic" is closest in meaning to:', opts:['A. Practical and realistic','B. Idealistic','C. Theoretical','D. Emotional'], ans:0, hint:'pragmatic=务实的'},
  {cat:'reading', stem:'If a passage describes a "paradigm shift", it refers to:', opts:['A. A fundamental change in approach or assumptions','B. A minor adjustment','C. A temporary change','D. A return to old methods'], ans:0, hint:'范式转变=根本性变革'},
  {cat:'reading', stem:'The word "alleviate" in the passage means:', opts:['A. To reduce or make less severe','B. To worsen','C. To eliminate','D. To cause'], ans:0, hint:'alleviate=缓解'},
  {cat:'reading', stem:'"The findings corroborate previous research" means:', opts:['A. The findings support earlier studies','B. The findings contradict studies','C. The findings are new','D. The findings are irrelevant'], ans:0, hint:'corroborate=证实'},
  {cat:'reading', stem:'The word "exacerbate" means:', opts:['A. To make a problem worse','B. To solve a problem','C. To ignore a problem','D. To describe a problem'], ans:0, hint:'exacerbate=加剧'},
  {cat:'reading', stem:'When an author uses "moreover" in an argument, it signals:', opts:['A. An additional point supporting the argument','B. A contrasting point','C. A conclusion','D. A change of topic'], ans:0, hint:'moreover=此外（递进）'},
  {cat:'reading', stem:'"Notwithstanding" in legal/academic writing means:', opts:['A. Despite; in spite of','B. Because of','C. According to','D. Together with'], ans:0, hint:'notwithstanding=尽管'},
  {cat:'reading', stem:'The word "empirical" refers to something based on:', opts:['A. Observation and experiment','B. Theory alone','C. Personal opinion','D. Tradition'], ans:0, hint:'empirical=实证的'},
  {cat:'reading', stem:'A "caveat" in academic writing is:', opts:['A. A warning or qualification','B. A conclusion','C. A hypothesis','D. A citation'], ans:0, hint:'caveat=注意事项/限制条件'},
  {cat:'reading', stem:'The phrase "the jury is still out on" means:', opts:['A. A decision has not yet been reached','B. The jury has left the courtroom','C. The case is closed','D. Everyone agrees'], ans:0, hint:'尚无定论'},
  {cat:'reading', stem:'"To shed light on" a topic means to:', opts:['A. Clarify or explain something','B. Make something darker','C. Ignore the topic','D. Complicate the matter'], ans:0, hint:'shed light on=阐明'},

  // ═══ 第七批 · 新题型 ═══
  {cat:'newtype', stem:'In a 7-to-5 matching exercise, what is the key strategy?', opts:['A. Find unique keywords linking each heading to its paragraph','B. Guess randomly','C. Choose the first option always','D. Skip difficult ones'], ans:0, hint:'关键词匹配法'},
  {cat:'newtype', stem:'In a sentence ordering task, the first step is to:', opts:['A. Identify the topic sentence and concluding sentence','B. Read all sentences quickly','C. Choose randomly','D. Start from the last sentence'], ans:0, hint:'先定首尾句'},
  {cat:'newtype', stem:'Cohesive devices such as "however", "therefore", "moreover" help in:', opts:['A. Understanding the logical flow between sentences','B. Vocabulary building','C. Grammar correction','D. Speed reading'], ans:0, hint:'衔接词=逻辑关系'},
  {cat:'newtype', stem:'In a reading comprehension about academic research, "findings" refers to:', opts:['A. The results or discoveries of the study','B. The introduction','C. The references','D. The abstract'], ans:0, hint:'findings=研究发现'},
  {cat:'newtype', stem:'A transition word "nevertheless" indicates:', opts:['A. Contrast or concession','B. Addition','C. Cause','D. Time sequence'], ans:0, hint:'nevertheless=然而（转折）'},
  {cat:'newtype', stem:'In paragraph matching, the phrase "this approach" most likely refers to:', opts:['A. A method described in the preceding paragraph','B. A new topic','C. The final conclusion','D. An unrelated idea'], ans:0, hint:'指代前文方法'},
  {cat:'newtype', stem:'The phrase "as illustrated by" signals:', opts:['A. An example or evidence is about to follow','B. A contrast','C. A summary','D. A repetition'], ans:0, hint:'举例说明'},
  {cat:'newtype', stem:'In text sorting, a sentence starting with "In conclusion" should be placed:', opts:['A. At the end','B. At the beginning','C. In the middle','D. It doesn\'t matter'], ans:0, hint:'In conclusion=结尾句'},
  {cat:'newtype', stem:'The word "aforementioned" refers to something:', opts:['A. Previously discussed or stated','B. About to be discussed','C. Irrelevant','D. Confidential'], ans:0, hint:'aforementioned=上述的'},
  {cat:'newtype', stem:'In a heading-matching task, a heading that contains a question usually introduces:', opts:['A. A paragraph that answers that question','B. An unrelated topic','C. A definition','D. A conclusion'], ans:0, hint:'问题标题→回答段落'},
  {cat:'newtype', stem:'The phrase "in light of" means:', opts:['A. Considering; taking into account','B. Ignoring','C. Lighting up','D. Despite'], ans:0, hint:'in light of=鉴于'},
  {cat:'newtype', stem:'A sentence that begins with "For instance" serves as:', opts:['A. An example supporting the previous statement','B. A new argument','C. A counterargument','D. A conclusion'], ans:0, hint:'for instance=例如'},
  {cat:'newtype', stem:'The function of "that said" in a passage is to:', opts:['A. Introduce a contrasting or qualifying point','B. Summarize','C. Define a term','D. Cite a source'], ans:0, hint:'that said=话虽如此'},
  {cat:'newtype', stem:'When matching summaries to paragraphs, the key is to:', opts:['A. Identify the main idea of each paragraph first','B. Match random sentences','C. Focus only on the first sentence','D. Ignore details'], ans:0, hint:'先提炼段落主旨'},
  {cat:'newtype', stem:'"To this end" means:', opts:['A. For this purpose','B. At the end','C. Finally','D. In opposition'], ans:0, hint:'to this end=为此目的'},

  // ═══ 第八批 · 词汇语法 ═══
  {cat:'cloze', stem:'The president ___ on all parties to exercise restraint.', opts:['A. called','B. fell','C. ran','D. put'], ans:0, hint:'call on=呼吁'},
  {cat:'cloze', stem:'She is widely ___ as one of the leading experts in the field.', opts:['A. regarded','B. rewarded','C. recorded','D. recovered'], ans:0, hint:'be regarded as=被视为'},
  {cat:'cloze', stem:'The experiment ___ a series of unexpected results.', opts:['A. yielded','B. yelled','C. yearned','D. yawned'], ans:0, hint:'yield=产生(结果)'},
  {cat:'cloze', stem:'The politician tried to ___ the public\'s attention from the scandal.', opts:['A. divert','B. convert','C. invert','D. revert'], ans:0, hint:'divert attention=转移注意力'},
  {cat:'cloze', stem:'The two theories are not mutually ___; they can coexist.', opts:['A. exclusive','B. inclusive','C. exhaustive','D. excessive'], ans:0, hint:'mutually exclusive=互斥'},
  {cat:'cloze', stem:'The committee was ___ to investigate the allegations.', opts:['A. appointed','B. disappointed','C. anointed','D. pointed'], ans:0, hint:'appoint=任命'},
  {cat:'cloze', stem:'Global warming poses a ___ threat to biodiversity.', opts:['A. grave','B. grateful','C. graceful','D. gradual'], ans:0, hint:'grave threat=严重威胁'},
  {cat:'cloze', stem:'The study ___ the link between diet and disease.', opts:['A. established','B. abolished','C. demolished','D. embellished'], ans:0, hint:'establish=确立'},
  {cat:'cloze', stem:'His behavior was ___ with what he had promised.', opts:['A. inconsistent','B. consistent','C. persistent','D. insistent'], ans:0, hint:'inconsistent with=与...不一致'},
  {cat:'cloze', stem:'The new technology has the ___ to revolutionize the industry.', opts:['A. potential','B. patent','C. pattern','D. patience'], ans:0, hint:'potential=潜力'},
  {cat:'cloze', stem:'The company is ___ committed to environmental protection.', opts:['A. firmly','B. firstly','C. fairly','D. finely'], ans:0, hint:'firmly committed=坚定承诺'},
  {cat:'cloze', stem:'The crisis has ___ the need for reform.', opts:['A. highlighted','B. hindered','C. hidden','D. hosted'], ans:0, hint:'highlight=凸显'},
  {cat:'cloze', stem:'She ___ her success to hard work and determination.', opts:['A. attributed','B. contributed','C. distributed','D. substituted'], ans:0, hint:'attribute A to B=归因于'},
  {cat:'cloze', stem:'The rules ___ to all employees without exception.', opts:['A. apply','B. appeal','C. appear','D. approve'], ans:0, hint:'apply to=适用于'},
  {cat:'cloze', stem:'The investigation ___ that the company had violated regulations.', opts:['A. revealed','B. revolved','C. reversed','D. revived'], ans:0, hint:'reveal=揭示'},
  {cat:'cloze', stem:'The government ___ heavy penalties for tax evasion.', opts:['A. imposed','B. exposed','C. proposed','D. supposed'], ans:0, hint:'impose=施加（处罚）'},
  {cat:'cloze', stem:'The plan was ___ due to lack of funding.', opts:['A. abandoned','B. adapted','C. adopted','D. absorbed'], ans:0, hint:'abandon=放弃'},
  {cat:'cloze', stem:'The professor\'s lecture ___ a wide range of topics.', opts:['A. covered','B. discovered','C. recovered','D. uncovered'], ans:0, hint:'cover=涵盖'},
  {cat:'cloze', stem:'The earthquake ___ widespread destruction across the region.', opts:['A. caused','B. ceased','C. cited','D. charged'], ans:0, hint:'cause=造成'},
  {cat:'cloze', stem:'Despite facing numerous obstacles, she ___ in her efforts.', opts:['A. persevered','B. preserved','C. perceived','D. prevailed'], ans:0, hint:'persevere=坚持不懈'},

  // ═══ 第九批 · 阅读理解深度 ═══
  {cat:'reading', stem:'The word "proliferation" in the passage means:', opts:['A. Rapid increase in number','B. Decrease','C. Stagnation','D. Stabilization'], ans:0, hint:'proliferation=激增'},
  {cat:'reading', stem:'"The author takes issue with" means the author:', opts:['A. Disagrees with or criticizes','B. Agrees with','C. Ignores','D. Summarizes'], ans:0, hint:'take issue with=反对'},
  {cat:'reading', stem:'The word "precipitate" used as a verb means:', opts:['A. To cause something to happen suddenly','B. To slow down','C. To prevent','D. To measure'], ans:0, hint:'precipitate=促使突然发生'},
  {cat:'reading', stem:'"Intrinsic" as used in the passage is closest in meaning to:', opts:['A. Inherent; essential','B. External','C. Artificial','D. Optional'], ans:0, hint:'intrinsic=内在的'},
  {cat:'reading', stem:'The phrase "in the wake of" means:', opts:['A. Following; as a result of','B. Before','C. During','D. Instead of'], ans:0, hint:'in the wake of=在...之后'},
  {cat:'reading', stem:'"Salient" features means ___ features:', opts:['A. Most noticeable or important','B. Hidden','C. Minor','D. Irrelevant'], ans:0, hint:'salient=显著的'},
  {cat:'reading', stem:'The word "mitigate" means:', opts:['A. To make less severe or serious','B. To increase','C. To cause','D. To ignore'], ans:0, hint:'mitigate=减轻'},
  {cat:'reading', stem:'"The crux of the matter" refers to:', opts:['A. The most important point','B. An insignificant detail','C. The beginning','D. The end'], ans:0, hint:'crux=关键/核心'},
  {cat:'reading', stem:'The word "pertinent" means:', opts:['A. Relevant and applicable','B. Impertinent','C. Persistent','D. Permanent'], ans:0, hint:'pertinent=相关的'},
  {cat:'reading', stem:'"Unprecedented" describes something that:', opts:['A. Has never happened before','B. Has happened many times','C. Is expected','D. Is common'], ans:0, hint:'unprecedented=前所未有的'},
  {cat:'reading', stem:'The phrase "to grapple with" means:', opts:['A. To struggle or wrestle with a problem','B. To solve easily','C. To ignore','D. To document'], ans:0, hint:'grapple with=努力解决'},
  {cat:'reading', stem:'"Superficial" analysis means the analysis is:', opts:['A. Shallow; lacking depth','B. Deep and thorough','C. Perfect','D. Scientific'], ans:0, hint:'superficial=表面的'},
  {cat:'reading', stem:'The word "ambiguous" means:', opts:['A. Open to more than one interpretation','B. Very clear','C. Definitive','D. Certain'], ans:0, hint:'ambiguous=模棱两可的'},
  {cat:'reading', stem:'"Robust" evidence means evidence that is:', opts:['A. Strong and convincing','B. Weak','C. Doubtful','D. Missing'], ans:0, hint:'robust=强有力的'},
  {cat:'reading', stem:'The phrase "by and large" means:', opts:['A. On the whole; generally','B. Specifically','C. Rarely','D. Never'], ans:0, hint:'by and large=总的来说'},

  // ═══ 第十批 · 综合补充 ═══
  {cat:'newtype', stem:'"Whereas" is used to:', opts:['A. Show contrast between two things','B. Show similarity','C. Add information','D. Give examples'], ans:0, hint:'whereas=然而（对比）'},
  {cat:'newtype', stem:'The phrase "It follows that" signals:', opts:['A. A logical conclusion','B. A new topic','C. A contradiction','D. An example'], ans:0, hint:'由此可知'},
  {cat:'newtype', stem:'"Albeit" means:', opts:['A. Although','B. Because','C. Therefore','D. Unless'], ans:0, hint:'albeit=尽管'},
  {cat:'newtype', stem:'In academic writing, "to posit" means:', opts:['A. To put forward as a fact or principle','B. To deny','C. To question','D. To hide'], ans:0, hint:'posit=假定/提出'},
  {cat:'newtype', stem:'"Hitherto" means:', opts:['A. Until now','B. From now on','C. Long ago','D. Never'], ans:0, hint:'hitherto=迄今为止'},
  {cat:'newtype', stem:'The word "preclude" means:', opts:['A. To prevent from happening','B. To include','C. To conclude','D. To precede'], ans:0, hint:'preclude=阻止'},
  {cat:'newtype', stem:'"Vis-à-vis" is used to express:', opts:['A. In relation to; compared with','B. Agreement','C. Disagreement','D. Sequence'], ans:0, hint:'vis-à-vis=关于/相对于'},
  {cat:'cloze', stem:'The report ___ the importance of early intervention.', opts:['A. underscored','B. undermined','C. understood','D. undertook'], ans:0, hint:'underscore=强调'},
  {cat:'cloze', stem:'Her argument was ___ by a lack of evidence.', opts:['A. hampered','B. helped','C. honored','D. hosted'], ans:0, hint:'hamper=阻碍'},
  {cat:'cloze', stem:'The industry has undergone a ___ transformation.', opts:['A. radical','B. radiant','C. random','D. rapid'], ans:0, hint:'radical transformation=根本性变革'},
  {cat:'reading', stem:'The word "tangible" means:', opts:['A. Real and concrete; can be touched','B. Abstract','C. Invisible','D. Theoretical'], ans:0, hint:'tangible=有形的'},
  {cat:'reading', stem:'"Concomitant" means:', opts:['A. Accompanying; occurring together','B. Opposing','C. Sequential','D. Exclusive'], ans:0, hint:'concomitant=伴随的'},
  {cat:'reading', stem:'The phrase "to bear fruit" means:', opts:['A. To produce positive results','B. To carry fruit','C. To fail completely','D. To plant trees'], ans:0, hint:'bear fruit=取得成果'},
  {cat:'reading', stem:'"Status quo" refers to:', opts:['A. The existing state of affairs','B. A new situation','C. A future plan','D. A historical event'], ans:0, hint:'status quo=现状'},
  {cat:'reading', stem:'The word "detrimental" means:', opts:['A. Harmful; damaging','B. Beneficial','C. Neutral','D. Helpful'], ans:0, hint:'detrimental=有害的'},
  {cat:'cloze', stem:'The negotiations ___ in a historic agreement.', opts:['A. culminated','B. calculated','C. cultivated','D. circulated'], ans:0, hint:'culminate in=以...告终'},
  {cat:'cloze', stem:'The scholar ___ the theory that had been accepted for decades.', opts:['A. challenged','B. championed','C. channeled','D. charged'], ans:0, hint:'challenge=质疑'},
  {cat:'cloze', stem:'Public opinion was ___ against the proposed changes.', opts:['A. mobilized','B. modernized','C. minimized','D. memorized'], ans:0, hint:'mobilize=动员'},
  {cat:'cloze', stem:'The findings ___ a reassessment of current policies.', opts:['A. warrant','B. wander','C. waive','D. weaken'], ans:0, hint:'warrant=使有必要'},
  {cat:'reading', stem:'The word "juxtapose" means:', opts:['A. Place side by side for comparison','B. Separate','C. Combine','D. Eliminate'], ans:0, hint:'juxtapose=并列对比'},
  {cat:'reading', stem:'"Disparate" means:', opts:['A. Fundamentally different','B. Similar','C. Equal','D. Comparable'], ans:0, hint:'disparate=完全不同的'},
  {cat:'reading', stem:'The word "ostensibly" means:', opts:['A. Apparently; seemingly','B. Certainly','C. Secretly','D. Obviously'], ans:0, hint:'ostensibly=表面上'},

  // ═══ 最终90题补齐 ═══

  // 完形填空 · 高频词汇辨析
  {cat:'cloze', stem:'The new regulations will ___ a significant impact on the industry.', opts:['A. have','B. make','C. take','D. give'], ans:0, hint:'have an impact on=产生影响'},
  {cat:'cloze', stem:'The committee ___ the proposal after lengthy debate.', opts:['A. approved','B. improved','C. proved','D. removed'], ans:0, hint:'approve=批准'},
  {cat:'cloze', stem:'The research ___ new insights into the causes of the disease.', opts:['A. provided','B. prevented','C. predicted','D. preserved'], ans:0, hint:'provide insights=提供洞见'},
  {cat:'cloze', stem:'The government ___ strict measures to combat corruption.', opts:['A. adopted','B. adapted','C. admitted','D. admired'], ans:0, hint:'adopt measures=采取措施'},
  {cat:'cloze', stem:'The scientists ___ to find a cure for the disease.', opts:['A. endeavored','B. endured','C. engaged','D. enlarged'], ans:0, hint:'endeavor=努力尝试'},
  {cat:'cloze', stem:'The treaty was ___ by both countries in 2020.', opts:['A. ratified','B. rectified','C. verified','D. classified'], ans:0, hint:'ratify=批准(条约)'},
  {cat:'cloze', stem:'The company ___ its commitment to sustainability.', opts:['A. reaffirmed','B. reformed','C. refunded','D. refused'], ans:0, hint:'reaffirm=重申'},
  {cat:'cloze', stem:'The data ___ a strong correlation between the two variables.', opts:['A. revealed','B. revolved','C. reversed','D. revived'], ans:0, hint:'reveal=揭示'},
  {cat:'cloze', stem:'The new policy aims to ___ economic growth.', opts:['A. stimulate','B. simulate','C. stipulate','D. stagnate'], ans:0, hint:'stimulate=刺激'},
  {cat:'cloze', stem:'The project was ___ due to budget constraints.', opts:['A. shelved','B. shaped','C. shared','D. sharpened'], ans:0, hint:'shelve=搁置'},
  {cat:'cloze', stem:'The organization ___ a comprehensive report on climate change.', opts:['A. issued','B. insured','C. isolated','D. irritated'], ans:0, hint:'issue a report=发布报告'},
  {cat:'cloze', stem:'The professor ___ the importance of critical thinking.', opts:['A. emphasized','B. empathized','C. embarked','D. embraced'], ans:0, hint:'emphasize=强调'},
  {cat:'cloze', stem:'The court ___ the defendant not guilty.', opts:['A. found','B. founded','C. fixed','D. formed'], ans:0, hint:'find sb not guilty=判定无罪'},
  {cat:'cloze', stem:'Success in business often ___ on timing and preparation.', opts:['A. hinges','B. hangs','C. holds','D. hooks'], ans:0, hint:'hinge on=取决于'},
  {cat:'cloze', stem:'The election results ___ a shift in public opinion.', opts:['A. reflected','B. rejected','C. refined','D. refreshed'], ans:0, hint:'reflect=反映'},
  {cat:'cloze', stem:'The charity ___ funds for disaster relief.', opts:['A. raised','B. rose','C. razed','D. raced'], ans:0, hint:'raise funds=筹集资金'},
  {cat:'cloze', stem:'The manager ___ the team for their outstanding performance.', opts:['A. commended','B. commanded','C. commenced','D. commented'], ans:0, hint:'commend=表扬'},
  {cat:'cloze', stem:'The new law ___ discrimination in the workplace.', opts:['A. prohibits','B. promotes','C. proclaims','D. produces'], ans:0, hint:'prohibit=禁止'},
  {cat:'cloze', stem:'The author ___ a vivid picture of life in the 18th century.', opts:['A. paints','B. prints','C. points','D. pours'], ans:0, hint:'paint a picture=描绘'},
  {cat:'cloze', stem:'The investigation ___ several irregularities in the accounts.', opts:['A. uncovered','B. undertook','C. understood','D. unified'], ans:0, hint:'uncover=发现(隐藏的)'},

  // 阅读理解 · 词义推断与逻辑
  {cat:'reading', stem:'The word "ameliorate" means:', opts:['A. To make something better','B. To make worse','C. To destroy','D. To ignore'], ans:0, hint:'ameliorate=改善'},
  {cat:'reading', stem:'"Burgeoning" industries are industries that are:', opts:['A. Growing rapidly','B. Declining','C. Stagnating','D. Disappearing'], ans:0, hint:'burgeoning=蓬勃发展的'},
  {cat:'reading', stem:'The word "nebulous" means:', opts:['A. Vague and unclear','B. Bright and clear','C. Dark and scary','D. Small and compact'], ans:0, hint:'nebulous=模糊的'},
  {cat:'reading', stem:'"Pernicious" effects are effects that are:', opts:['A. Harmful, especially in a gradual way','B. Beneficial','C. Neutral','D. Temporary'], ans:0, hint:'pernicious=有害的(渐进)'},
  {cat:'reading', stem:'The word "tenacious" describes someone who is:', opts:['A. Persistent and determined','B. Lazy and indifferent','C. Shy and reserved','D. Aggressive and hostile'], ans:0, hint:'tenacious=坚韧不拔的'},
  {cat:'reading', stem:'"Expedite" means to:', opts:['A. Speed up a process','B. Slow down','C. Cancel','D. Postpone'], ans:0, hint:'expedite=加速'},
  {cat:'reading', stem:'The word "spurious" means:', opts:['A. False or fake','B. Genuine','C. Important','D. Beautiful'], ans:0, hint:'spurious=虚假的'},
  {cat:'reading', stem:'"Quintessential" means:', opts:['A. Representing the most perfect example','B. Ordinary','C. Incomplete','D. Controversial'], ans:0, hint:'quintessential=典型的'},
  {cat:'reading', stem:'The word "truncate" means:', opts:['A. To shorten by cutting off','B. To lengthen','C. To widen','D. To deepen'], ans:0, hint:'truncate=截断'},
  {cat:'reading', stem:'"Vicarious" experience is experience gained:', opts:['A. Through observing others rather than doing it yourself','B. By direct participation','C. Through reading only','D. By accident'], ans:0, hint:'vicarious=间接体验的'},
  {cat:'reading', stem:'The word "eschew" means:', opts:['A. To deliberately avoid','B. To embrace','C. To chew','D. To review'], ans:0, hint:'eschew=刻意避免'},
  {cat:'reading', stem:'"Prolific" author means an author who:', opts:['A. Produces a large amount of work','B. Writes rarely','C. Is unpublished','D. Is anonymous'], ans:0, hint:'prolific=多产的'},
  {cat:'reading', stem:'The word "cursory" means:', opts:['A. Hasty and superficial','B. Thorough and detailed','C. Careful','D. Slow'], ans:0, hint:'cursory=粗略的'},
  {cat:'reading', stem:'"Idiosyncratic" means:', opts:['A. Peculiar to an individual','B. Common to all','C. Universal','D. Standard'], ans:0, hint:'idiosyncratic=独特的'},
  {cat:'reading', stem:'The word "copious" means:', opts:['A. Abundant; in large quantities','B. Scarce','C. Moderate','D. Tiny'], ans:0, hint:'copious=大量的'},
  {cat:'reading', stem:'"Insidious" describes something that is:', opts:['A. Proceeding harmfully but subtly','B. Obvious and loud','C. Quick and sudden','D. Harmless'], ans:0, hint:'insidious=阴险的/潜伏的'},
  {cat:'reading', stem:'The word "propensity" means:', opts:['A. A natural tendency','B. A strong dislike','C. A legal right','D. A physical object'], ans:0, hint:'propensity=倾向'},
  {cat:'reading', stem:'"Ubiquitous" technology means technology that is:', opts:['A. Found everywhere','B. Rare and expensive','C. Outdated','D. Dangerous'], ans:0, hint:'ubiquitous=无处不在的'},
  {cat:'reading', stem:'The word "ephemeral" means:', opts:['A. Lasting for a very short time','B. Permanent','C. Ancient','D. Expensive'], ans:0, hint:'ephemeral=短暂的'},
  {cat:'reading', stem:'"Auspicious" beginning means a beginning that is:', opts:['A. Favorable; promising success','B. Unfortunate','C. Boring','D. Complicated'], ans:0, hint:'auspicious=吉利的'},

  // 新题型 · 逻辑衔接与排序
  {cat:'newtype', stem:'The phrase "in retrospect" means:', opts:['A. Looking back on the past','B. Looking forward','C. At present','D. In the future'], ans:0, hint:'in retrospect=回顾起来'},
  {cat:'newtype', stem:'"Conversely" is used to introduce:', opts:['A. An opposite or contrasting statement','B. A similar point','C. A conclusion','D. An example'], ans:0, hint:'conversely=相反地'},
  {cat:'newtype', stem:'The phrase "by the same token" means:', opts:['A. For the same reason; similarly','B. Using the same currency','C. In contrast','D. As a result'], ans:0, hint:'by the same token=同样地'},
  {cat:'newtype', stem:'"Insofar as" means:', opts:['A. To the extent that','B. Because','C. Although','D. Unless'], ans:0, hint:'insofar as=在...范围内'},
  {cat:'newtype', stem:'The phrase "be that as it may" signals:', opts:['A. A concessive statement (acknowledging a point but continuing)','B. Disagreement','C. Agreement','D. A question'], ans:0, hint:'尽管如此（让步）'},
  {cat:'newtype', stem:'"Inasmuch as" means:', opts:['A. Since; because','B. Although','C. Unless','D. Until'], ans:0, hint:'inasmuch as=因为/鉴于'},
  {cat:'newtype', stem:'A sentence beginning with "Granted" signals:', opts:['A. A concession before a counterargument','B. Permission','C. A conclusion','D. An example'], ans:0, hint:'Granted=诚然（让步）'},
  {cat:'newtype', stem:'The phrase "in tandem with" means:', opts:['A. Together with; alongside','B. Against','C. Instead of','D. Before'], ans:0, hint:'in tandem with=与...一起'},
  {cat:'newtype', stem:'"Correspondingly" is used to show:', opts:['A. A related or parallel change','B. A contrast','C. A cause','D. A random fact'], ans:0, hint:'correspondingly=相应地'},
  {cat:'newtype', stem:'The word "erstwhile" means:', opts:['A. Former','B. Current','C. Future','D. Eternal'], ans:0, hint:'erstwhile=以前的'},
  {cat:'newtype', stem:'"Per se" is a Latin phrase meaning:', opts:['A. By itself; intrinsically','B. For example','C. On the other hand','D. In conclusion'], ans:0, hint:'per se=本身'},
  {cat:'newtype', stem:'The phrase "mutatis mutandis" means:', opts:['A. With the necessary changes having been made','B. Without any changes','C. In the same way','D. Randomly'], ans:0, hint:'mutatis mutandis=作必要修改后'},
  {cat:'newtype', stem:'"Ipso facto" means:', opts:['A. By that very fact','B. In another way','C. Despite this','D. For example'], ans:0, hint:'ipso facto=由此'},
  {cat:'newtype', stem:'A paragraph that starts with "Admittedly" is likely to:', opts:['A. Concede a point before presenting a counterargument','B. Conclude the essay','C. Introduce a new topic','D. Summarize findings'], ans:0, hint:'Admittedly=诚然→让步'},
  {cat:'newtype', stem:'The phrase "all things considered" is used to:', opts:['A. Introduce a balanced conclusion','B. Start a new argument','C. Give an example','D. Cite a source'], ans:0, hint:'综合考虑→总结'},

  // 综合 · 高频考研词汇
  {cat:'cloze', stem:'The economic downturn ___ many businesses to close.', opts:['A. compelled','B. compiled','C. competed','D. complained'], ans:0, hint:'compel=迫使'},
  {cat:'cloze', stem:'The government ___ a state of emergency.', opts:['A. declared','B. declined','C. delayed','D. delivered'], ans:0, hint:'declare=宣布'},
  {cat:'cloze', stem:'The policy was designed to ___ innovation.', opts:['A. foster','B. frustrate','C. forbid','D. forget'], ans:0, hint:'foster=促进/培养'},
  {cat:'cloze', stem:'The data was ___ from multiple sources.', opts:['A. gathered','B. guarded','C. guided','D. guaranteed'], ans:0, hint:'gather=收集'},
  {cat:'cloze', stem:'The regulations ___ strict penalties for violations.', opts:['A. stipulate','B. stimulate','C. simulate','D. stagnate'], ans:0, hint:'stipulate=规定'},
  {cat:'reading', stem:'The word "nascent" means:', opts:['A. Just beginning to develop','B. Fully mature','C. Declining','D. Ancient'], ans:0, hint:'nascent=新生的'},
  {cat:'reading', stem:'"Extraneous" information is information that is:', opts:['A. Irrelevant; not pertaining to the subject','B. Essential','C. Accurate','D. Detailed'], ans:0, hint:'extraneous=无关的'},
  {cat:'reading', stem:'The word "cognizant" means:', opts:['A. Aware of; having knowledge of','B. Ignorant','C. Confused','D. Angry'], ans:0, hint:'cognizant=认识到的'},
  {cat:'reading', stem:'"Irrevocable" means:', opts:['A. Cannot be changed or reversed','B. Easily changed','C. Temporary','D. Flexible'], ans:0, hint:'irrevocable=不可撤回的'},
  {cat:'reading', stem:'The word "perfunctory" means:', opts:['A. Done without care; superficial','B. Thorough','C. Enthusiastic','D. Creative'], ans:0, hint:'perfunctory=敷衍的'},

  // ═══ 最后25题补齐至500 ═══
  {cat:'cloze', stem:'The company ___ a new strategy to increase market share.', opts:['A. devised','B. divided','C. devoted','D. derived'], ans:0, hint:'devise=设计/制定'},
  {cat:'cloze', stem:'The evidence strongly ___ the theory.', opts:['A. supports','B. suspects','C. suppresses','D. surpasses'], ans:0, hint:'support=支持'},
  {cat:'cloze', stem:'The two countries agreed to ___ diplomatic relations.', opts:['A. establish','B. abolish','C. diminish','D. extinguish'], ans:0, hint:'establish=建立'},
  {cat:'cloze', stem:'The report ___ that further research is needed.', opts:['A. recommends','B. commands','C. demands','D. reprimands'], ans:0, hint:'recommend=建议'},
  {cat:'cloze', stem:'Poverty ___ millions of children of educational opportunities.', opts:['A. deprives','B. derives','C. delivers','D. describes'], ans:0, hint:'deprive of=剥夺'},
  {cat:'reading', stem:'The word "sanguine" means:', opts:['A. Optimistic; positive','B. Pessimistic','C. Angry','D. Confused'], ans:0, hint:'sanguine=乐观的'},
  {cat:'reading', stem:'"Repercussions" are:', opts:['A. Unintended consequences of an action','B. Planned outcomes','C. Celebrations','D. Meetings'], ans:0, hint:'repercussions=反响/后果'},
  {cat:'reading', stem:'The word "candid" means:', opts:['A. Honest and straightforward','B. Secretive','C. Diplomatic','D. Cunning'], ans:0, hint:'candid=坦率的'},
  {cat:'reading', stem:'"Antithetical" means:', opts:['A. Directly opposed or contrasted','B. Similar','C. Related','D. Complementary'], ans:0, hint:'antithetical=对立的'},
  {cat:'reading', stem:'The word "futile" means:', opts:['A. Pointless; incapable of producing results','B. Successful','C. Difficult','D. Expensive'], ans:0, hint:'futile=徒劳的'},
  {cat:'newtype', stem:'The phrase "on the grounds that" introduces:', opts:['A. A reason or justification','B. A location','C. A contrast','D. A conclusion'], ans:0, hint:'on the grounds that=基于...理由'},
  {cat:'newtype', stem:'"Lest" is used to express:', opts:['A. Fear that something might happen','B. Hope','C. Certainty','D. Indifference'], ans:0, hint:'lest=以免/唯恐'},
  {cat:'newtype', stem:'The phrase "in lieu of" means:', opts:['A. Instead of','B. In addition to','C. Because of','D. In spite of'], ans:0, hint:'in lieu of=代替'},
  {cat:'cloze', stem:'The experiment was ___ under controlled conditions.', opts:['A. conducted','B. constructed','C. consulted','D. consumed'], ans:0, hint:'conduct=进行(实验)'},
  {cat:'cloze', stem:'The factory ___ toxic waste into the river.', opts:['A. discharged','B. discounted','C. discovered','D. discussed'], ans:0, hint:'discharge=排放'},
  {cat:'reading', stem:'The word "acquiesce" means:', opts:['A. To accept something reluctantly without protest','B. To strongly resist','C. To celebrate','D. To question'], ans:0, hint:'acquiesce=默许'},
  {cat:'reading', stem:'"Incontrovertible" evidence is evidence that is:', opts:['A. Impossible to deny or dispute','B. Weak','C. Questionable','D. Fabricated'], ans:0, hint:'incontrovertible=无可辩驳的'},
  {cat:'reading', stem:'The word "assiduous" means:', opts:['A. Showing great care and perseverance','B. Lazy','C. Careless','D. Indifferent'], ans:0, hint:'assiduous=勤勉的'},
  {cat:'cloze', stem:'The journalist ___ the corruption scandal.', opts:['A. exposed','B. expected','C. expired','D. exported'], ans:0, hint:'expose=揭露'},
  {cat:'cloze', stem:'The organization ___ a campaign to raise awareness.', opts:['A. launched','B. latched','C. laughed','D. lasted'], ans:0, hint:'launch a campaign=发起运动'},
  {cat:'reading', stem:'The word "precarious" means:', opts:['A. Not securely held; dangerously unstable','B. Safe and stable','C. Comfortable','D. Permanent'], ans:0, hint:'precarious=不稳定的/危险的'},
  {cat:'reading', stem:'"Reticent" describes someone who is:', opts:['A. Not revealing thoughts or feelings readily','B. Very talkative','C. Aggressive','D. Emotional'], ans:0, hint:'reticent=沉默寡言的'},
  {cat:'newtype', stem:'The phrase "with a view to" means:', opts:['A. With the aim or intention of','B. With a scenery of','C. In opposition to','D. Without considering'], ans:0, hint:'with a view to=目的在于'},
  {cat:'newtype', stem:'"Notwithstanding" can be used as a:', opts:['A. Preposition, conjunction, and adverb','B. Only a noun','C. Only a verb','D. Only an adjective'], ans:0, hint:'notwithstanding=尽管(多词性)'},
  {cat:'cloze', stem:'The reforms ___ significant improvements in public health.', opts:['A. brought about','B. broke down','C. backed up','D. blew out'], ans:0, hint:'bring about=带来/引起'},
];

// 导出题库
if (typeof window !== 'undefined') window.ENGLISH_QUESTIONS = ENGLISH_QUESTIONS;
