/**
 * 301数学 · 500道单选题题库
 * ========================================
 * 每局按真实卷面抽10题(全部单选)
 * 
 * 分类标签 cat:
 *   calculus = 高等数学(极限/微分/积分/微分方程/级数/多元)
 *   linalg   = 线性代数
 *   prob     = 概率论与数理统计
 */
const MATH_QUESTIONS = [
  // ═══ 高等数学 · 极限与连续 ═══
  {cat:'calculus', stem:'极限 lim(x→0) sin(x)/x 等于：', opts:['A. 0','B. 1','C. ∞','D. -1'], ans:1, hint:'第一个重要极限'},
  {cat:'calculus', stem:'极限 lim(x→∞) (1+1/x)^x 等于：', opts:['A. 1','B. e','C. ∞','D. 0'], ans:1, hint:'第二个重要极限'},
  {cat:'calculus', stem:'lim(x→0) (1-cosx)/x² 等于：', opts:['A. 0','B. 1/2','C. 1','D. 2'], ans:1, hint:'等价无穷小1-cosx~x²/2'},
  {cat:'calculus', stem:'lim(x→0) tan(x)/x 等于：', opts:['A. 0','B. 1','C. ∞','D. -1'], ans:1, hint:'tanx~x(x→0)'},
  {cat:'calculus', stem:'lim(x→0) (e^x-1)/x 等于：', opts:['A. 0','B. 1','C. e','D. -1'], ans:1, hint:'等价无穷小e^x-1~x'},
  {cat:'calculus', stem:'lim(x→0) ln(1+x)/x 等于：', opts:['A. 0','B. 1','C. e','D. ln2'], ans:1, hint:'等价无穷小ln(1+x)~x'},
  {cat:'calculus', stem:'设f(x)在x=a处连续，则lim(h→0)[f(a+h)-f(a-h)]/(2h)等于：', opts:['A. f\'(a)','B. f(a)','C. 2f\'(a)','D. 条件不足'], ans:3, hint:'连续不一定可导'},
  {cat:'calculus', stem:'函数f(x)在x=x₀处可导，则f(x)在该点：', opts:['A. 一定连续','B. 不一定连续','C. 一定不连续','D. 无法判断'], ans:0, hint:'可导⇒连续'},
  {cat:'calculus', stem:'无穷小量α与β是等价无穷小的充要条件是：', opts:['A. lim(α/β)=1','B. lim(α/β)=0','C. lim(α-β)=0','D. α=β'], ans:0, hint:'等价无穷小比值趋于1'},
  {cat:'calculus', stem:'数列{(-1)^n/n}的极限为：', opts:['A. 0','B. 1','C. -1','D. 不存在'], ans:0, hint:'|(-1)^n/n|=1/n→0'},
  {cat:'calculus', stem:'函数在某点极限存在的充要条件是：', opts:['A. 左极限=右极限','B. 函数在该点有定义','C. 函数在该点连续','D. 函数在该点可导'], ans:0, hint:'左极限=右极限⇔极限存在'},

  // ═══ 高等数学 · 一元微分 ═══
  {cat:'calculus', stem:'设f(x)=eˣ，则f\'(x)=', opts:['A. eˣ','B. xeˣ⁻¹','C. 1/eˣ','D. ln(x)'], ans:0, hint:'指数函数求导不变'},
  {cat:'calculus', stem:'(sin x)\' 等于：', opts:['A. cos x','B. -cos x','C. sin x','D. -sin x'], ans:0, hint:'sin求导=cos'},
  {cat:'calculus', stem:'(ln x)\' 等于：', opts:['A. 1/x','B. x','C. e^x','D. 1'], ans:0, hint:'对数函数导数=1/x'},
  {cat:'calculus', stem:'函数f(x)=x³-3x在x=1处的切线斜率为：', opts:['A. 0','B. -2','C. 3','D. -3'], ans:0, hint:'f\'(1)=3×1²-3=0'},
  {cat:'calculus', stem:'若f\'(x₀)=0且f\'\'(x₀)>0，则x₀是：', opts:['A. 极小值点','B. 极大值点','C. 既不是极大也不是极小','D. 拐点'], ans:0, hint:'f\'\'(x₀)>0→极小'},
  {cat:'calculus', stem:'罗尔定理的条件：f(x)在[a,b]连续，在(a,b)可导，f(a)=f(b)，则存在ξ∈(a,b)使得：', opts:['A. f\'(ξ)=0','B. f(ξ)=0','C. f\'\'(ξ)=0','D. f(ξ)=f(a)'], ans:0, hint:'罗尔定理：存在零导数点'},
  {cat:'calculus', stem:'拉格朗日中值定理：f(b)-f(a)=', opts:['A. f\'(ξ)(b-a)','B. f(ξ)(b-a)','C. f\'(b)-f\'(a)','D. f\'(a)(b-a)'], ans:0, hint:'拉格朗日中值公式'},
  {cat:'calculus', stem:'洛必达法则适用于求解的不定式类型是：', opts:['A. 0/0 或 ∞/∞','B. 0×∞','C. 1^∞','D. 以上都可以(先变形)'], ans:3, hint:'其他类型先变形为0/0或∞/∞'},
  {cat:'calculus', stem:'函数f(x)的二阶导数f\'\'(x₀)=0，且f\'\'在x₀两侧变号，则x₀是：', opts:['A. 拐点','B. 极值点','C. 最值点','D. 零点'], ans:0, hint:'f\'\'变号→拐点'},
  {cat:'calculus', stem:'隐函数y由方程x²+y²=1确定，则dy/dx=', opts:['A. -x/y','B. x/y','C. -y/x','D. y/x'], ans:0, hint:'两边求导：2x+2yy\'=0'},
  {cat:'calculus', stem:'参数方程x=cos(t), y=sin(t)的导数dy/dx=', opts:['A. -cos(t)/sin(t)','B. cos(t)/sin(t)','C. -cot(t)','D. A和C相同'], ans:3, hint:'dy/dx=(dy/dt)/(dx/dt)=cost/(-sint)=-cot(t)'},
  {cat:'calculus', stem:'莱布尼茨公式用于求：', opts:['A. 两个函数乘积的n阶导数','B. 不定积分','C. 极限','D. 级数和'], ans:0, hint:'(uv)^(n)的展开'},
  {cat:'calculus', stem:'曲率公式κ=|y\'\'|/(1+y\'²)^(3/2)，当y\'=0时曲率等于：', opts:['A. |y\'\'|','B. 0','C. 1','D. ∞'], ans:0, hint:'y\'=0时分母=1'},

  // ═══ 高等数学 · 一元积分 ═══
  {cat:'calculus', stem:'∫₀¹ x² dx 等于：', opts:['A. 1/3','B. 1/2','C. 1','D. 2/3'], ans:0, hint:'x³/3从0到1'},
  {cat:'calculus', stem:'∫ 1/x dx 等于：', opts:['A. ln|x|+C','B. x²/2+C','C. 1/x²+C','D. e^x+C'], ans:0, hint:'1/x的原函数是ln|x|'},
  {cat:'calculus', stem:'∫ eˣ dx 等于：', opts:['A. eˣ+C','B. xeˣ+C','C. eˣ/x+C','D. ln(eˣ)+C'], ans:0, hint:'eˣ积分还是eˣ'},
  {cat:'calculus', stem:'分部积分公式∫u dv等于：', opts:['A. uv-∫v du','B. uv+∫v du','C. u/v-∫v du','D. uv-∫u dv'], ans:0, hint:'∫udv=uv-∫vdu'},
  {cat:'calculus', stem:'∫₋₁¹ x³ dx 等于：', opts:['A. 0','B. 1/4','C. 1/2','D. 2/3'], ans:0, hint:'奇函数在对称区间积分为0'},
  {cat:'calculus', stem:'变上限积分函数F(x)=∫₀ˣ f(t)dt的导数F\'(x)=', opts:['A. f(x)','B. f(0)','C. F(x)','D. ∫f(x)dx'], ans:0, hint:'变上限积分的导数=被积函数'},
  {cat:'calculus', stem:'广义积分∫₁^∞ 1/x² dx的值为：', opts:['A. 1','B. ∞','C. 0','D. 1/2'], ans:0, hint:'-1/x从1到∞=0-(-1)=1'},
  {cat:'calculus', stem:'广义积分∫₁^∞ 1/x dx的敛散性：', opts:['A. 发散','B. 收敛','C. 等于1','D. 等于0'], ans:0, hint:'p=1时发散'},
  {cat:'calculus', stem:'∫₀^(π/2) sin²x dx 等于：', opts:['A. π/4','B. π/2','C. 1','D. 0'], ans:0, hint:'华里士公式'},
  {cat:'calculus', stem:'换元积分法∫f(g(x))g\'(x)dx=', opts:['A. ∫f(u)du (令u=g(x))','B. f(g(x))+C','C. f\'(g(x))+C','D. g(f(x))+C'], ans:0, hint:'第一类换元法'},

  // ═══ 高等数学 · 多元函数 ═══
  {cat:'calculus', stem:'二元函数f(x,y)=x²+y²的偏导数∂f/∂x=', opts:['A. 2x','B. 2y','C. 2x+2y','D. x²'], ans:0, hint:'对x偏导，y视为常数'},
  {cat:'calculus', stem:'梯度grad f在某点处的方向是：', opts:['A. 函数增长最快的方向','B. 函数减小最快的方向','C. 等值线的切线方向','D. 任意方向'], ans:0, hint:'梯度=最速上升方向'},
  {cat:'calculus', stem:'二重积分∫∫_D 1 dA的几何意义是：', opts:['A. 区域D的面积','B. 区域D的周长','C. 曲面的面积','D. 体积'], ans:0, hint:'被积函数为1时积分=面积'},
  {cat:'calculus', stem:'全微分dz=∂z/∂x·dx+∂z/∂y·dy的存在性要求：', opts:['A. 偏导数存在且连续','B. 偏导数存在即可','C. 函数连续即可','D. 函数有定义即可'], ans:0, hint:'偏导连续⇒可微'},
  {cat:'calculus', stem:'二元函数f(x,y)取极值的必要条件是：', opts:['A. fx=0且fy=0','B. fxx>0','C. fxx·fyy-fxy²>0','D. B和C都需要'], ans:0, hint:'偏导为零是必要条件'},
  {cat:'calculus', stem:'格林公式将什么联系起来？', opts:['A. 平面区域上的二重积分与其边界的曲线积分','B. 空间曲面积分与体积分','C. 定积分与不定积分','D. 级数与积分'], ans:0, hint:'Green公式=二重积分↔曲线积分'},
  {cat:'calculus', stem:'交换二次积分顺序时，关键步骤是：', opts:['A. 画出积分区域，重新确定积分限','B. 直接交换dx和dy的位置','C. 改变被积函数','D. 添加负号'], ans:0, hint:'必须画图找新积分限'},

  // ═══ 高等数学 · 微分方程 ═══
  {cat:'calculus', stem:'一阶齐次方程dy/dx=f(y/x)的标准解法是：', opts:['A. 令u=y/x进行换元','B. 直接积分','C. 分离变量','D. 常数变易法'], ans:0, hint:'u=y/x→y=ux→分离变量'},
  {cat:'calculus', stem:'二阶常系数齐次方程y\'\'-4y=0的通解是：', opts:['A. C₁e²ˣ+C₂e⁻²ˣ','B. C₁cos2x+C₂sin2x','C. C₁e⁴ˣ','D. C₁x+C₂'], ans:0, hint:'特征方程r²-4=0,r=±2'},
  {cat:'calculus', stem:'特征方程有重根r=r₁=r₂时，通解的形式为：', opts:['A. (C₁+C₂x)e^(r₁x)','B. C₁e^(r₁x)+C₂e^(r₂x)','C. C₁cos(r₁x)+C₂sin(r₁x)','D. C₁+C₂x'], ans:0, hint:'重根乘x'},
  {cat:'calculus', stem:'特征方程有共轭复根r=α±βi时，通解含：', opts:['A. e^(αx)(C₁cosβx+C₂sinβx)','B. C₁e^(αx)+C₂e^(βx)','C. C₁cos(αx)+C₂sin(βx)','D. (C₁+C₂x)e^(αx)'], ans:0, hint:'复根→三角函数'},
  {cat:'calculus', stem:'可分离变量方程g(y)dy=f(x)dx的解法是：', opts:['A. 两边分别积分','B. 换元法','C. 常数变易法','D. 级数展开'], ans:0, hint:'分离后各自积分'},
  {cat:'calculus', stem:'伯努利方程y\'+P(x)y=Q(x)y^n的解法是：', opts:['A. 令z=y^(1-n)化为线性方程','B. 直接积分','C. 分离变量','D. 凑微分'], ans:0, hint:'z=y^(1-n)变线性'},

  // ═══ 高等数学 · 级数 ═══
  {cat:'calculus', stem:'泰勒展开eˣ=1+x+x²/2!+...的收敛半径是：', opts:['A. ∞','B. 1','C. 2','D. 0'], ans:0, hint:'eˣ处处收敛'},
  {cat:'calculus', stem:'几何级数∑(n=0 to ∞) r^n收敛的条件是：', opts:['A. |r|<1','B. r<1','C. r>0','D. r≠0'], ans:0, hint:'公比绝对值小于1'},
  {cat:'calculus', stem:'p级数∑1/n^p收敛的条件是：', opts:['A. p>1','B. p>0','C. p≥1','D. p>2'], ans:0, hint:'p>1收敛，p≤1发散'},
  {cat:'calculus', stem:'交错级数∑(-1)^n·a_n收敛的莱布尼茨判别法要求：', opts:['A. a_n单调递减且趋于0','B. a_n有界','C. a_n为正','D. a_n为整数'], ans:0, hint:'单调递减+趋零'},
  {cat:'calculus', stem:'幂级数∑aₙxⁿ的收敛半径R的计算公式（比值法）是：', opts:['A. R=lim|aₙ/aₙ₊₁|','B. R=lim|aₙ₊₁/aₙ|','C. R=∑aₙ','D. R=a₁'], ans:0, hint:'R=lim|aₙ/aₙ₊₁|'},
  {cat:'calculus', stem:'麦克劳林展开sin(x)=', opts:['A. x-x³/3!+x⁵/5!-...','B. 1-x²/2!+x⁴/4!-...','C. x+x²/2+x³/3+...','D. 1+x+x²+...'], ans:0, hint:'sinx奇数项'},
  {cat:'calculus', stem:'cos(x)的麦克劳林展开是：', opts:['A. 1-x²/2!+x⁴/4!-...','B. x-x³/3!+x⁵/5!-...','C. 1+x+x²/2!+...','D. x+x³/3+x⁵/5+...'], ans:0, hint:'cosx偶数项'},

  // ═══ 线性代数 ═══
  {cat:'linalg', stem:'矩阵A的秩r(A)=0，则A是：', opts:['A. 零矩阵','B. 单位矩阵','C. 对角矩阵','D. 可逆矩阵'], ans:0, hint:'秩为0=全零'},
  {cat:'linalg', stem:'n阶方阵A可逆的充要条件是：', opts:['A. |A|≠0','B. |A|=0','C. r(A)<n','D. A有零特征值'], ans:0, hint:'行列式不为零⇔可逆'},
  {cat:'linalg', stem:'向量a=(1,2,3)和b=(2,4,6)的关系是：', opts:['A. 线性相关','B. 线性无关','C. 正交','D. 等价'], ans:0, hint:'b=2a→线性相关'},
  {cat:'linalg', stem:'n个n维向量线性无关的充要条件是：', opts:['A. 由它们构成的矩阵的行列式不为零','B. 存在不全为零的系数使线性组合为零','C. 它们两两正交','D. 它们的模都为1'], ans:0, hint:'行列式≠0⇔线性无关'},
  {cat:'linalg', stem:'齐次线性方程组Ax=0有非零解的充要条件是：', opts:['A. r(A)<n(未知数个数)','B. r(A)=n','C. |A|≠0','D. A=O'], ans:0, hint:'秩<未知数个数→非零解'},
  {cat:'linalg', stem:'非齐次线性方程组Ax=b有解的充要条件是：', opts:['A. r(A)=r(A|b)','B. r(A)<r(A|b)','C. |A|≠0','D. b=0'], ans:0, hint:'系数矩阵与增广矩阵秩相等'},
  {cat:'linalg', stem:'实对称矩阵的特征值一定是：', opts:['A. 实数','B. 复数','C. 正数','D. 整数'], ans:0, hint:'实对称矩阵特征值都是实数'},
  {cat:'linalg', stem:'矩阵A的特征值之和等于：', opts:['A. A的迹(主对角线元素之和)','B. |A|','C. r(A)','D. 0'], ans:0, hint:'特征值之和=迹tr(A)'},
  {cat:'linalg', stem:'矩阵A的特征值之积等于：', opts:['A. |A|(行列式)','B. tr(A)','C. r(A)','D. n'], ans:0, hint:'特征值之积=行列式'},
  {cat:'linalg', stem:'正定矩阵的特征值满足：', opts:['A. 全为正数','B. 全为负数','C. 有正有负','D. 全为零'], ans:0, hint:'正定⇔特征值全正'},
  {cat:'linalg', stem:'矩阵的初等行变换不改变矩阵的：', opts:['A. 秩','B. 行列式','C. 特征值','D. 元素'], ans:0, hint:'初等变换保秩'},
  {cat:'linalg', stem:'克莱姆法则适用于：', opts:['A. 方程个数等于未知数个数且系数行列式不为零','B. 任意线性方程组','C. 齐次方程组','D. 欠定方程组'], ans:0, hint:'n×n且|A|≠0'},
  {cat:'linalg', stem:'矩阵A和B相似的充要条件不包括：', opts:['A. A和B有相同的特征值','B. A和B有相同的迹','C. A和B有相同的行列式','D. A和B有相同的元素'], ans:3, hint:'相似矩阵元素一般不同'},
  {cat:'linalg', stem:'正交矩阵Q满足：', opts:['A. Q^TQ=I','B. Q²=I','C. Q=Q^T','D. |Q|=0'], ans:0, hint:'正交矩阵转置=逆'},
  {cat:'linalg', stem:'向量空间的维数等于：', opts:['A. 基中向量的个数','B. 向量的分量数','C. 向量空间中向量的总数','D. 零向量的个数'], ans:0, hint:'维数=基的向量个数'},
  {cat:'linalg', stem:'施密特正交化的目的是：', opts:['A. 将线性无关的向量组正交化','B. 求特征值','C. 求行列式','D. 求逆矩阵'], ans:0, hint:'正交化=构造正交基'},
  {cat:'linalg', stem:'二次型f=x^TAx的矩阵A一定是：', opts:['A. 对称矩阵','B. 正交矩阵','C. 对角矩阵','D. 单位矩阵'], ans:0, hint:'二次型矩阵取对称形式'},
  {cat:'linalg', stem:'合同变换x=Cy可以将二次型化为标准形，其中C是：', opts:['A. 可逆矩阵','B. 正交矩阵','C. 对称矩阵','D. 零矩阵'], ans:0, hint:'合同变换用可逆矩阵'},
  {cat:'linalg', stem:'矩阵A的伴随矩阵A*满足：', opts:['A. AA*=|A|I','B. AA*=A','C. A*=A^(-1)','D. A*=A^T'], ans:0, hint:'AA*=|A|E'},
  {cat:'linalg', stem:'设A为n阶矩阵，kA的行列式|kA|=', opts:['A. k^n|A|','B. k|A|','C. |A|','D. k²|A|'], ans:0, hint:'提公因子n次'},
  {cat:'linalg', stem:'分块矩阵的转置规则是：', opts:['A. 将子块视为元素进行转置，同时各子块也转置','B. 只转置子块','C. 只交换子块位置','D. 不变'], ans:0, hint:'分块转置=位置+内部都转'},

  // ═══ 概率论与数理统计 ═══
  {cat:'prob', stem:'P(A∪B) = P(A)+P(B) 成立的条件是：', opts:['A. A,B互斥','B. A,B独立','C. A⊂B','D. 任意情况'], ans:0, hint:'互斥=不能同时发生'},
  {cat:'prob', stem:'A,B独立的充要条件是：', opts:['A. P(AB)=P(A)P(B)','B. P(A|B)=P(A|B̄)','C. P(A+B)=P(A)+P(B)','D. A和C都对'], ans:0, hint:'独立⇔乘法公式成立'},
  {cat:'prob', stem:'贝叶斯公式的核心思想是：', opts:['A. 利用先验信息和样本信息更新后验概率','B. 计算边缘概率','C. 独立性检验','D. 求期望'], ans:0, hint:'先验→后验'},
  {cat:'prob', stem:'全概率公式用于：', opts:['A. 已知原因求结果的概率','B. 已知结果求原因','C. 求期望值','D. 参数估计'], ans:0, hint:'全概率=因→果，贝叶斯=果→因'},
  {cat:'prob', stem:'连续型随机变量X的概率密度f(x)满足：', opts:['A. f(x)≥0且∫f(x)dx=1','B. f(x)可以为负','C. f(x)≤1','D. ∫f(x)dx可以不等于1'], ans:0, hint:'非负+归一'},
  {cat:'prob', stem:'标准正态分布N(0,1)的期望和方差分别为：', opts:['A. 0和1','B. 1和0','C. 0和0','D. 1和1'], ans:0, hint:'标准正态E=0, D=1'},
  {cat:'prob', stem:'泊松分布P(λ)的期望和方差都等于：', opts:['A. λ','B. λ²','C. 1/λ','D. √λ'], ans:0, hint:'泊松分布E=D=λ'},
  {cat:'prob', stem:'指数分布Exp(λ)的期望为：', opts:['A. 1/λ','B. λ','C. λ²','D. √λ'], ans:0, hint:'指数分布E=1/λ'},
  {cat:'prob', stem:'二项分布B(n,p)的期望E(X)=', opts:['A. np','B. n/p','C. p/n','D. n+p'], ans:0, hint:'二项分布E=np'},
  {cat:'prob', stem:'协方差Cov(X,Y)=0意味着：', opts:['A. X和Y不相关','B. X和Y独立','C. X和Y相等','D. X和Y同分布'], ans:0, hint:'不相关≠独立（正态例外）'},
  {cat:'prob', stem:'相关系数ρ的取值范围是：', opts:['A. [-1,1]','B. [0,1]','C. (-∞,+∞)','D. [0,+∞)'], ans:0, hint:'|ρ|≤1'},
  {cat:'prob', stem:'切比雪夫不等式P(|X-μ|≥ε)≤', opts:['A. σ²/ε²','B. ε/σ','C. σ/ε','D. ε²/σ²'], ans:0, hint:'切比雪夫不等式'},
  {cat:'prob', stem:'中心极限定理指出，大量独立同分布随机变量之和近似服从：', opts:['A. 正态分布','B. 泊松分布','C. 均匀分布','D. 指数分布'], ans:0, hint:'n足够大→正态'},
  {cat:'prob', stem:'大数定律的核心思想是：', opts:['A. 样本均值依概率收敛于总体期望','B. 样本方差趋于0','C. 频率趋于概率','D. A和C都对'], ans:3, hint:'大数定律=频率→概率=均值→期望'},
  {cat:'prob', stem:'矩估计法的基本思想是：', opts:['A. 用样本矩代替总体矩','B. 求似然函数的最大值','C. 最小化残差','D. 贝叶斯估计'], ans:0, hint:'矩估计=样本矩替代总体矩'},
  {cat:'prob', stem:'最大似然估计(MLE)的原理是：', opts:['A. 选择使样本出现概率最大的参数值','B. 选择使参数方差最小的值','C. 选择使偏差最小的值','D. 随机选择'], ans:0, hint:'MLE=最大化似然函数'},
  {cat:'prob', stem:'χ²分布的自由度为n，则它的期望为：', opts:['A. n','B. n²','C. 2n','D. n/2'], ans:0, hint:'χ²(n)的期望=n'},
  {cat:'prob', stem:'t分布的期望(自由度n>1时)为：', opts:['A. 0','B. 1','C. n','D. 1/n'], ans:0, hint:'t分布关于0对称'},
  {cat:'prob', stem:'假设检验中，第一类错误(α错误)是指：', opts:['A. 拒绝了正确的H₀','B. 接受了错误的H₀','C. 正确拒绝H₀','D. 正确接受H₀'], ans:0, hint:'弃真=第一类错误'},
  {cat:'prob', stem:'置信区间的置信度1-α越大，则区间：', opts:['A. 越宽','B. 越窄','C. 不变','D. 可能宽可能窄'], ans:0, hint:'置信度高→区间宽'},
  {cat:'prob', stem:'F分布F(n₁,n₂)中，n₁和n₂分别是：', opts:['A. 分子自由度和分母自由度','B. 均值和方差','C. 样本量','D. 总体参数'], ans:0, hint:'F=χ²₁/n₁ ÷ χ²₂/n₂'},

  // ═══ 补充题目 ═══
  {cat:'calculus', stem:'f(x)=|x|在x=0处：', opts:['A. 连续但不可导','B. 可导','C. 不连续','D. 可微'], ans:0, hint:'左导数=-1，右导数=1不等'},
  {cat:'calculus', stem:'定积分的中值定理：若f(x)在[a,b]连续，则存在ξ∈[a,b]使∫ₐᵇf(x)dx=', opts:['A. f(ξ)(b-a)','B. f\'(ξ)(b-a)','C. f(a)+f(b)','D. f(b)-f(a)'], ans:0, hint:'积分中值定理'},
  {cat:'calculus', stem:'函数f(x)=x·sin(1/x)在x=0处的极限为：', opts:['A. 0','B. 1','C. 不存在','D. ∞'], ans:0, hint:'夹逼准则：-|x|≤xsin(1/x)≤|x|'},
  {cat:'calculus', stem:'多元函数可微的充分条件是：', opts:['A. 偏导数存在且连续','B. 偏导数存在','C. 函数连续','D. 极限存在'], ans:0, hint:'偏导连续⇒可微'},
  {cat:'calculus', stem:'高斯公式(散度定理)将什么联系起来？', opts:['A. 曲面积分与三重积分','B. 曲线积分与二重积分','C. 定积分与不定积分','D. 级数与积分'], ans:0, hint:'Gauss公式=曲面→体积分'},
  {cat:'calculus', stem:'斯托克斯公式将什么联系起来？', opts:['A. 曲线积分与曲面积分','B. 二重积分与三重积分','C. 定积分与导数','D. 级数与积分'], ans:0, hint:'Stokes公式=曲线→曲面'},
  {cat:'linalg', stem:'矩阵A的特征多项式|λI-A|=0的根是A的：', opts:['A. 特征值','B. 秩','C. 逆矩阵','D. 行列式'], ans:0, hint:'特征方程的根=特征值'},
  {cat:'linalg', stem:'对角化条件：n阶矩阵A可对角化的充要条件是：', opts:['A. A有n个线性无关的特征向量','B. A的特征值互不相同','C. A是对称矩阵','D. B和C都是充分不必要条件'], ans:3, hint:'n个线性无关特征向量⇔可对角化'},
  {cat:'linalg', stem:'设A是m×n矩阵，则Ax=0的解空间的维数为：', opts:['A. n-r(A)','B. m-r(A)','C. r(A)','D. n'], ans:0, hint:'基础解系维数=n-r'},
  {cat:'linalg', stem:'行列式的性质：交换两行，行列式：', opts:['A. 变号','B. 不变','C. 变为0','D. 变为绝对值'], ans:0, hint:'换行变号'},
  {cat:'prob', stem:'条件概率P(A|B)=', opts:['A. P(AB)/P(B)','B. P(A)/P(B)','C. P(A)P(B)','D. P(A+B)'], ans:0, hint:'条件概率公式'},
  {cat:'prob', stem:'随机变量X~N(μ,σ²)，则(X-μ)/σ服从：', opts:['A. N(0,1)','B. N(μ,1)','C. N(0,σ²)','D. χ²(1)'], ans:0, hint:'标准化'},
  {cat:'prob', stem:'判断估计量优劣的标准不包括：', opts:['A. 无偏性','B. 有效性','C. 一致性','D. 美观性'], ans:3, hint:'估计量的三个标准'},
  {cat:'prob', stem:'样本方差S²是总体方差σ²的：', opts:['A. 无偏估计','B. 有偏估计','C. 最大估计','D. 最小估计'], ans:0, hint:'S²=Σ(Xi-X̄)²/(n-1)无偏'},
  {cat:'prob', stem:'二维正态分布中，X和Y不相关与独立的关系是：', opts:['A. 等价(不相关⇔独立)','B. 独立⇒不相关但反之不成立','C. 不相关⇒独立但反之不成立','D. 两者无关'], ans:0, hint:'正态分布下不相关⇔独立'},

  // ═══ 更多补充 ═══
  {cat:'calculus', stem:'函数f(x)=x²-2x+1的最小值是：', opts:['A. 0','B. 1','C. -1','D. 2'], ans:0, hint:'配方：(x-1)²的最小值=0'},
  {cat:'calculus', stem:'两个无穷小的商：', opts:['A. 可能是常数、无穷小或无穷大','B. 一定是无穷小','C. 一定是0','D. 一定是1'], ans:0, hint:'0/0型，结果不定'},
  {cat:'calculus', stem:'若f(x)的导函数f\'(x)在区间内恒正，则f(x)在该区间：', opts:['A. 单调递增','B. 单调递减','C. 有极值','D. 不确定'], ans:0, hint:'f\'>0⇒递增'},
  {cat:'calculus', stem:'不定积分∫cos(x)dx=', opts:['A. sin(x)+C','B. -sin(x)+C','C. cos(x)+C','D. tan(x)+C'], ans:0, hint:'cos积分=sin'},
  {cat:'calculus', stem:'∫₀^∞ e^(-x) dx=', opts:['A. 1','B. 0','C. ∞','D. e'], ans:0, hint:'-e^(-x)从0到∞=0-(-1)=1'},
  {cat:'calculus', stem:'若∫ₐᵇf(x)dx=0，则：', opts:['A. f(x)不一定恒等于0','B. f(x)恒等于0','C. f(x)<0','D. f(x)>0'], ans:0, hint:'正负相消也可使积分为0'},
  {cat:'calculus', stem:'多元函数的极值存在的充分条件（二阶条件）：AC-B²>0且A>0，其中A=fxx, B=fxy, C=fyy，则该点是：', opts:['A. 极小值','B. 极大值','C. 鞍点','D. 不确定'], ans:0, hint:'AC-B²>0,A>0→极小'},
  {cat:'calculus', stem:'拉格朗日乘数法用于求解：', opts:['A. 条件极值问题','B. 无约束极值','C. 定积分','D. 微分方程'], ans:0, hint:'有约束条件的极值'},
  {cat:'calculus', stem:'傅里叶级数展开的核心性质是利用三角函数的：', opts:['A. 正交性','B. 周期性','C. 有界性','D. 单调性'], ans:0, hint:'三角函数系正交'},
  {cat:'linalg', stem:'若A是可逆矩阵，则A^(-1)的行列式|A^(-1)|=', opts:['A. 1/|A|','B. |A|','C. -|A|','D. |A|²'], ans:0, hint:'|A^(-1)|=1/|A|'},
  {cat:'linalg', stem:'矩阵A的转置A^T满足(AB)^T=', opts:['A. B^T·A^T','B. A^T·B^T','C. (AB)','D. B·A'], ans:0, hint:'转置倒序'},
  {cat:'linalg', stem:'向量组的秩等于：', opts:['A. 极大线性无关组中向量的个数','B. 向量的维数','C. 向量的个数','D. 零向量的个数'], ans:0, hint:'秩=极大无关组的元素个数'},
  {cat:'prob', stem:'设X~U(a,b)(均匀分布)，则E(X)=', opts:['A. (a+b)/2','B. a+b','C. ab','D. (b-a)/2'], ans:0, hint:'均匀分布期望=(a+b)/2'},
  {cat:'prob', stem:'方差D(X)的性质：D(aX+b)=', opts:['A. a²D(X)','B. aD(X)+b','C. a²D(X)+b²','D. D(X)'], ans:0, hint:'常数不影响方差，系数平方'},
  {cat:'prob', stem:'联合分布函数F(x,y)与边缘分布的关系：F_X(x)=', opts:['A. F(x,+∞)','B. F(x,0)','C. F(+∞,x)','D. F(0,x)'], ans:0, hint:'y→+∞得X的边缘分布'},
  {cat:'prob', stem:'若E(X)=μ，则E(X²)=', opts:['A. D(X)+μ²','B. D(X)','C. μ²','D. D(X)-μ²'], ans:0, hint:'D(X)=E(X²)-[E(X)]²'},

  // ═══ 第三批补充 ═══
  {cat:'calculus', stem:'函数y=arctan(x)的导数y\'=', opts:['A. 1/(1+x²)','B. 1/√(1-x²)','C. -1/(1+x²)','D. x/(1+x²)'], ans:0, hint:'反正切导数'},
  {cat:'calculus', stem:'函数y=arcsin(x)的导数y\'=', opts:['A. 1/√(1-x²)','B. 1/(1+x²)','C. -1/√(1-x²)','D. 1/x'], ans:0, hint:'反正弦导数'},
  {cat:'calculus', stem:'n次多项式最多有几个实根？', opts:['A. n个','B. n-1个','C. n+1个','D. 无穷多个'], ans:0, hint:'代数基本定理'},
  {cat:'calculus', stem:'若f(x)在[a,b]上连续且f(a)·f(b)<0，则存在：', opts:['A. ξ∈(a,b)使f(ξ)=0','B. f(x)处处为零','C. f(x)不变号','D. 无解'], ans:0, hint:'零点定理'},
  {cat:'calculus', stem:'柯西中值定理：[f(b)-f(a)]/[g(b)-g(a)]=', opts:['A. f\'(ξ)/g\'(ξ)','B. f(ξ)/g(ξ)','C. f\'(a)/g\'(a)','D. [f(a)+f(b)]/[g(a)+g(b)]'], ans:0, hint:'柯西中值定理'},
  {cat:'linalg', stem:'若方阵A满足A²=A，则A的特征值只可能是：', opts:['A. 0或1','B. 1或-1','C. 0或-1','D. 任意实数'], ans:0, hint:'λ²=λ⇒λ=0或1'},
  {cat:'linalg', stem:'设A为n阶矩阵，则r(A)≤min(m,n)对于m×n矩阵成立，这说明：', opts:['A. 秩不超过行数和列数的较小值','B. 秩等于行数','C. 秩等于列数','D. 秩等于元素个数'], ans:0, hint:'秩≤min(行数,列数)'},
  {cat:'linalg', stem:'矩阵的秩=1，则矩阵可以表示为：', opts:['A. 一个列向量与一个行向量的乘积','B. 两个矩阵之和','C. 单位矩阵','D. 对角矩阵'], ans:0, hint:'秩1矩阵=αβ^T'},
  {cat:'prob', stem:'0-1分布(伯努利分布)B(1,p)的方差D(X)=', opts:['A. p(1-p)','B. p','C. p²','D. 1-p'], ans:0, hint:'D=npq=p(1-p)'},
  {cat:'prob', stem:'几何分布P(X=k)=(1-p)^(k-1)·p的期望E(X)=', opts:['A. 1/p','B. p','C. 1-p','D. p/(1-p)'], ans:0, hint:'几何分布E=1/p'},
  {cat:'prob', stem:'样本均值X̄的期望E(X̄)=', opts:['A. μ(总体均值)','B. σ²','C. μ/n','D. nμ'], ans:0, hint:'X̄是μ的无偏估计'},
  {cat:'prob', stem:'正态总体的样本均值X̄服从什么分布？', opts:['A. N(μ, σ²/n)','B. N(μ, σ²)','C. N(0, 1)','D. t分布'], ans:0, hint:'X̄~N(μ, σ²/n)'},
  {cat:'prob', stem:'事件A的对立事件Ā满足P(Ā)=', opts:['A. 1-P(A)','B. P(A)','C. 1/P(A)','D. -P(A)'], ans:0, hint:'互补事件概率之和=1'},
  {cat:'prob', stem:'随机事件的三种运算关系：并、交、差，其中A-B等价于：', opts:['A. A∩B̄','B. A∪B̄','C. Ā∩B','D. A∪B'], ans:0, hint:'A-B=A交B的补'},

  // ═══ 第四批 · 高数补充 ═══
  {cat:'calculus', stem:'(tan x)\' 等于：', opts:['A. sec²x','B. csc²x','C. -sec²x','D. sin²x'], ans:0, hint:'tanx导数=sec²x'},
  {cat:'calculus', stem:'(cot x)\' 等于：', opts:['A. -csc²x','B. sec²x','C. csc²x','D. -sec²x'], ans:0, hint:'cotx导数=-csc²x'},
  {cat:'calculus', stem:'(sec x)\' 等于：', opts:['A. sec x·tan x','B. -csc x·cot x','C. sec²x','D. cos x'], ans:0, hint:'secx导数=secx·tanx'},
  {cat:'calculus', stem:'∫sec²x dx =', opts:['A. tan x + C','B. sec x + C','C. sin x + C','D. cot x + C'], ans:0, hint:'sec²x积分=tanx'},
  {cat:'calculus', stem:'∫1/√(1-x²) dx =', opts:['A. arcsin x + C','B. arctan x + C','C. arccos x + C','D. ln|x| + C'], ans:0, hint:'1/√(1-x²)→arcsin'},
  {cat:'calculus', stem:'∫1/(1+x²) dx =', opts:['A. arctan x + C','B. arcsin x + C','C. ln(1+x²) + C','D. 1/x + C'], ans:0, hint:'1/(1+x²)→arctan'},
  {cat:'calculus', stem:'∫x·eˣ dx 用分部积分法等于：', opts:['A. (x-1)eˣ + C','B. xeˣ + C','C. (x+1)eˣ + C','D. x²eˣ/2 + C'], ans:0, hint:'u=x,dv=eˣdx→xeˣ-eˣ'},
  {cat:'calculus', stem:'∫ln x dx =', opts:['A. x·ln x - x + C','B. 1/x + C','C. x·ln x + C','D. ln x/x + C'], ans:0, hint:'分部积分u=lnx'},
  {cat:'calculus', stem:'不定积分∫sin²x dx =', opts:['A. x/2 - sin(2x)/4 + C','B. -cos²x + C','C. sin x·cos x + C','D. x - sin x + C'], ans:0, hint:'降幂公式sin²x=(1-cos2x)/2'},
  {cat:'calculus', stem:'∫₀^π sin x dx =', opts:['A. 2','B. 0','C. π','D. 1'], ans:0, hint:'-cosx从0到π=-(-1)-(-1)=2'},
  {cat:'calculus', stem:'设y=x^x(x>0)，则y\' =', opts:['A. x^x(ln x + 1)','B. x·x^(x-1)','C. x^x·ln x','D. x^(x-1)'], ans:0, hint:'对数微分法：lny=xlnx'},
  {cat:'calculus', stem:'复合函数求导的链式法则：[f(g(x))]\' =', opts:['A. f\'(g(x))·g\'(x)','B. f\'(x)·g\'(x)','C. f(g\'(x))','D. f\'(g(x))'], ans:0, hint:'链式法则=外导×内导'},
  {cat:'calculus', stem:'函数f(x)=eˣ-x-1在x=0处的泰勒展开第一个非零余项是：', opts:['A. x²/2','B. x','C. 1','D. x³/6'], ans:0, hint:'eˣ-x-1≈x²/2(x→0)'},
  {cat:'calculus', stem:'曲线y=f(x)的渐近线不包括：', opts:['A. 水平渐近线','B. 垂直渐近线','C. 斜渐近线','D. 圆形渐近线'], ans:3, hint:'三种渐近线：水平、垂直、斜'},
  {cat:'calculus', stem:'水平渐近线的求法是：', opts:['A. 求x→±∞时f(x)的极限','B. 求f\'(x)=0','C. 求f(0)','D. 求f\'\'(x)=0'], ans:0, hint:'lim(x→±∞)f(x)=L→y=L'},
  {cat:'calculus', stem:'弧长公式s=∫ₐᵇ√(1+y\'²) dx 用于计算：', opts:['A. 曲线的弧长','B. 曲线围成的面积','C. 旋转体体积','D. 曲面面积'], ans:0, hint:'弧长=∫√(1+y\'²)dx'},
  {cat:'calculus', stem:'绕x轴旋转体体积公式V=π∫ₐᵇ y² dx适用于：', opts:['A. 求曲线y=f(x)绕x轴旋转所得旋转体体积','B. 求面积','C. 求弧长','D. 求质心'], ans:0, hint:'盘片法'},
  {cat:'calculus', stem:'三重积分∫∫∫_Ω f(x,y,z) dV在球坐标系下dV=', opts:['A. r²sinφ dr dφ dθ','B. r dr dθ dz','C. dx dy dz','D. r dr dθ'], ans:0, hint:'球坐标体积元'},
  {cat:'calculus', stem:'柱坐标系下体积元dV=', opts:['A. r dr dθ dz','B. r²sinφ dr dφ dθ','C. dx dy dz','D. r² dr dθ'], ans:0, hint:'柱坐标体积元'},
  {cat:'calculus', stem:'第一类曲线积分∫_L f(x,y) ds的几何意义是：', opts:['A. 以f为线密度的曲线质量','B. 面积','C. 体积','D. 长度'], ans:0, hint:'ds=弧长元素→质量'},
  {cat:'calculus', stem:'第二类曲线积分∫_L P dx + Q dy与方向有关吗？', opts:['A. 有关，方向相反则变号','B. 无关','C. 只与P有关','D. 只与Q有关'], ans:0, hint:'第二类曲线积分与方向有关'},
  {cat:'calculus', stem:'曲线积分与路径无关的充要条件(保守场)是：', opts:['A. ∂P/∂y = ∂Q/∂x','B. P=Q','C. P+Q=0','D. P·Q=0'], ans:0, hint:'全微分条件'},
  {cat:'calculus', stem:'散度div F = ∇·F 的物理意义是：', opts:['A. 源(汇)的强度','B. 旋涡强度','C. 流速','D. 压力'], ans:0, hint:'散度=通量密度'},
  {cat:'calculus', stem:'旋度curl F = ∇×F 的物理意义是：', opts:['A. 旋涡的强度和方向','B. 源的强度','C. 流量','D. 压力梯度'], ans:0, hint:'旋度=环量密度'},
  {cat:'calculus', stem:'一阶线性方程y\'+P(x)y=Q(x)的通解公式含：', opts:['A. 积分因子e^(∫P dx)','B. 特征方程','C. 级数展开','D. 拉普拉斯变换'], ans:0, hint:'积分因子法'},
  {cat:'calculus', stem:'常数变易法用于求：', opts:['A. 非齐次线性方程的特解','B. 齐次方程的通解','C. 特征方程','D. 级数和'], ans:0, hint:'常数变易法→非齐次特解'},
  {cat:'calculus', stem:'欧拉方程x²y\'\'+ axy\' + by = 0的解法是：', opts:['A. 令x=eᵗ变为常系数方程','B. 分离变量','C. 直接积分','D. 级数解'], ans:0, hint:'x=eᵗ变换'},
  {cat:'calculus', stem:'正项级数∑aₙ(aₙ≥0)收敛的充要条件是：', opts:['A. 部分和数列有界','B. aₙ→0','C. aₙ单调递减','D. aₙ有界'], ans:0, hint:'部分和有界⇔正项级数收敛'},
  {cat:'calculus', stem:'比值判别法(达朗贝尔判别法)：若lim(aₙ₊₁/aₙ)=L，则L<1时级数：', opts:['A. 收敛','B. 发散','C. 不确定','D. 条件收敛'], ans:0, hint:'L<1收敛，L>1发散'},
  {cat:'calculus', stem:'根值判别法(柯西判别法)：若lim(aₙ^(1/n))=L，则L<1时级数：', opts:['A. 收敛','B. 发散','C. 不确定','D. 条件收敛'], ans:0, hint:'L<1收敛'},
  {cat:'calculus', stem:'绝对收敛与条件收敛的关系：', opts:['A. 绝对收敛⇒收敛，但反之不一定','B. 条件收敛⇒绝对收敛','C. 两者等价','D. 两者无关'], ans:0, hint:'绝对收敛⇒收敛'},
  {cat:'calculus', stem:'1/(1-x)的麦克劳林展开(|x|<1)=', opts:['A. 1+x+x²+x³+...','B. 1-x+x²-x³+...','C. x+x²/2+x³/3+...','D. 1+x/2+x²/4+...'], ans:0, hint:'几何级数'},
  {cat:'calculus', stem:'ln(1+x)的麦克劳林展开(-1<x≤1)=', opts:['A. x-x²/2+x³/3-x⁴/4+...','B. 1+x+x²/2!+...','C. x+x²/2+x³/3+...','D. 1-x+x²-x³+...'], ans:0, hint:'ln(1+x)交错级数'},
  {cat:'calculus', stem:'(1+x)^α的麦克劳林展开第二项是：', opts:['A. αx','B. x','C. α','D. x²'], ans:0, hint:'二项级数第二项=αx'},
  {cat:'calculus', stem:'函数展开为傅里叶级数时，奇函数只含：', opts:['A. 正弦项','B. 余弦项','C. 常数项','D. 正弦和余弦'], ans:0, hint:'奇函数→正弦级数'},
  {cat:'calculus', stem:'函数展开为傅里叶级数时，偶函数只含：', opts:['A. 余弦项','B. 正弦项','C. 常数项和正弦','D. 没有规律'], ans:0, hint:'偶函数→余弦级数'},
  {cat:'calculus', stem:'微分方程的阶数是指：', opts:['A. 方程中出现的最高阶导数的阶数','B. 未知函数的个数','C. 独立变量的个数','D. 方程的项数'], ans:0, hint:'最高阶导数的阶'},
  {cat:'calculus', stem:'一阶全微分方程M(x,y)dx+N(x,y)dy=0是全微分方程的条件是：', opts:['A. ∂M/∂y = ∂N/∂x','B. M=N','C. M+N=0','D. M·N=0'], ans:0, hint:'恰当方程条件'},
  {cat:'calculus', stem:'方向导数∂f/∂l的计算公式涉及：', opts:['A. 梯度与方向向量的内积','B. 偏导数之差','C. 偏导数之积','D. 全微分'], ans:0, hint:'方向导数=grad f · l/|l|'},
  {cat:'calculus', stem:'隐函数存在定理中，F(x,y)=0确定y=y(x)的条件之一是：', opts:['A. Fy≠0','B. Fx=0','C. F=0','D. Fy=0'], ans:0, hint:'Fy≠0保证y可解'},
  {cat:'calculus', stem:'雅可比行列式在多元积分换元中的作用是：', opts:['A. 计算面积/体积元素的变换系数','B. 求极值','C. 求特征值','D. 求方程的解'], ans:0, hint:'Jacobian=换元系数'},

  // ═══ 第五批 · 线代补充 ═══
  {cat:'linalg', stem:'矩阵A的逆矩阵A⁻¹的计算方法不包括：', opts:['A. 伴随矩阵法','B. 初等变换法','C. 求导法','D. 分块矩阵法'], ans:2, hint:'求导不能求逆矩阵'},
  {cat:'linalg', stem:'若A为m×n矩阵，B为n×p矩阵，则AB的列数为：', opts:['A. p','B. m','C. n','D. m+p'], ans:0, hint:'AB的大小=m×p'},
  {cat:'linalg', stem:'矩阵乘法满足交换律吗？', opts:['A. 一般不满足','B. 总是满足','C. 只有方阵满足','D. 只有对称矩阵满足'], ans:0, hint:'AB≠BA(一般情况)'},
  {cat:'linalg', stem:'矩阵乘法满足结合律吗？', opts:['A. 满足(AB)C=A(BC)','B. 不满足','C. 有时满足','D. 只有方阵满足'], ans:0, hint:'结合律成立'},
  {cat:'linalg', stem:'行列式的展开定理：可以按任一行(列)展开，公式中需要：', opts:['A. 代数余子式','B. 余子式','C. 伴随矩阵','D. 逆矩阵'], ans:0, hint:'行列式=Σaij·Aij'},
  {cat:'linalg', stem:'范德蒙德行列式的值为：', opts:['A. 所有(xj-xi)的乘积(j>i)','B. 0','C. 1','D. 对角线元素之积'], ans:0, hint:'∏(xj-xi),j>i'},
  {cat:'linalg', stem:'若两行(列)成比例，则行列式：', opts:['A. 等于0','B. 等于1','C. 不变','D. 变号'], ans:0, hint:'成比例→行列式=0'},
  {cat:'linalg', stem:'若行列式某行(列)都是0，则行列式：', opts:['A. 等于0','B. 等于1','C. 不确定','D. 等于-1'], ans:0, hint:'全零行→|A|=0'},
  {cat:'linalg', stem:'A^T·A是什么类型的矩阵？', opts:['A. 半正定对称矩阵','B. 反对称矩阵','C. 正交矩阵','D. 零矩阵'], ans:0, hint:'A^TA对称且半正定'},
  {cat:'linalg', stem:'若A是幂等矩阵(A²=A)，则I-A也是幂等矩阵吗？', opts:['A. 是','B. 不是','C. 不确定','D. 只有A=I时'], ans:0, hint:'(I-A)²=I-2A+A²=I-2A+A=I-A'},
  {cat:'linalg', stem:'若A是正交矩阵，则|A|=', opts:['A. ±1','B. 0','C. 1','D. -1'], ans:0, hint:'Q^TQ=I→|Q|²=1→|Q|=±1'},
  {cat:'linalg', stem:'实对称矩阵属于不同特征值的特征向量一定：', opts:['A. 正交','B. 平行','C. 线性相关','D. 相等'], ans:0, hint:'实对称矩阵→不同特征值→正交'},
  {cat:'linalg', stem:'Jordan标准形用于什么情况？', opts:['A. 矩阵不可对角化时的简化形式','B. 可逆矩阵的求逆','C. 求行列式','D. 解方程组'], ans:0, hint:'不可对角化→Jordan形'},
  {cat:'linalg', stem:'凯莱-哈密顿定理说的是：', opts:['A. 矩阵满足自己的特征多项式','B. 矩阵的秩等于维数','C. 所有矩阵可逆','D. 矩阵可对角化'], ans:0, hint:'f(A)=0，f是A的特征多项式'},
  {cat:'linalg', stem:'矩阵A的谱半径ρ(A)是指：', opts:['A. 最大特征值的绝对值','B. 最小特征值','C. 特征值之和','D. 行列式'], ans:0, hint:'ρ(A)=max|λi|'},
  {cat:'linalg', stem:'惯性定理说的是：', opts:['A. 二次型经过非退化线性变换后正负惯性指数不变','B. 矩阵秩不变','C. 行列式不变','D. 特征值不变'], ans:0, hint:'正负惯性指数不随变换改变'},
  {cat:'linalg', stem:'负定矩阵的顺序主子式满足：', opts:['A. 奇数阶<0，偶数阶>0','B. 全部>0','C. 全部<0','D. 全部=0'], ans:0, hint:'负定=交替变号，首项<0'},
  {cat:'linalg', stem:'矩阵的迹tr(AB)=', opts:['A. tr(BA)','B. tr(A)·tr(B)','C. 0','D. |A|·|B|'], ans:0, hint:'迹的交换不变性'},
  {cat:'linalg', stem:'向量的内积(点积)a·b=|a||b|cosθ，当θ=90°时：', opts:['A. a·b=0','B. a·b=|a||b|','C. a·b=-|a||b|','D. 未定义'], ans:0, hint:'正交⇔内积=0'},
  {cat:'linalg', stem:'向量的叉积(外积)a×b的方向由什么决定？', opts:['A. 右手定则','B. 左手定则','C. 点积方向','D. 任意方向'], ans:0, hint:'右手定则'},
  {cat:'linalg', stem:'r(A+B)与r(A)、r(B)的关系是：', opts:['A. r(A+B)≤r(A)+r(B)','B. r(A+B)=r(A)+r(B)','C. r(A+B)≥r(A)+r(B)','D. 无法确定'], ans:0, hint:'秩的次可加性'},
  {cat:'linalg', stem:'r(AB)与r(A)、r(B)的关系是：', opts:['A. r(AB)≤min{r(A),r(B)}','B. r(AB)=r(A)·r(B)','C. r(AB)≥r(A)+r(B)','D. r(AB)=r(A)+r(B)'], ans:0, hint:'乘积秩不超过因子秩'},
  {cat:'linalg', stem:'矩阵的LU分解是将A分解为：', opts:['A. 下三角矩阵L和上三角矩阵U的乘积','B. 对称矩阵之积','C. 正交矩阵之积','D. 对角矩阵之积'], ans:0, hint:'L=下三角，U=上三角'},
  {cat:'linalg', stem:'若A为n阶矩阵且A^k=O(零矩阵)，则A称为：', opts:['A. 幂零矩阵','B. 幂等矩阵','C. 正交矩阵','D. 对称矩阵'], ans:0, hint:'A^k=O→幂零'},
  {cat:'linalg', stem:'线性变换T(αx+βy)=αT(x)+βT(y)满足的性质叫：', opts:['A. 线性性(齐次性+可加性)','B. 连续性','C. 可微性','D. 有界性'], ans:0, hint:'线性=齐次+可加'},

  // ═══ 第六批 · 概率论补充 ═══
  {cat:'prob', stem:'古典概型的特点是：', opts:['A. 样本空间有限且等可能','B. 样本空间无限','C. 不等可能','D. 连续型'], ans:0, hint:'有限等可能=古典概型'},
  {cat:'prob', stem:'几何概型的特点是：', opts:['A. 样本空间连续且等可能(以面积/体积衡量)','B. 样本空间有限','C. 离散型','D. 不等可能'], ans:0, hint:'连续等可能=几何概型'},
  {cat:'prob', stem:'容斥原理P(A∪B)=', opts:['A. P(A)+P(B)-P(AB)','B. P(A)+P(B)','C. P(A)P(B)','D. P(A)-P(B)'], ans:0, hint:'容斥公式'},
  {cat:'prob', stem:'条件独立和独立的关系是：', opts:['A. 两者没有必然联系','B. 独立⇒条件独立','C. 条件独立⇒独立','D. 两者等价'], ans:0, hint:'独立与条件独立无必然关系'},
  {cat:'prob', stem:'离散型随机变量的分布律Σpk=', opts:['A. 1','B. 0','C. ∞','D. pk'], ans:0, hint:'归一性'},
  {cat:'prob', stem:'连续型随机变量在某一点的概率P(X=a)=', opts:['A. 0','B. f(a)','C. F(a)','D. 1'], ans:0, hint:'连续型在一点概率=0'},
  {cat:'prob', stem:'分布函数F(x)的性质不包括：', opts:['A. 单调不减','B. F(-∞)=0','C. F(+∞)=1','D. F(x)可以大于1'], ans:3, hint:'0≤F(x)≤1'},
  {cat:'prob', stem:'均匀分布U(a,b)的方差D(X)=', opts:['A. (b-a)²/12','B. (b-a)/2','C. (a+b)/2','D. (b-a)²'], ans:0, hint:'均匀分布方差=(b-a)²/12'},
  {cat:'prob', stem:'正态分布的3σ原则：P(|X-μ|<3σ)≈', opts:['A. 99.73%','B. 95%','C. 68%','D. 50%'], ans:0, hint:'3σ≈99.73%'},
  {cat:'prob', stem:'正态分布的2σ原则：P(|X-μ|<2σ)≈', opts:['A. 95.45%','B. 99.73%','C. 68.27%','D. 50%'], ans:0, hint:'2σ≈95.45%'},
  {cat:'prob', stem:'正态分布的1σ原则：P(|X-μ|<σ)≈', opts:['A. 68.27%','B. 95.45%','C. 99.73%','D. 50%'], ans:0, hint:'1σ≈68.27%'},
  {cat:'prob', stem:'超几何分布适用于：', opts:['A. 不放回抽样','B. 放回抽样','C. 连续型随机变量','D. 指数衰减'], ans:0, hint:'不放回→超几何'},
  {cat:'prob', stem:'负二项分布(帕斯卡分布)描述的是：', opts:['A. 第r次成功所需的试验次数','B. n次试验中的成功次数','C. 首次成功的等待时间','D. 到达率'], ans:0, hint:'第r次成功→负二项'},
  {cat:'prob', stem:'期望E(X)的性质：E(aX+bY)=', opts:['A. aE(X)+bE(Y)','B. E(X)·E(Y)','C. a+b','D. abE(XY)'], ans:0, hint:'期望的线性性'},
  {cat:'prob', stem:'若X,Y独立，则E(XY)=', opts:['A. E(X)·E(Y)','B. E(X)+E(Y)','C. E(X)-E(Y)','D. 0'], ans:0, hint:'独立⇒E(XY)=E(X)E(Y)'},
  {cat:'prob', stem:'Cov(X,Y)的计算公式=', opts:['A. E(XY)-E(X)E(Y)','B. E(X)E(Y)','C. E(X+Y)','D. D(X)D(Y)'], ans:0, hint:'协方差公式'},
  {cat:'prob', stem:'若X,Y独立，则D(X+Y)=', opts:['A. D(X)+D(Y)','B. D(X)·D(Y)','C. D(X)-D(Y)','D. 0'], ans:0, hint:'独立⇒方差可加'},
  {cat:'prob', stem:'D(X-Y)与D(X+Y)的关系(X,Y独立时)：', opts:['A. D(X-Y)=D(X+Y)=D(X)+D(Y)','B. D(X-Y)=D(X)-D(Y)','C. D(X-Y)=0','D. 不确定'], ans:0, hint:'独立时D(X±Y)=D(X)+D(Y)'},
  {cat:'prob', stem:'相关系数ρ(X,Y)=1表示：', opts:['A. X与Y之间存在完全正线性关系','B. X=Y','C. X与Y独立','D. X与Y无关'], ans:0, hint:'ρ=1→完全正线性相关'},
  {cat:'prob', stem:'随机变量函数Y=g(X)的期望E(Y)=', opts:['A. ∫g(x)f(x)dx (连续型)','B. g(E(X))','C. E(X)','D. g(0)'], ans:0, hint:'E(g(X))≠g(E(X))'},
  {cat:'prob', stem:'χ²分布的可加性：χ²(n₁)+χ²(n₂)=', opts:['A. χ²(n₁+n₂)','B. χ²(n₁·n₂)','C. F分布','D. t分布'], ans:0, hint:'χ²可加'},
  {cat:'prob', stem:'t分布在n→∞时趋近于：', opts:['A. 标准正态分布N(0,1)','B. χ²分布','C. F分布','D. 均匀分布'], ans:0, hint:'t(∞)→N(0,1)'},
  {cat:'prob', stem:'F分布F(n₁,n₂)与F(n₂,n₁)的关系：', opts:['A. F(n₁,n₂)=1/F(n₂,n₁)','B. 相等','C. 无关','D. 互为相反数'], ans:0, hint:'F互为倒数'},
  {cat:'prob', stem:'充分统计量的定义是：', opts:['A. 包含样本中关于参数的全部信息','B. 最简单的统计量','C. 方差最小的统计量','D. 偏差最小的统计量'], ans:0, hint:'充分统计量=全部信息'},
  {cat:'prob', stem:'有效估计(最小方差无偏估计)的含义是：', opts:['A. 在所有无偏估计中方差最小','B. 偏差最小','C. 计算最简单','D. 收敛最快'], ans:0, hint:'MVUE=最小方差无偏'},
  {cat:'prob', stem:'单侧假设检验H₀:μ≤μ₀ vs H₁:μ>μ₀的拒绝域在：', opts:['A. 右侧','B. 左侧','C. 两侧','D. 中间'], ans:0, hint:'H₁:μ>μ₀→右侧检验'},
  {cat:'prob', stem:'第二类错误(β错误)是指：', opts:['A. 接受了错误的H₀','B. 拒绝了正确的H₀','C. 正确拒绝H₀','D. 正确接受H₀'], ans:0, hint:'取伪=第二类错误'},
  {cat:'prob', stem:'一元线性回归模型Y=β₀+β₁X+ε中，ε满足：', opts:['A. E(ε)=0, D(ε)=σ²','B. E(ε)=1','C. ε=0','D. ε是常数'], ans:0, hint:'误差项零均值等方差'},
  {cat:'prob', stem:'最小二乘法的原理是：', opts:['A. 使残差平方和最小','B. 使残差绝对值和最小','C. 使残差最大值最小','D. 使参数最大'], ans:0, hint:'min Σ(yi-ŷi)²'},
  {cat:'prob', stem:'决定系数R²的取值范围是：', opts:['A. [0,1]','B. [-1,1]','C. [0,∞)','D. (-∞,+∞)'], ans:0, hint:'R²∈[0,1]，越大拟合越好'},
  {cat:'prob', stem:'样本均值X̄的方差D(X̄)=', opts:['A. σ²/n','B. σ²','C. nσ²','D. σ/n'], ans:0, hint:'D(X̄)=σ²/n'},
  {cat:'prob', stem:'矩母函数(矩生成函数)M(t)=E(eᵗˣ)的用途是：', opts:['A. 求各阶矩和判断分布','B. 只能求均值','C. 只能求方差','D. 画图'], ans:0, hint:'MGF确定分布+求矩'},

  // ═══ 更多高数 ═══
  {cat:'calculus', stem:'∫₀¹ x·ln x dx =', opts:['A. -1/4','B. 1/4','C. 0','D. -1/2'], ans:0, hint:'分部积分后计算'},
  {cat:'calculus', stem:'级数∑1/n!的和等于：', opts:['A. e-1','B. e','C. 1','D. ∞'], ans:0, hint:'eˣ在x=1时展开=e'},
  {cat:'calculus', stem:'∫₀^∞ x·e^(-x) dx =', opts:['A. 1','B. 0','C. ∞','D. e'], ans:0, hint:'Γ(2)=1!=1'},
  {cat:'calculus', stem:'Γ函数Γ(n+1)=', opts:['A. n!','B. n','C. (n+1)!','D. 1/n'], ans:0, hint:'Γ(n+1)=n!'},
  {cat:'calculus', stem:'Beta函数B(p,q)与Γ函数的关系是：', opts:['A. B(p,q)=Γ(p)Γ(q)/Γ(p+q)','B. B(p,q)=Γ(p+q)','C. B(p,q)=p·q','D. B(p,q)=1'], ans:0, hint:'B=ΓΓ/Γ'},
  {cat:'calculus', stem:'∫₋∞^∞ e^(-x²) dx =', opts:['A. √π','B. π','C. 1','D. 2π'], ans:0, hint:'高斯积分=√π'},
  {cat:'calculus', stem:'向量值函数r(t)=(x(t),y(t),z(t))的导数r\'(t)的几何意义是：', opts:['A. 曲线的切线方向向量','B. 法线方向','C. 曲率','D. 挠率'], ans:0, hint:'r\'(t)=切线方向'},
  {cat:'calculus', stem:'空间曲线的曲率κ和挠率τ完全确定了：', opts:['A. 曲线的形状(在等距变换意义下)','B. 曲线的位置','C. 曲线的方程','D. 曲线的参数'], ans:0, hint:'曲率+挠率→基本定理'},
  {cat:'calculus', stem:'偏导数f_x(a,b)的几何意义是：', opts:['A. 曲面z=f(x,y)在平行于xOz平面的截面的切线斜率','B. 法线斜率','C. 面积','D. 体积'], ans:0, hint:'固定y=b时的斜率'},
  {cat:'calculus', stem:'二元函数连续、偏导存在、可微三者的关系：', opts:['A. 可微⇒连续且偏导存在，但反之不一定','B. 三者等价','C. 连续⇒可微','D. 偏导存在⇒连续'], ans:0, hint:'可微⇒连续+偏导存在'},

  // ═══ 更多线代 ═══
  {cat:'linalg', stem:'非齐次线性方程组Ax=b的通解=', opts:['A. 对应齐次方程组通解 + 一个特解','B. 只含特解','C. 只含齐次通解','D. 以上都不对'], ans:0, hint:'通解=齐次通解+特解'},
  {cat:'linalg', stem:'矩阵A和B等价的条件是：', opts:['A. r(A)=r(B)且A,B同型','B. A=B','C. |A|=|B|','D. A和B特征值相同'], ans:0, hint:'等价⇔同型且同秩'},
  {cat:'linalg', stem:'矩阵的QR分解是将A分解为：', opts:['A. 正交矩阵Q和上三角矩阵R的乘积','B. 下三角和上三角','C. 对称矩阵之积','D. 对角矩阵之积'], ans:0, hint:'QR:Q正交+R上三角'},
  {cat:'linalg', stem:'奇异值分解(SVD)将矩阵A分解为：', opts:['A. UΣV^T(U,V正交，Σ对角)','B. LU','C. QR','D. LDL^T'], ans:0, hint:'SVD=UΣV^T'},
  {cat:'linalg', stem:'正定二次型的判定条件：所有顺序主子式为正是什么类型的条件？', opts:['A. 充要条件','B. 充分条件','C. 必要条件','D. 既非充分也非必要'], ans:0, hint:'西尔维斯特准则（充要）'},

  // ═══ 更多概率 ═══
  {cat:'prob', stem:'马尔可夫不等式P(X≥a)≤E(X)/a要求：', opts:['A. X≥0且a>0','B. X为正态','C. X为离散','D. 无条件'], ans:0, hint:'X非负+a>0'},
  {cat:'prob', stem:'辛钦大数定律的条件是：', opts:['A. 独立同分布且期望存在','B. 方差存在','C. 正态分布','D. 离散分布'], ans:0, hint:'iid+期望存在'},
  {cat:'prob', stem:'中心极限定理要求的最基本条件是：', opts:['A. 独立同分布且方差有限','B. 正态分布','C. 均匀分布','D. 期望无限'], ans:0, hint:'CLT:iid+有限方差'},
  {cat:'prob', stem:'泊松定理：当n大p小np=λ时，B(n,p)近似：', opts:['A. P(λ)(泊松分布)','B. N(0,1)','C. U(0,1)','D. Exp(λ)'], ans:0, hint:'n大p小→泊松近似'},
  {cat:'prob', stem:'卡方拟合优度检验用于：', opts:['A. 检验样本是否来自某一指定分布','B. 估计参数','C. 求期望','D. 求方差'], ans:0, hint:'拟合优度=检验分布'},

  // ═══ 第七批 · 高数计算与综合 ═══
  {cat:'calculus', stem:'函数f(x)=x/(x²+1)的水平渐近线是：', opts:['A. y=0','B. y=1','C. y=-1','D. 没有'], ans:0, hint:'x→±∞时f(x)→0'},
  {cat:'calculus', stem:'函数f(x)=1/(x-1)的垂直渐近线是：', opts:['A. x=0','B. x=1','C. x=-1','D. 没有'], ans:1, hint:'x=1时分母=0'},
  {cat:'calculus', stem:'∫₀^(2π) cos²x dx =', opts:['A. π','B. 2π','C. 0','D. π/2'], ans:0, hint:'cos²x平均值=1/2×周期=π'},
  {cat:'calculus', stem:'函数y=xe^(-x)的极值为：', opts:['A. x=1处取极大值1/e','B. x=0处取极小值','C. x=-1处取极大值','D. 没有极值'], ans:0, hint:'y\'=e^(-x)(1-x)=0→x=1'},
  {cat:'calculus', stem:'∫₁^e ln x dx =', opts:['A. 1','B. e-1','C. 0','D. e'], ans:0, hint:'分部积分xlnx-x从1到e'},
  {cat:'calculus', stem:'曲线y=x³的拐点坐标是：', opts:['A. (0,0)','B. (1,1)','C. (-1,-1)','D. 没有拐点'], ans:0, hint:'y\'\'=6x=0→x=0，且y\'\'变号'},
  {cat:'calculus', stem:'函数f(x)=sin x/x在x→0时的极限为：', opts:['A. 1','B. 0','C. ∞','D. 不存在'], ans:0, hint:'第一个重要极限'},
  {cat:'calculus', stem:'设f(x)=x²sin(1/x)(x≠0)，f(0)=0，则f\'(0)=', opts:['A. 0','B. 1','C. 不存在','D. -1'], ans:0, hint:'f\'(0)=lim f(x)/x=lim xsin(1/x)=0'},
  {cat:'calculus', stem:'∫ x/(x²+1) dx =', opts:['A. (1/2)ln(x²+1)+C','B. ln(x²+1)+C','C. arctan x+C','D. x²/2+C'], ans:0, hint:'凑微分d(x²+1)=2xdx'},
  {cat:'calculus', stem:'旋转体侧面积公式为2π∫ₐᵇ y·√(1+y\'²) dx，其几何意义是：', opts:['A. 曲线绕x轴旋转的侧面积','B. 体积','C. 弧长','D. 质心'], ans:0, hint:'旋转曲面面积'},
  {cat:'calculus', stem:'数列xₙ=(-1)^n·(1/n)的上确界是：', opts:['A. 1/2','B. 1','C. 0','D. 1/3'], ans:0, hint:'n=2时x₂=1/2，之后偶数项递减'},
  {cat:'calculus', stem:'连续函数在闭区间上一定取到：', opts:['A. 最大值和最小值','B. 只有最大值','C. 不一定取到极值','D. 只有最小值'], ans:0, hint:'最值定理'},
  {cat:'calculus', stem:'介值定理要求函数在什么条件下满足？', opts:['A. 闭区间上连续','B. 开区间上可导','C. 有界','D. 单调'], ans:0, hint:'闭区间连续→介值定理'},
  {cat:'calculus', stem:'设f(x)在[0,1]上连续，f(0)=f(1)，则f(x)在(0,1)内至少有一个：', opts:['A. 满足f\'(ξ)=0的点(若可导)','B. 零点','C. 极大值点','D. 不确定'], ans:0, hint:'罗尔定理'},
  {cat:'calculus', stem:'函数y=e^(x²)的导数为：', opts:['A. 2xe^(x²)','B. e^(x²)','C. x²e^(x²-1)','D. 2e^(x²)'], ans:0, hint:'链式法则：外导×内导'},
  {cat:'calculus', stem:'∫ sin(2x) dx =', opts:['A. -(1/2)cos(2x)+C','B. cos(2x)+C','C. (1/2)cos(2x)+C','D. -cos(2x)+C'], ans:0, hint:'∫sin(ax)dx=-cos(ax)/a'},
  {cat:'calculus', stem:'dy/dx = y的通解是：', opts:['A. y=Ce^x','B. y=Cx','C. y=C/x','D. y=x+C'], ans:0, hint:'分离变量dy/y=dx'},
  {cat:'calculus', stem:'dy/dx = -y/x的通解是：', opts:['A. y=C/x','B. y=Cx','C. y=Ce^x','D. y=x+C'], ans:0, hint:'分离变量dy/y=-dx/x→lny=-lnx+C'},
  {cat:'calculus', stem:'柯西积分不等式|∫fg|²≤∫f²·∫g²属于哪个领域？', opts:['A. 泛函分析/积分不等式','B. 代数','C. 概率论','D. 拓扑学'], ans:0, hint:'Cauchy-Schwarz不等式'},
  {cat:'calculus', stem:'函数f(x,y)=x²+y²-2x的极小值点是：', opts:['A. (1,0)','B. (0,0)','C. (2,0)','D. (1,1)'], ans:0, hint:'fx=2x-2=0,fy=2y=0→(1,0)'},
  {cat:'calculus', stem:'二重积分∫∫_D xy dA，D为x²+y²≤1的第一象限部分，结果为：', opts:['A. 1/8','B. 1/4','C. 1/2','D. 0'], ans:0, hint:'极坐标计算'},
  {cat:'calculus', stem:'格林公式∮_C Pdx+Qdy = ∫∫_D (∂Q/∂x-∂P/∂y)dA要求：', opts:['A. C为闭曲线且D为其围成的区域','B. C为开曲线','C. D无界','D. P=Q'], ans:0, hint:'格林公式前提：闭曲线+区域'},
  {cat:'calculus', stem:'幂级数∑(n=0 to ∞) x^n/n!的和函数是：', opts:['A. e^x','B. 1/(1-x)','C. sin x','D. cos x'], ans:0, hint:'eˣ的泰勒展开'},
  {cat:'calculus', stem:'调和级数∑1/n的敛散性：', opts:['A. 发散','B. 收敛于1','C. 收敛于e','D. 收敛于ln2'], ans:0, hint:'p=1时发散'},
  {cat:'calculus', stem:'函数f(x)=|x|²=x²在x=0处是否可导？', opts:['A. 可导，f\'(0)=0','B. 不可导','C. 左导数不存在','D. 右导数不存在'], ans:0, hint:'f\'(x)=2x,f\'(0)=0'},
  {cat:'calculus', stem:'设f(x)=x³+3x-1，则f(x)=0在(0,1)内有几个实根？', opts:['A. 恰好1个','B. 0个','C. 2个','D. 3个'], ans:0, hint:'f(0)=-1<0,f(1)=3>0,f单调递增'},
  {cat:'calculus', stem:'∫₀^1 1/√x dx =', opts:['A. 2','B. ∞','C. 1','D. 1/2'], ans:0, hint:'2√x从0到1=2'},
  {cat:'calculus', stem:'无穷级数收敛的必要条件是：', opts:['A. 通项趋于0','B. 部分和有界','C. 通项单调','D. 通项有界'], ans:0, hint:'aₙ→0是必要不充分'},
  {cat:'calculus', stem:'Abel收敛判别法用于判断什么级数？', opts:['A. ∑aₙbₙ型级数','B. 正项级数','C. 等比级数','D. p级数'], ans:0, hint:'Abel=乘积级数判别'},
  {cat:'calculus', stem:'隐函数x²+y²+z²=1确定z=z(x,y)时，∂z/∂x=', opts:['A. -x/z','B. x/z','C. -z/x','D. z/x'], ans:0, hint:'隐函数求偏导'},
  {cat:'calculus', stem:'曲面z=x²+y²在点(1,1,2)的法线方向向量为：', opts:['A. (2,2,-1)','B. (1,1,2)','C. (0,0,1)','D. (1,1,1)'], ans:0, hint:'F=x²+y²-z,∇F=(2x,2y,-1)=(2,2,-1)'},
  {cat:'calculus', stem:'设D是第一象限内x+y≤1的三角形区域，∫∫_D dA=', opts:['A. 1/2','B. 1','C. 1/4','D. 2'], ans:0, hint:'三角形面积=1/2×1×1=1/2'},
  {cat:'calculus', stem:'复变函数z²在整个复平面上是否解析？', opts:['A. 是','B. 否','C. 只在原点','D. 只在实轴'], ans:0, hint:'多项式处处解析'},
  {cat:'calculus', stem:'留数定理用于计算：', opts:['A. 围道积分','B. 实数积分','C. 微分方程','D. 级数和'], ans:0, hint:'留数定理=围道积分工具'},
  {cat:'calculus', stem:'拉普拉斯变换L{e^(at)}=', opts:['A. 1/(s-a)','B. 1/s','C. s/(s²+a²)','D. a/(s²+a²)'], ans:0, hint:'L{e^(at)}=1/(s-a),s>a'},
  {cat:'calculus', stem:'傅里叶变换的逆变换存在的条件是：', opts:['A. 函数绝对可积','B. 函数连续','C. 函数有界','D. 函数周期'], ans:0, hint:'绝对可积→逆变换存在'},
  {cat:'calculus', stem:'多重积分的换元公式中，需要乘以：', opts:['A. 雅可比行列式的绝对值','B. 雅可比行列式','C. 1','D. 行列式的平方'], ans:0, hint:'|J|=|∂(x,y)/∂(u,v)|'},
  {cat:'calculus', stem:'曲线积分∮_C x dy - y dx (C为单位圆逆时针)=', opts:['A. 2π','B. 0','C. π','D. -2π'], ans:0, hint:'格林公式=∫∫(1+1)dA=2×π×1²=2π'},
  {cat:'calculus', stem:'向量场F=(y,-x,0)的旋度为：', opts:['A. (0,0,-2)','B. (0,0,2)','C. (0,0,0)','D. (1,1,0)'], ans:0, hint:'∇×F=偏导交叉计算'},
  {cat:'calculus', stem:'向量场F=(x,y,z)的散度为：', opts:['A. 3','B. 0','C. 1','D. x+y+z'], ans:0, hint:'∇·F=1+1+1=3'},

  // ═══ 第八批 · 线代计算与综合 ═══
  {cat:'linalg', stem:'3阶单位矩阵I的行列式|I|=', opts:['A. 1','B. 0','C. 3','D. -1'], ans:0, hint:'单位矩阵行列式=1'},
  {cat:'linalg', stem:'若A,B都是n阶可逆矩阵，则(AB)⁻¹=', opts:['A. B⁻¹A⁻¹','B. A⁻¹B⁻¹','C. AB','D. BA'], ans:0, hint:'逆矩阵倒序'},
  {cat:'linalg', stem:'若矩阵A的特征值为1,2,3，则A²的特征值为：', opts:['A. 1,4,9','B. 2,4,6','C. 1,2,3','D. 3,6,9'], ans:0, hint:'A²特征值=λ²'},
  {cat:'linalg', stem:'若A的特征值为1,2,3，则A+I的特征值为：', opts:['A. 2,3,4','B. 1,2,3','C. 0,1,2','D. 2,4,6'], ans:0, hint:'A+kI特征值=λ+k'},
  {cat:'linalg', stem:'若A的特征值为1,2,3，则A⁻¹的特征值为：', opts:['A. 1,1/2,1/3','B. 1,2,3','C. 3,2,1','D. -1,-2,-3'], ans:0, hint:'A⁻¹特征值=1/λ'},
  {cat:'linalg', stem:'3阶矩阵A的特征值为1,2,3，则|A|=', opts:['A. 6','B. 1','C. 5','D. 0'], ans:0, hint:'|A|=λ₁λ₂λ₃=6'},
  {cat:'linalg', stem:'3阶矩阵A的特征值为1,2,3，则tr(A)=', opts:['A. 6','B. 5','C. 3','D. 9'], ans:0, hint:'tr=1+2+3=6'},
  {cat:'linalg', stem:'若A是3×5矩阵，r(A)=3，则Ax=0的解空间维数为：', opts:['A. 2','B. 3','C. 5','D. 0'], ans:0, hint:'dim(null)=5-3=2'},
  {cat:'linalg', stem:'若A是4×4矩阵，r(A)=2，则Ax=0有多少个自由变量？', opts:['A. 2','B. 4','C. 1','D. 3'], ans:0, hint:'自由变量=4-2=2'},
  {cat:'linalg', stem:'设A为正交矩阵，则A的列向量组必定是：', opts:['A. 标准正交基','B. 线性相关','C. 零向量','D. 全为单位向量但不正交'], ans:0, hint:'正交矩阵→列为标准正交基'},
  {cat:'linalg', stem:'若r(A₃ₓ₃)=1，则A的伴随矩阵A*的秩为：', opts:['A. 1','B. 0','C. 2','D. 3'], ans:0, hint:'r(A)=1→r(A*)=1(n=3时特殊结论)'},
  {cat:'linalg', stem:'分块对角矩阵diag(A₁,A₂)的行列式=', opts:['A. |A₁|·|A₂|','B. |A₁|+|A₂|','C. |A₁|-|A₂|','D. 0'], ans:0, hint:'分块对角行列式=子块行列式之积'},
  {cat:'linalg', stem:'若A是反对称矩阵(A^T=-A)，则A的主对角线元素全为：', opts:['A. 0','B. 1','C. -1','D. 任意'], ans:0, hint:'aij=-aji→aii=-aii→aii=0'},
  {cat:'linalg', stem:'两个向量的混合积[a,b,c]=a·(b×c)的几何意义是：', opts:['A. a,b,c构成的平行六面体的有向体积','B. 面积','C. 长度','D. 角度'], ans:0, hint:'混合积=平行六面体体积'},
  {cat:'linalg', stem:'矩阵A的最小多项式m(λ)的根与A的：', opts:['A. 特征值集合相同','B. 特征向量相同','C. 秩相同','D. 行列式相同'], ans:0, hint:'最小多项式的根=不重复的特征值'},
  {cat:'linalg', stem:'矩阵的Frobenius范数||A||_F的定义是：', opts:['A. 所有元素平方和的算术平方根','B. 最大特征值','C. 行列式','D. 秩'], ans:0, hint:'||A||_F=√(Σaij²)'},
  {cat:'linalg', stem:'若A的特征值为λ，则kA的特征值为：', opts:['A. kλ','B. k+λ','C. λ/k','D. k²λ'], ans:0, hint:'kA的特征值=kλ'},
  {cat:'linalg', stem:'矩阵A=(1 2; 3 4)的行列式|A|=', opts:['A. -2','B. 2','C. 10','D. 0'], ans:0, hint:'1×4-2×3=-2'},
  {cat:'linalg', stem:'矩阵A=(1 2; 3 4)的迹tr(A)=', opts:['A. 5','B. 6','C. 10','D. -2'], ans:0, hint:'1+4=5'},
  {cat:'linalg', stem:'克莱姆法则对方程组Ax=b适用时，x_i的计算公式是：', opts:['A. x_i=|A_i|/|A|','B. x_i=|A|/|A_i|','C. x_i=|A_i|','D. x_i=|A|'], ans:0, hint:'Cramer法则'},
  {cat:'linalg', stem:'矩阵的初等列变换不改变矩阵的：', opts:['A. 列空间','B. 行空间','C. 秩','D. B和C都对'], ans:3, hint:'初等列变换保持行空间和秩不变'},
  {cat:'linalg', stem:'投影矩阵P的性质：P²=P且P^T=P，即P是：', opts:['A. 对称幂等矩阵','B. 正交矩阵','C. 可逆矩阵','D. 零矩阵'], ans:0, hint:'投影矩阵=对称+幂等'},
  {cat:'linalg', stem:'矩阵A可逆的充要条件不包括：', opts:['A. |A|≠0','B. r(A)=n','C. A的行向量线性无关','D. A有零特征值'], ans:3, hint:'有零特征值→不可逆'},
  {cat:'linalg', stem:'向量a=(1,0,0)和b=(0,1,0)的叉积a×b=', opts:['A. (0,0,1)','B. (0,0,-1)','C. (1,1,0)','D. (0,0,0)'], ans:0, hint:'i×j=k'},
  {cat:'linalg', stem:'特征方程|λI-A|=0展开后是一个关于λ的什么？', opts:['A. n次多项式','B. n-1次多项式','C. 线性方程','D. 指数函数'], ans:0, hint:'n阶矩阵→n次特征多项式'},

  // ═══ 第九批 · 概率论计算与综合 ═══
  {cat:'prob', stem:'一枚均匀硬币抛3次，恰好出现2次正面的概率为：', opts:['A. 3/8','B. 1/4','C. 1/2','D. 1/8'], ans:0, hint:'C(3,2)×(1/2)³=3/8'},
  {cat:'prob', stem:'两个独立事件A,B，P(A)=0.3,P(B)=0.5，则P(A∪B)=', opts:['A. 0.65','B. 0.8','C. 0.15','D. 0.5'], ans:0, hint:'P(A∪B)=0.3+0.5-0.15=0.65'},
  {cat:'prob', stem:'X~B(10,0.5)，则E(X)=', opts:['A. 5','B. 10','C. 2.5','D. 0.5'], ans:0, hint:'np=10×0.5=5'},
  {cat:'prob', stem:'X~B(10,0.5)，则D(X)=', opts:['A. 2.5','B. 5','C. 10','D. 0.25'], ans:0, hint:'npq=10×0.5×0.5=2.5'},
  {cat:'prob', stem:'X~P(3)(泊松分布)，则P(X=0)=', opts:['A. e^(-3)','B. 0','C. 1','D. 3'], ans:0, hint:'P(X=k)=e^(-λ)λ^k/k!→e^(-3)'},
  {cat:'prob', stem:'X~Exp(2)，则P(X>1)=', opts:['A. e^(-2)','B. 1-e^(-2)','C. 2e^(-2)','D. 1'], ans:0, hint:'P(X>t)=e^(-λt)=e^(-2)'},
  {cat:'prob', stem:'X~N(3,4)，则P(X<3)=', opts:['A. 0.5','B. 0.3','C. 0.7','D. 1'], ans:0, hint:'正态分布关于均值对称'},
  {cat:'prob', stem:'X~U(0,4)，则E(X)=', opts:['A. 2','B. 4','C. 0','D. 1'], ans:0, hint:'(0+4)/2=2'},
  {cat:'prob', stem:'X~U(0,4)，则D(X)=', opts:['A. 4/3','B. 2','C. 4','D. 16/3'], ans:0, hint:'(4-0)²/12=16/12=4/3'},
  {cat:'prob', stem:'两个骰子同时投掷，点数之和为7的概率为：', opts:['A. 1/6','B. 1/12','C. 1/36','D. 5/36'], ans:0, hint:'6种组合/36=1/6'},
  {cat:'prob', stem:'某批产品次品率p=0.1，抽10个产品，用二项分布求恰好有1个次品的概率约为：', opts:['A. 0.387','B. 0.349','C. 0.5','D. 0.1'], ans:0, hint:'C(10,1)×0.1×0.9⁹≈0.387'},
  {cat:'prob', stem:'在回归分析中，相关系数r=0说明：', opts:['A. X和Y之间没有线性关系','B. X和Y无关','C. X和Y独立','D. X=Y'], ans:0, hint:'r=0→无线性关系（可能有非线性）'},
  {cat:'prob', stem:'一个口袋有3红2白球，不放回地取2个，取到的红球数X的期望E(X)=', opts:['A. 6/5','B. 1','C. 2','D. 3/5'], ans:0, hint:'超几何分布E=nM/N=2×3/5=6/5'},
  {cat:'prob', stem:'设X₁,X₂,...,Xₙ是来自N(μ,σ²)的简单随机样本，则样本均值X̄服从：', opts:['A. N(μ,σ²/n)','B. N(μ,σ²)','C. t(n-1)','D. χ²(n)'], ans:0, hint:'X̄~N(μ,σ²/n)'},
  {cat:'prob', stem:'设X₁,...,Xₙ来自N(μ,σ²)，(n-1)S²/σ²服从：', opts:['A. χ²(n-1)','B. t(n-1)','C. F(n-1,n)','D. N(0,1)'], ans:0, hint:'(n-1)S²/σ²~χ²(n-1)'},
  {cat:'prob', stem:'在假设检验中，p值越小说明：', opts:['A. 拒绝H₀的证据越强','B. 应该接受H₀','C. 数据不够','D. 无法判断'], ans:0, hint:'p值小→强烈反对H₀'},
  {cat:'prob', stem:'二维正态分布的概率密度由哪些参数决定？', opts:['A. μ₁,μ₂,σ₁,σ₂,ρ','B. μ,σ','C. λ','D. n,p'], ans:0, hint:'5个参数'},
  {cat:'prob', stem:'全概率公式P(B)=ΣP(Aᵢ)P(B|Aᵢ)中，{Aᵢ}必须满足：', opts:['A. 完备事件组(互不相容且并集为Ω)','B. 独立','C. 相关','D. 等可能'], ans:0, hint:'完备事件组=划分'},
  {cat:'prob', stem:'贝叶斯公式P(Aⱼ|B)=P(Aⱼ)P(B|Aⱼ)/ΣP(Aᵢ)P(B|Aᵢ)的本质是：', opts:['A. 由结果推原因','B. 由原因推结果','C. 求独立性','D. 求期望'], ans:0, hint:'贝叶斯=果→因'},
  {cat:'prob', stem:'连续型随机变量的概率密度函数f(x)与分布函数F(x)的关系：F\'(x)=', opts:['A. f(x)','B. F(x)','C. 1-F(x)','D. ∫f(x)dx'], ans:0, hint:'F\'(x)=f(x)'},
  {cat:'prob', stem:'E(X²)-[E(X)]²=', opts:['A. D(X)','B. E(X)','C. 0','D. [E(X)]²'], ans:0, hint:'方差=E(X²)-μ²'},
  {cat:'prob', stem:'若X和Y的联合密度为f(x,y)，则边缘密度fₓ(x)=', opts:['A. ∫f(x,y)dy','B. f(x,y)/fᵧ(y)','C. f(x,0)','D. ∫f(x,y)dx'], ans:0, hint:'对y积分得X的边缘密度'},
  {cat:'prob', stem:'X和Y独立的充要条件是：', opts:['A. f(x,y)=fₓ(x)·fᵧ(y)','B. E(XY)=0','C. Cov(X,Y)=0','D. ρ=0'], ans:0, hint:'联合=边缘之积⇔独立'},
  {cat:'prob', stem:'Z=X+Y (X,Y独立)的密度函数是X和Y密度函数的：', opts:['A. 卷积','B. 乘积','C. 和','D. 差'], ans:0, hint:'独立变量和的密度=卷积'},
  {cat:'prob', stem:'二项分布B(n,p)当n大p小时可用什么分布近似？', opts:['A. 泊松分布','B. 正态分布','C. 均匀分布','D. 指数分布'], ans:0, hint:'n大p小np=λ→泊松'},
  {cat:'prob', stem:'样本中位数是总体中位数的：', opts:['A. 近似估计','B. 精确值','C. 无关量','D. 方差'], ans:0, hint:'样本中位数估计总体中位数'},
  {cat:'prob', stem:'区间估计中，增大样本量n会使置信区间：', opts:['A. 变窄','B. 变宽','C. 不变','D. 消失'], ans:0, hint:'n↑→标准误↓→区间窄'},
  {cat:'prob', stem:'总体X~N(μ,σ²)，σ²已知时，对μ的检验用什么统计量？', opts:['A. Z统计量(标准正态)','B. t统计量','C. F统计量','D. χ²统计量'], ans:0, hint:'σ²已知→Z检验'},
  {cat:'prob', stem:'总体X~N(μ,σ²)，σ²未知时，对μ的检验用什么统计量？', opts:['A. t统计量','B. Z统计量','C. F统计量','D. χ²统计量'], ans:0, hint:'σ²未知→t检验'},

  // ═══ 第十批 · 混合补充 ═══
  {cat:'calculus', stem:'函数f(x)=sin(x)/x的可去间断点在：', opts:['A. x=0','B. x=π','C. x=1','D. 没有间断点'], ans:0, hint:'x=0处极限=1但无定义'},
  {cat:'calculus', stem:'第二类间断点包括：', opts:['A. 无穷间断点和振荡间断点','B. 可去间断点','C. 跳跃间断点','D. B和C'], ans:0, hint:'第二类=无穷+振荡'},
  {cat:'calculus', stem:'第一类间断点包括：', opts:['A. 可去间断点和跳跃间断点','B. 无穷间断点','C. 振荡间断点','D. B和C'], ans:0, hint:'第一类=可去+跳跃'},
  {cat:'calculus', stem:'∫₀^∞ e^(-x²) dx = ', opts:['A. √π/2','B. √π','C. π','D. 1'], ans:0, hint:'高斯积分的一半'},
  {cat:'calculus', stem:'多元函数的条件极值问题可用什么方法求解？', opts:['A. 拉格朗日乘数法','B. 直接求导','C. 分部积分','D. 级数展开'], ans:0, hint:'有约束→拉格朗日乘数法'},
  {cat:'calculus', stem:'设z=f(xy,x/y)，其中f具有连续偏导数，则x∂z/∂x+y∂z/∂y=', opts:['A. 需要具体计算（涉及链式法则）','B. 0','C. 1','D. z'], ans:0, hint:'复合函数偏导需链式法则'},
  {cat:'calculus', stem:'一致连续和连续的关系：函数在闭区间上连续则：', opts:['A. 一定一致连续(Cantor定理)','B. 不一定一致连续','C. 一定不一致连续','D. 无关'], ans:0, hint:'闭区间连续⇒一致连续'},
  {cat:'calculus', stem:'函数项级数一致收敛的充分条件(Weierstrass M判别法)：', opts:['A. 若|fₙ(x)|≤Mₙ且∑Mₙ收敛','B. |fₙ(x)|→0','C. fₙ有界','D. fₙ连续'], ans:0, hint:'M判别法=逐项被正项级数控制'},
  {cat:'calculus', stem:'二元函数在某点偏导数存在但不连续，则函数在该点：', opts:['A. 不一定可微','B. 一定可微','C. 一定连续','D. 一定不连续'], ans:0, hint:'偏导存在不能保证可微'},
  {cat:'calculus', stem:'曲线y=x²和y=x围成的面积为：', opts:['A. 1/6','B. 1/3','C. 1/2','D. 1'], ans:0, hint:'∫₀¹(x-x²)dx=1/2-1/3=1/6'},
  {cat:'calculus', stem:'曲线y=√x, y=0, x=1围成区域绕x轴旋转体积为：', opts:['A. π/2','B. π','C. 2π','D. π/4'], ans:0, hint:'V=π∫₀¹(√x)²dx=π/2'},
  {cat:'linalg', stem:'如果n阶矩阵A满足A²=I(I为单位矩阵)，则A的特征值只能是：', opts:['A. 1或-1','B. 0或1','C. 0或-1','D. 任意实数'], ans:0, hint:'λ²=1→λ=±1'},
  {cat:'linalg', stem:'若A是实矩阵，则A^T·A的特征值一定：', opts:['A. 非负','B. 为正','C. 可以为负','D. 为零'], ans:0, hint:'A^TA半正定→特征值≥0'},
  {cat:'linalg', stem:'下三角矩阵L的行列式等于：', opts:['A. 主对角线元素之积','B. 0','C. 1','D. 所有元素之和'], ans:0, hint:'三角矩阵|L|=∏lii'},
  {cat:'linalg', stem:'矩阵A的列空间的维数等于：', opts:['A. r(A)','B. n-r(A)','C. n','D. m'], ans:0, hint:'列空间维数=秩'},
  {cat:'linalg', stem:'行阶梯形矩阵的主元所在列对应原矩阵的：', opts:['A. 基向量（极大线性无关组的成员）','B. 零向量','C. 自由变量','D. 特解'], ans:0, hint:'主元列=基向量'},
  {cat:'linalg', stem:'若A是n阶矩阵，A的列向量组线性相关，则：', opts:['A. |A|=0','B. |A|≠0','C. A可逆','D. r(A)=n'], ans:0, hint:'列向量线性相关→|A|=0'},
  {cat:'linalg', stem:'矩阵指数e^A的定义是：', opts:['A. I+A+A²/2!+A³/3!+...','B. e的A次方','C. A的e次方','D. 不存在'], ans:0, hint:'矩阵指数=级数展开'},
  {cat:'prob', stem:'X的k阶原点矩定义为：', opts:['A. E(X^k)','B. E(X-μ)^k','C. D(X^k)','D. (E(X))^k'], ans:0, hint:'μₖ=E(X^k)'},
  {cat:'prob', stem:'X的k阶中心矩定义为：', opts:['A. E(X-μ)^k','B. E(X^k)','C. D(X)','D. E(X)^k'], ans:0, hint:'νₖ=E(X-μ)^k'},
  {cat:'prob', stem:'大数定律保证了随机现象的：', opts:['A. 统计规律性','B. 确定性','C. 不可预测性','D. 随机性'], ans:0, hint:'大数定律=统计规律'},
  {cat:'prob', stem:'某检验的功效(power)=1-β表示：', opts:['A. 正确拒绝H₀的概率','B. 错误拒绝H₀的概率','C. 接受H₀的概率','D. 检验失败的概率'], ans:0, hint:'功效=正确拒绝错误H₀的概率'},
  {cat:'prob', stem:'柯尔莫哥洛夫概率公理中，必然事件Ω的概率为：', opts:['A. 1','B. 0','C. ∞','D. 不确定'], ans:0, hint:'P(Ω)=1'},
  {cat:'prob', stem:'条件分布F(x|y)与联合分布F(x,y)和边缘分布Fᵧ(y)的关系：', opts:['A. f(x|y)=f(x,y)/fᵧ(y)','B. F(x|y)=F(x,y)+Fᵧ(y)','C. f(x|y)=f(x,y)·fᵧ(y)','D. 无关'], ans:0, hint:'条件密度=联合/边缘'},
  {cat:'prob', stem:'正态分布的偏度系数为：', opts:['A. 0','B. 1','C. 3','D. -1'], ans:0, hint:'正态分布对称→偏度=0'},
  {cat:'prob', stem:'正态分布的峰度系数(超额峰度)为：', opts:['A. 0','B. 3','C. 1','D. -1'], ans:0, hint:'正态超额峰度=0(峰度=3)'},

  // ═══ 最后补充 ═══
  {cat:'calculus', stem:'等比级数∑ar^n (n=0 to ∞)的求和公式(|r|<1)为：', opts:['A. a/(1-r)','B. a·r','C. a+r','D. 1/r'], ans:0, hint:'S=a/(1-r)'},
  {cat:'calculus', stem:'自然对数的底e≈', opts:['A. 2.718','B. 3.14','C. 1.414','D. 1.618'], ans:0, hint:'e≈2.71828'},
  {cat:'calculus', stem:'圆周率π≈', opts:['A. 3.14159','B. 2.71828','C. 1.41421','D. 1.61803'], ans:0, hint:'π≈3.14159'},
  {cat:'linalg', stem:'单位矩阵I的特征值是：', opts:['A. 全为1','B. 全为0','C. 1和-1','D. 不确定'], ans:0, hint:'Ix=1·x→特征值全1'},
  {cat:'linalg', stem:'零矩阵O的秩r(O)=', opts:['A. 0','B. 1','C. n','D. 不确定'], ans:0, hint:'零矩阵秩为0'},
  {cat:'prob', stem:'掷一个均匀骰子，出现偶数的概率为：', opts:['A. 1/2','B. 1/3','C. 1/6','D. 2/3'], ans:0, hint:'偶数{2,4,6}=3个/6=1/2'},
  {cat:'prob', stem:'从52张扑克牌中随机抽一张，抽到红心的概率为：', opts:['A. 1/4','B. 1/2','C. 1/13','D. 1/52'], ans:0, hint:'13红心/52=1/4'},
  {cat:'prob', stem:'正态分布的概率密度函数图形是：', opts:['A. 钟形曲线','B. 直线','C. 抛物线','D. 指数曲线'], ans:0, hint:'正态=钟形曲线'},
  {cat:'prob', stem:'在方差分析(ANOVA)中，F统计量用于检验：', opts:['A. 多个总体均值是否相等','B. 方差是否为零','C. 中位数是否相等','D. 频率是否相等'], ans:0, hint:'ANOVA用F检验均值差异'},
  {cat:'prob', stem:'极大似然估计量(MLE)具有的性质不包括：', opts:['A. 一致性','B. 渐近正态性','C. 不变性','D. 一定无偏'], ans:3, hint:'MLE不一定无偏'},

  // ═══ 最终补齐至500 ═══
  {cat:'calculus', stem:'∫ 1/(1+x²) dx =', opts:['A. arctan x + C','B. ln(1+x²) + C','C. 1/(1+x²) + C','D. x/(1+x²) + C'], ans:0, hint:'标准积分公式'},
  {cat:'calculus', stem:'∫ 1/x dx =', opts:['A. ln|x| + C','B. 1/x² + C','C. x + C','D. -1/x² + C'], ans:0, hint:'对数积分'},
  {cat:'calculus', stem:'(sin x)\' =', opts:['A. cos x','B. -cos x','C. sin x','D. -sin x'], ans:0, hint:'正弦导数=余弦'},
  {cat:'calculus', stem:'(cos x)\' =', opts:['A. -sin x','B. sin x','C. cos x','D. -cos x'], ans:0, hint:'余弦导数=-正弦'},
  {cat:'calculus', stem:'(tan x)\' =', opts:['A. sec²x','B. csc²x','C. cot x','D. sin x/cos²x'], ans:0, hint:'tan导数=sec²x'},
  {cat:'calculus', stem:'(e^x)\' =', opts:['A. e^x','B. xe^(x-1)','C. e^(x-1)','D. 1/e^x'], ans:0, hint:'e^x的导数是自身'},
  {cat:'calculus', stem:'(ln x)\' =', opts:['A. 1/x','B. ln x','C. x','D. e^x'], ans:0, hint:'自然对数导数=1/x'},
  {cat:'calculus', stem:'L\'Hôpital法则适用的条件是：', opts:['A. 0/0或∞/∞型不定式','B. 任何极限','C. 0×∞型','D. 1^∞型'], ans:0, hint:'洛必达=0/0或∞/∞'},
  {cat:'calculus', stem:'f(x)在x₀处可微的充要条件是：', opts:['A. Δy=AΔx+o(Δx)，其中A=f\'(x₀)','B. f连续','C. f有界','D. f可积'], ans:0, hint:'可微=线性增量+高阶无穷小'},
  {cat:'calculus', stem:'设f(x)在区间I上一致连续，则f(x)在I上一定：', opts:['A. 连续','B. 可导','C. 有界','D. 单调'], ans:0, hint:'一致连续⇒连续'},
  {cat:'calculus', stem:'Riemann积分存在的充要条件之一是：', opts:['A. f在[a,b]上有界且不连续点组成零测集','B. f连续','C. f可导','D. f单调'], ans:0, hint:'Lebesgue判据'},
  {cat:'calculus', stem:'微分方程y\'+P(x)y=Q(x)的类型是：', opts:['A. 一阶线性ODE','B. 二阶ODE','C. 偏微分方程','D. 差分方程'], ans:0, hint:'一阶线性微分方程'},
  {cat:'calculus', stem:'齐次方程y\'+P(x)y=0的通解为：', opts:['A. y=Ce^(-∫P(x)dx)','B. y=Cx','C. y=C+P(x)','D. y=P(x)'], ans:0, hint:'分离变量→指数解'},
  {cat:'calculus', stem:'二阶常系数齐次线性方程y\'\'+py\'+qy=0的特征方程为：', opts:['A. r²+pr+q=0','B. r+p=0','C. r²=q','D. r=p+q'], ans:0, hint:'特征方程=代入e^(rx)'},
  {cat:'calculus', stem:'欧拉公式e^(iθ)=', opts:['A. cosθ + i·sinθ','B. cosθ - i·sinθ','C. sinθ + i·cosθ','D. 1'], ans:0, hint:'Euler公式'},
  {cat:'calculus', stem:'三重积分∫∫∫_Ω dV在球坐标下的体积元素dV=', opts:['A. ρ²sinφ dρdφdθ','B. r dr dθ dz','C. dx dy dz','D. ρ dρ dφ dθ'], ans:0, hint:'球坐标体积元=ρ²sinφ'},
  {cat:'calculus', stem:'斯托克斯公式将什么联系起来？', opts:['A. 曲面积分与曲线积分','B. 二重积分与三重积分','C. 单积分与二重积分','D. 级数与积分'], ans:0, hint:'Stokes=曲面⇔边界曲线'},
  {cat:'calculus', stem:'高斯散度定理将什么联系起来？', opts:['A. 三重积分与曲面积分','B. 曲线积分与二重积分','C. 单积分与曲线积分','D. 级数与积分'], ans:0, hint:'Gauss=体积⇔封闭曲面'},
  {cat:'calculus', stem:'正项级数的比值审敛法：若lim(aₙ₊₁/aₙ)=ρ<1，则级数：', opts:['A. 收敛','B. 发散','C. 不确定','D. 条件收敛'], ans:0, hint:'ρ<1收敛，ρ>1发散，ρ=1不确定'},
  {cat:'calculus', stem:'正项级数的根值审敛法：若lim(aₙ)^(1/n)=ρ<1，则级数：', opts:['A. 收敛','B. 发散','C. 不确定','D. 条件收敛'], ans:0, hint:'Cauchy根值法'},
  {cat:'calculus', stem:'交错级数∑(-1)^n·bₙ收敛的充分条件(Leibniz判别法)是：', opts:['A. bₙ单调递减且bₙ→0','B. bₙ有界','C. bₙ递增','D. bₙ=常数'], ans:0, hint:'Leibniz=单调趋零'},
  {cat:'calculus', stem:'幂级数∑aₙx^n的收敛半径R的计算公式(比值法)为：', opts:['A. R=lim|aₙ/aₙ₊₁|','B. R=lim|aₙ|','C. R=∑aₙ','D. R=1'], ans:0, hint:'R=lim|aₙ/aₙ₊₁|'},
  {cat:'calculus', stem:'Taylor公式中，余项Rₙ的Lagrange余项形式为：', opts:['A. f^(n+1)(ξ)·(x-a)^(n+1)/(n+1)!','B. f(x)-f(a)','C. f\'(a)·(x-a)','D. 0'], ans:0, hint:'Lagrange余项'},
  {cat:'calculus', stem:'McLaurin级数是什么的特例？', opts:['A. Taylor级数(展开点a=0)','B. Fourier级数','C. 幂级数','D. Laurent级数'], ans:0, hint:'Maclaurin=a=0的Taylor'},
  {cat:'calculus', stem:'sin x的Maclaurin展开的前三项是：', opts:['A. x - x³/3! + x⁵/5!','B. 1 - x²/2! + x⁴/4!','C. x + x²/2 + x³/3','D. 1 + x + x²'], ans:0, hint:'sinx=x-x³/6+x⁵/120-...'},
  {cat:'calculus', stem:'cos x的Maclaurin展开的前三项是：', opts:['A. 1 - x²/2! + x⁴/4!','B. x - x³/3! + x⁵/5!','C. 1 + x + x²','D. x + x²/2 + x³/6'], ans:0, hint:'cosx=1-x²/2+x⁴/24-...'},
  {cat:'calculus', stem:'偏微分∂²f/∂x∂y=∂²f/∂y∂x成立的条件是：', opts:['A. 二阶混合偏导数连续','B. f可导','C. f有界','D. 无条件'], ans:0, hint:'Schwarz定理：混合偏导连续则相等'},
  {cat:'calculus', stem:'方向导数的计算公式涉及什么？', opts:['A. 梯度与方向向量的点积','B. 叉积','C. 行列式','D. 秩'], ans:0, hint:'方向导数=∇f·e'},
  {cat:'calculus', stem:'梯度grad f的方向是：', opts:['A. f增长最快的方向','B. f减小最快的方向','C. 等值线方向','D. 随机方向'], ans:0, hint:'梯度=最大方向导数方向'},
  {cat:'calculus', stem:'散度为零的向量场称为：', opts:['A. 无源场','B. 无旋场','C. 保守场','D. 零场'], ans:0, hint:'∇·F=0→无源'},
  {cat:'calculus', stem:'旋度为零的向量场称为：', opts:['A. 无旋场(保守场)','B. 无源场','C. 均匀场','D. 零场'], ans:0, hint:'∇×F=0→无旋/保守'},

  {cat:'linalg', stem:'矩阵A和B的乘积AB一般不等于BA，这说明矩阵乘法不满足：', opts:['A. 交换律','B. 结合律','C. 分配律','D. 以上都不满足'], ans:0, hint:'矩阵乘法不满足交换律'},
  {cat:'linalg', stem:'矩阵的LU分解是将矩阵分解为：', opts:['A. 下三角矩阵L和上三角矩阵U的乘积','B. 两个对称矩阵','C. 正交矩阵和对角矩阵','D. 特征值和特征向量'], ans:0, hint:'LU分解=Lower×Upper'},
  {cat:'linalg', stem:'QR分解是将矩阵分解为：', opts:['A. 正交矩阵Q和上三角矩阵R的乘积','B. 两个对角矩阵','C. 下三角和上三角','D. 对称矩阵和反对称矩阵'], ans:0, hint:'QR=正交×上三角'},
  {cat:'linalg', stem:'奇异值分解(SVD)将矩阵A分解为：', opts:['A. UΣV^T (U,V正交，Σ对角)','B. LU','C. QR','D. 特征分解'], ans:0, hint:'SVD=UΣV^T'},
  {cat:'linalg', stem:'最小二乘法求解超定方程组Ax≈b的正规方程是：', opts:['A. A^TAx=A^Tb','B. Ax=b','C. A^Tx=b','D. x=A^Tb'], ans:0, hint:'正规方程=A^TA·x=A^Tb'},
  {cat:'linalg', stem:'正定矩阵的所有特征值都：', opts:['A. 大于0','B. 等于0','C. 小于0','D. 可以为负'], ans:0, hint:'正定⇔所有特征值>0'},
  {cat:'linalg', stem:'谱定理(Spectral Theorem)指出实对称矩阵可以：', opts:['A. 正交对角化','B. 不能对角化','C. 只有三角化','D. 分解为LU'], ans:0, hint:'实对称→必可正交对角化'},
  {cat:'linalg', stem:'矩阵的条件数衡量的是：', opts:['A. 方程组解对输入扰动的敏感程度','B. 矩阵的大小','C. 矩阵的秩','D. 矩阵的迹'], ans:0, hint:'条件数大=病态'},
  {cat:'linalg', stem:'Gram-Schmidt正交化过程的目的是：', opts:['A. 将一组线性无关向量变为标准正交基','B. 求特征值','C. 求行列式','D. 求逆矩阵'], ans:0, hint:'G-S=正交化+单位化'},
  {cat:'linalg', stem:'若A是n阶实对称矩阵，则A的不同特征值对应的特征向量：', opts:['A. 相互正交','B. 相互平行','C. 线性相关','D. 相等'], ans:0, hint:'实对称→不同特征值对应正交特征向量'},
  {cat:'linalg', stem:'向量空间的基(Basis)满足的条件是：', opts:['A. 线性无关且生成整个空间','B. 线性相关','C. 全为零向量','D. 只有一个向量'], ans:0, hint:'基=线性无关+张成'},
  {cat:'linalg', stem:'有限维向量空间的维数(Dimension)等于：', opts:['A. 基中向量的个数','B. 空间中向量的总数','C. 矩阵的行数','D. 矩阵的列数'], ans:0, hint:'dim=基的大小'},
  {cat:'linalg', stem:'线性映射T:V→W的核(Kernel)定义为：', opts:['A. ker(T)={v∈V | T(v)=0}','B. T的像集','C. V本身','D. W本身'], ans:0, hint:'核=映射到零的元素集'},
  {cat:'linalg', stem:'线性映射T:V→W的像(Image)定义为：', opts:['A. Im(T)={T(v) | v∈V}','B. T的核','C. V本身','D. {0}'], ans:0, hint:'像=T的值域'},
  {cat:'linalg', stem:'维数公式：dim(ker T) + dim(Im T) =', opts:['A. dim V','B. dim W','C. 0','D. dim V + dim W'], ans:0, hint:'秩-零度定理'},

  {cat:'prob', stem:'Poisson分布P(λ)的方差等于：', opts:['A. λ','B. λ²','C. 1/λ','D. √λ'], ans:0, hint:'泊松分布E(X)=D(X)=λ'},
  {cat:'prob', stem:'指数分布Exp(λ)的期望E(X)=', opts:['A. 1/λ','B. λ','C. λ²','D. 1/λ²'], ans:0, hint:'指数分布期望=1/λ'},
  {cat:'prob', stem:'指数分布的无记忆性是指：', opts:['A. P(X>s+t|X>s)=P(X>t)','B. P(X=0)=1','C. E(X)=0','D. D(X)=0'], ans:0, hint:'无记忆性=指数分布独有'},
  {cat:'prob', stem:'几何分布的无记忆性是指：', opts:['A. P(X>m+n|X>m)=P(X>n)','B. P(X=0)=1','C. E(X)=0','D. 不存在'], ans:0, hint:'离散分布中只有几何分布有无记忆性'},
  {cat:'prob', stem:'协方差Cov(X,Y)=0但X和Y不独立，这说明：', opts:['A. 不相关不等于独立','B. 不相关等于独立','C. 两者总是相等','D. 协方差不存在'], ans:0, hint:'不相关≠独立(正态除外)'},
  {cat:'prob', stem:'矩估计法的基本思想是：', opts:['A. 用样本矩代替总体矩建立方程','B. 最大化似然函数','C. 最小化方差','D. 贝叶斯推断'], ans:0, hint:'矩估计=样本矩=总体矩'},
  {cat:'prob', stem:'极大似然估计法的基本思想是：', opts:['A. 选择使观测到的样本出现概率最大的参数值','B. 用样本矩估计总体矩','C. 最小化误差','D. 随机选择'], ans:0, hint:'MLE=最大化似然函数'},
  {cat:'prob', stem:'无偏估计量的定义是：', opts:['A. E(θ̂)=θ','B. D(θ̂)=0','C. θ̂=θ','D. P(θ̂=θ)=1'], ans:0, hint:'期望=真值→无偏'},
  {cat:'prob', stem:'有效估计量是指在所有无偏估计中：', opts:['A. 方差最小的','B. 偏差最大的','C. 最复杂的','D. 最简单的'], ans:0, hint:'有效=MVUE'},
  {cat:'prob', stem:'充分统计量的含义是：', opts:['A. 包含了样本中关于参数的全部信息','B. 只包含部分信息','C. 不包含信息','D. 是常数'], ans:0, hint:'充分=不丢失信息'},
  {cat:'prob', stem:'Fisher信息量I(θ)衡量的是：', opts:['A. 样本中关于参数θ的信息量','B. 样本大小','C. 参数值','D. 方差'], ans:0, hint:'Fisher信息=参数可估计精度'},
  {cat:'prob', stem:'Cramér-Rao不等式给出了无偏估计方差的：', opts:['A. 下界','B. 上界','C. 精确值','D. 中位数'], ans:0, hint:'CR下界=1/I(θ)'},
  {cat:'prob', stem:'Neyman-Pearson引理用于构造：', opts:['A. 最强检验(最优检验)','B. 无偏估计','C. 置信区间','D. 回归方程'], ans:0, hint:'N-P引理=似然比检验最优'},
  {cat:'prob', stem:'χ²分布的自由度为n，则E(χ²)=', opts:['A. n','B. 2n','C. n/2','D. √n'], ans:0, hint:'E(χ²)=n'},
  {cat:'prob', stem:'t分布的自由度为n，当n→∞时t分布趋向：', opts:['A. 标准正态分布N(0,1)','B. 均匀分布','C. 指数分布','D. χ²分布'], ans:0, hint:'t(∞)=N(0,1)'},
  {cat:'prob', stem:'F分布F(m,n)的定义是：', opts:['A. 两个独立χ²变量之比除以各自自由度','B. 正态变量之比','C. 均匀变量之积','D. 指数变量之差'], ans:0, hint:'F=(χ²₁/m)/(χ²₂/n)'},
  {cat:'prob', stem:'在回归分析中，判定系数R²的含义是：', opts:['A. 回归方程对数据变异的解释比例','B. 相关系数','C. 残差','D. 截距'], ans:0, hint:'R²=SSR/SST'},
  {cat:'prob', stem:'在最小二乘法中，回归系数β̂的目标是使什么最小？', opts:['A. 残差平方和','B. 残差之和','C. 残差绝对值','D. 数据方差'], ans:0, hint:'min Σ(yi-ŷi)²'},
  {cat:'prob', stem:'正态总体均值的95%置信区间(σ已知)中的z值为：', opts:['A. 1.96','B. 1.645','C. 2.576','D. 1.28'], ans:0, hint:'95%→z=1.96'},
  {cat:'prob', stem:'正态总体均值的99%置信区间(σ已知)中的z值为：', opts:['A. 2.576','B. 1.96','C. 1.645','D. 3.0'], ans:0, hint:'99%→z=2.576'},
  {cat:'prob', stem:'第一类错误(α错误)是指：', opts:['A. 拒绝了为真的H₀','B. 接受了为假的H₀','C. 拒绝了为假的H₀','D. 接受了为真的H₀'], ans:0, hint:'弃真=α错误'},
  {cat:'prob', stem:'第二类错误(β错误)是指：', opts:['A. 未拒绝为假的H₀','B. 拒绝了为真的H₀','C. 接受了为真的H₁','D. 同时犯两种错误'], ans:0, hint:'取伪=β错误'},
  {cat:'prob', stem:'样本方差S²=(1/(n-1))Σ(Xi-X̄)²中除以n-1而不是n是为了：', opts:['A. 保证S²是σ²的无偏估计','B. 简化计算','C. 减小方差','D. 增大精度'], ans:0, hint:'n-1=Bessel校正→无偏'},
  {cat:'prob', stem:'随机变量X的分布函数F(x)的性质不包括：', opts:['A. 单调递增','B. 右连续','C. F(-∞)=0,F(+∞)=1','D. F(x)>1'], ans:3, hint:'F(x)∈[0,1]，不可能>1'},
  {cat:'prob', stem:'马尔可夫不等式P(X≥a)≤E(X)/a要求：', opts:['A. X≥0且a>0','B. X服从正态分布','C. X有限方差','D. a<0'], ans:0, hint:'Markov不等式=非负随机变量'},
  {cat:'prob', stem:'切比雪夫不等式P(|X-μ|≥kσ)≤1/k²要求的条件是：', opts:['A. X的均值和方差存在','B. X服从正态分布','C. X≥0','D. k<1'], ans:0, hint:'Chebyshev只需有限方差'},
  {cat:'prob', stem:'生成函数(母函数)M(t)=E(e^(tX))称为：', opts:['A. 矩母函数','B. 概率母函数','C. 特征函数','D. 分布函数'], ans:0, hint:'MGF=矩母函数'},
  {cat:'prob', stem:'特征函数φ(t)=E(e^(itX))的优点是：', opts:['A. 对任何分布都存在','B. 只对正态分布存在','C. 不唯一','D. 计算简单'], ans:0, hint:'特征函数总存在'},
  {cat:'linalg', stem:'Jordan标准形的对角块称为：', opts:['A. Jordan块','B. 特征块','C. 对角块','D. 子空间'], ans:0, hint:'Jordan块=λ+上方1'},
  {cat:'linalg', stem:'矩阵A的谱(Spectrum)是指：', opts:['A. A的所有特征值的集合','B. A的行列式','C. A的秩','D. A的迹'], ans:0, hint:'谱=特征值集合'},
  {cat:'linalg', stem:'幂零矩阵A的特点是存在k使得：', opts:['A. A^k=O(零矩阵)','B. A^k=I','C. A^k=A','D. A^k=2A'], ans:0, hint:'幂零=某幂次为零'},
  {cat:'linalg', stem:'矩阵的秩等于其行秩也等于其列秩，这个性质称为：', opts:['A. 秩的行列等价性','B. 行列式性质','C. 特征值性质','D. 逆矩阵定理'], ans:0, hint:'行秩=列秩=秩'},
  {cat:'calculus', stem:'Γ函数(Gamma函数)Γ(n)在n为正整数时等于：', opts:['A. (n-1)!','B. n!','C. 1/n','D. n'], ans:0, hint:'Γ(n)=(n-1)!'},
  {cat:'calculus', stem:'Beta函数B(p,q)=∫₀¹ x^(p-1)(1-x)^(q-1)dx与Gamma函数的关系是：', opts:['A. B(p,q)=Γ(p)Γ(q)/Γ(p+q)','B. B(p,q)=Γ(p+q)','C. B(p,q)=1','D. B(p,q)=p·q'], ans:0, hint:'Beta与Gamma的关系'},

  // ═══ 最后31题补齐 ═══
  {cat:'calculus', stem:'∫ sec x dx =', opts:['A. ln|sec x + tan x| + C','B. tan x + C','C. sec x tan x + C','D. ln|cos x| + C'], ans:0, hint:'sec积分公式'},
  {cat:'calculus', stem:'∫ csc x dx =', opts:['A. ln|csc x - cot x| + C','B. -cot x + C','C. csc x cot x + C','D. ln|sin x| + C'], ans:0, hint:'csc积分公式'},
  {cat:'calculus', stem:'(arctan x)\' =', opts:['A. 1/(1+x²)','B. -1/(1+x²)','C. 1/√(1-x²)','D. arctan x'], ans:0, hint:'反正切导数'},
  {cat:'calculus', stem:'(arcsin x)\' =', opts:['A. 1/√(1-x²)','B. -1/√(1-x²)','C. 1/(1+x²)','D. arcsin x'], ans:0, hint:'反正弦导数'},
  {cat:'calculus', stem:'Wallis公式∫₀^(π/2) sin^n x dx在n为偶数时结果含有：', opts:['A. π/2因子','B. 只有整数','C. e因子','D. ln因子'], ans:0, hint:'n偶→含π/2'},
  {cat:'calculus', stem:'函数在某点可导一定可微（一元函数），可微一定：', opts:['A. 连续','B. 可导','C. 有界','D. 单调'], ans:0, hint:'可微⇒连续'},
  {cat:'calculus', stem:'∫₀^π sin x dx =', opts:['A. 2','B. 0','C. π','D. 1'], ans:0, hint:'-cosx从0到π=1+1=2'},
  {cat:'calculus', stem:'反常积分∫₁^∞ 1/x² dx =', opts:['A. 1','B. ∞','C. 0','D. 1/2'], ans:0, hint:'-1/x从1到∞=1'},
  {cat:'calculus', stem:'函数f(x)=x·|x|在x=0处：', opts:['A. 可导，f\'(0)=0','B. 不可导','C. 不连续','D. 无定义'], ans:0, hint:'x>0时x²,x<0时-x²，均→0可导'},
  {cat:'calculus', stem:'隐函数求导：若y=y(x)由x²+y²=25确定，则dy/dx=', opts:['A. -x/y','B. x/y','C. -y/x','D. y/x'], ans:0, hint:'两边求导2x+2yy\'=0'},
  {cat:'calculus', stem:'参数方程x=a·cost, y=a·sint的dy/dx=', opts:['A. -cot t','B. tan t','C. -tan t','D. cot t'], ans:0, hint:'(dy/dt)/(dx/dt)=acost/(-asint)'},
  {cat:'linalg', stem:'n阶方阵A满足A²=A，则A的特征值只能是：', opts:['A. 0或1','B. 1或-1','C. 0或-1','D. 任意值'], ans:0, hint:'幂等矩阵λ²=λ→λ=0或1'},
  {cat:'linalg', stem:'若n阶矩阵A的秩r(A)=r，则A的零空间维数为：', opts:['A. n-r','B. r','C. n','D. 0'], ans:0, hint:'秩-零度定理dim(ker)=n-r'},
  {cat:'linalg', stem:'两个矩阵相似的充要条件之一是：', opts:['A. 具有相同的特征多项式','B. 具有相同的行列式','C. 具有相同的秩','D. 具有相同的迹'], ans:0, hint:'相似→相同特征多项式（必要非充分，但最接近）'},
  {cat:'linalg', stem:'实二次型f=x^TAx正定的充要条件之一是：', opts:['A. A的所有顺序主子式都大于0','B. |A|>0','C. tr(A)>0','D. A对角线元素>0'], ans:0, hint:'西尔维斯特判据'},
  {cat:'linalg', stem:'矩阵A=(2 1; 0 2)是否可对角化？', opts:['A. 不可以(特征值2的几何重数<代数重数)','B. 可以','C. 不确定','D. 只有在复数域可以'], ans:0, hint:'λ=2(二重)但特征空间维数=1'},
  {cat:'linalg', stem:'向量组{(1,0,0),(0,1,0),(0,0,1)}的秩为：', opts:['A. 3','B. 2','C. 1','D. 0'], ans:0, hint:'标准基线性无关，秩=3'},
  {cat:'linalg', stem:'齐次线性方程组Ax=0有非零解的充要条件是：', opts:['A. r(A)<n(未知数个数)','B. r(A)=n','C. |A|≠0','D. A可逆'], ans:0, hint:'秩<n→有自由变量→非零解'},
  {cat:'linalg', stem:'非齐次线性方程组Ax=b有解的充要条件是：', opts:['A. r(A)=r(A|b)','B. r(A)<r(A|b)','C. |A|≠0','D. A可逆'], ans:0, hint:'增广矩阵秩=系数矩阵秩'},
  {cat:'prob', stem:'设X~N(0,1)，则E(X²)=', opts:['A. 1','B. 0','C. 2','D. 1/2'], ans:0, hint:'D(X)=E(X²)-[E(X)]²，D=1,E=0→E(X²)=1'},
  {cat:'prob', stem:'设X~N(μ,σ²)，则(X-μ)/σ服从：', opts:['A. N(0,1)','B. N(μ,1)','C. t分布','D. χ²分布'], ans:0, hint:'标准化'},
  {cat:'prob', stem:'n个独立的N(0,1)变量的平方和服从：', opts:['A. χ²(n)','B. t(n)','C. F(n,n)','D. N(0,n)'], ans:0, hint:'χ²分布定义'},
  {cat:'prob', stem:'若X₁,...,Xₙ来自N(μ,σ²)，则(X̄-μ)/(S/√n)服从：', opts:['A. t(n-1)','B. N(0,1)','C. χ²(n-1)','D. F(1,n-1)'], ans:0, hint:'t分布定义'},
  {cat:'prob', stem:'若P(A)=0.6, P(B|A)=0.5，则P(AB)=', opts:['A. 0.3','B. 0.5','C. 0.6','D. 0.1'], ans:0, hint:'P(AB)=P(A)×P(B|A)=0.3'},
  {cat:'prob', stem:'连续型随机变量X在某一点的概率P(X=a)=', opts:['A. 0','B. f(a)','C. F(a)','D. 1'], ans:0, hint:'连续型单点概率=0'},
  {cat:'prob', stem:'离散型随机变量X的分布函数F(x)是：', opts:['A. 阶梯函数','B. 连续函数','C. 可导函数','D. 常数函数'], ans:0, hint:'离散→跳跃→阶梯'},
  {cat:'prob', stem:'二维随机变量(X,Y)的联合分布函数F(x,y)=P(X≤x,Y≤y)满足：', opts:['A. F(+∞,+∞)=1','B. F(+∞,+∞)=0','C. F(0,0)=1','D. F(-∞,-∞)=1'], ans:0, hint:'F(+∞,+∞)=P(全集)=1'},
  {cat:'prob', stem:'Cov(aX,bY)=', opts:['A. ab·Cov(X,Y)','B. Cov(X,Y)','C. (a+b)Cov(X,Y)','D. a²b²Cov(X,Y)'], ans:0, hint:'协方差的双线性性'},
  {cat:'prob', stem:'D(X+Y)=D(X)+D(Y)成立的条件是：', opts:['A. X和Y不相关(或独立)','B. 无条件','C. X=Y','D. X和Y相关'], ans:0, hint:'不相关→方差可加'},
  {cat:'prob', stem:'设X和Y独立，则E(XY)=', opts:['A. E(X)·E(Y)','B. E(X)+E(Y)','C. E(X)-E(Y)','D. 0'], ans:0, hint:'独立→期望可乘'},
  {cat:'calculus', stem:'空间曲线的曲率κ衡量的是曲线的：', opts:['A. 弯曲程度','B. 长度','C. 面积','D. 体积'], ans:0, hint:'曲率=弯曲程度'},
];

// 导出题库
if (typeof window !== 'undefined') window.MATH_QUESTIONS = MATH_QUESTIONS;
